---
title: "Ad Hoc - Time Since Verification with No Baseline Collection"
author: "Kelsey Dowling"
date: "`r Sys.Date()`"
header-includes:  
    \usepackage[labelformat=empty]{caption}
    \usepackage{placeins}
    \usepackage{booktabs}
    \usepackage{pdflscape}


output:
  pdf_document:
    extra_dependencies: ["float"]
    toc: false
    keep_tex: yes
    fig_width: 7
    fig_height: 5
    fig_caption: true
    latex_engine: xelatex
    df_print: paged 

---

```{r setup,eval=TRUE,include=FALSE,echo=FALSE, warning=FALSE}


#old.packages()
#update.packages()  


library(bigrquery)
library(data.table) ###to write or read and data management 
library(dplyr) ###data management
# library(boxr) ###read or write data from/to box
library(tidyverse) ###for data management
library(reshape)  ###to work on transition from long to wide or wide to long data
library(listr) ###to work on a list of vector, files or..
library(sqldf) ##sql
library(lubridate) ###date time
library(ggplot2) ###plots
#library(ggpubr) ###for the publications of plots
library(RColorBrewer) ###visions color http://www.sthda.com/english/wiki/colors-in-r
library(gridExtra)
library(stringr) ###to work on patterns, charaters
#library(plyr)
library(tinytex) #for pdf
library(rmarkdown) ###for the output tables into other files: pdf, rtf, etc.
library(janitor) #to get the summary sum
library(finalfit) #https://cran.r-project.org/web/packages/finalfit/vignettes/export.html t
library(expss) ###to add labels
library(epiDisplay) ##recommended applied here crosstable, tab1
library(summarytools) ##recommended
library(gmodels) ##recommended
library(magrittr)
library(arsenal)
library(gtsummary)
library(kableExtra)
library(gt)
library(crosstable)
library(cowplot)
library(webshot2)
library(glue) 
#options(knitr.table.format = "latex")
currentDate <- Sys.Date()

bq_auth()

### Set Box folders for output CSV files #######################################
use_test_box_folder <- TRUE # Local user sets this (Jake or Kelsey)

# Over-ride if using plumber api on GCP (USER DOESN'T TOUCH THIS!)
# Check if the environment variable exists and is not empty
if (!is.null(Sys.getenv("USE_TEST_BOX_FOLDER")) &&
    Sys.getenv("USE_TEST_BOX_FOLDER") != "") {
  use_test_box_folder <- as.logical(Sys.getenv("USE_TEST_BOX_FOLDER"))
}

if (use_test_box_folder) {
  boxfolder <- 222593912729 # test box folder
} else {
  boxfolder <- 221280601453 # destination of CSV files (not pdf)
}


##### Making sure personal C drives aren't referenced if this code is being used by others


#Change to FALSE if referencing this code
write_to_local_drive = F #F

#local_drive="C:/Users/dowlingk2/Documents/Module-Missingness-and-Metrics/data/"    


### This function below is put before any write.csv functions, and "filename" is updated. It determines wheteher the file will be created locally or not.
#filename=
local_drive= ifelse(write_to_local_drive, "C:/Users/dowlingk2/Documents/Module-Missingness-and-Metrics/data/", "")

```

```{r BQPull, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}
##import data to R

project <- "nih-nci-dceg-connect-prod-6d04"
billing <- "nih-nci-dceg-connect-prod-6d04" ##project and billing should be consistent
bio_tb <- bq_project_query(project, query='SELECT * FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.biospecimen_JP` where Connect_ID is not null')  #d_410912345 is not null
biospe <- bq_table_download(bio_tb,bigint="integer64",n_max = Inf, page_size = 1000)
cnames <- names(biospe)
###to check variables in recr_noinact_wl1

numbers_only <- function(x) !grepl("\\D", x)

for (i in 1: length(cnames)){
  varname <- cnames[i]
  var<-pull(biospe,varname)
  biospe[,cnames[i]] <- ifelse(numbers_only(var), as.numeric(as.character(var)), var)
}
tb_box <- bq_project_query(project, query="SELECT * FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.boxes_JP`")
box_wl_flat <- bigrquery::bq_table_download(tb_box,bigint="integer64",n_max = Inf, page_size = 1000)
#y <- read_table(urlfile1,header = TRUE, sep = "\t", na.strings = c("NA","N/A",""),fill = TRUE, quote='')
library(rio)
dictionary <- rio::import("https://episphere.github.io/conceptGithubActions/aggregate.json",format = "json")
dd<-rbindlist(dictionary,fill=TRUE,use.names=TRUE,idcol="CID") #THIS TABLE HAS REPLICATED (CIDS+LABELS) WITH DIFFERENT VARIABLE NAMES,
# dd <- as.data.frame(do.call("rbind",dictionary))
# colnames(dd) <- c("Variable Label", "Variable Name")
# dd$CID <- rownames(dd)
box_CID <- as.data.frame(as.numeric(sapply((strsplit(colnames(box_wl_flat),"d_")),tail,1)))
box_CID$variable <- colnames(box_wl_flat)
colnames(box_CID)[1] <-"CID"
box_CID_dd <- base::merge(box_CID, dd,by="CID",all.x=TRUE)
#to convert the numeric variables
numbers_only <- function(x) !grepl("\\D", x)
 cnames <- names(box_wl_flat)
 ###to check variables in recr_noinact_wl1
 data2 <- box_wl_flat
 for (i in 1: length(cnames)){
   varname <- cnames[i]
   var<-pull(data2,varname)
   data2[,cnames[i]] <- ifelse(numbers_only(var), as.numeric(as.character(var)), var)
 }
# 
pct_tb <- function(x,y){
  table1 <- CrossTable(x,y, prop.t=FALSE, prop.r=FALSE, prop.c=TRUE,chisq=FALSE)
  pct <- as.data.frame(cbind(table1$prop.row,table1$t))
  if(ncol(pct)==2){
    total <- as.numeric(sum(pct[,2]))
    pct[nrow(pct)+1,c(1:2)] <- c(1,total)
    rownames(pct)[nrow(pct)] <- "Total"
    colnames(pct)[1] <- paste0("pct_",colnames(pct)[1])
    colnames(pct)[2] <- paste0("n_",colnames(pct)[2])
    
  }
  else  if(ncol(pct)>2 ){
    total <- as.numeric(sum(pct[,3] + pct[,4]))
    pct[nrow(pct)+1,c(1:4)] <- c(sum(pct[,3])/total,sum(pct[,4])/total,sum(pct[,3]),sum(pct[,4]))
    rownames(pct)[nrow(pct)] <- "Total"
    colnames(pct)[c(1:2)] <- paste0("pct_",colnames(pct[c(1:2)]))
    colnames(pct)[c(3:4)] <- paste0("n_",colnames(pct)[c(3:4)])
  
    pct[,5] <- paste0(format(pct[,3],big.mark=","), " (",round(100*pct[,1],1), " %)")
    pct[,6] <- paste0(format(pct[,4],big.mark=","), " (",round(100*pct[,2],1), " %)") 
    colnames(pct)[5] <- paste0("n_",colnames(pct)[1])
    colnames(pct)[6] <- paste0("n_",colnames(pct)[2])
  }
return(pct)
}
##to select biospecimen data in recruitment 
recr_var <- bq_project_query(project, query="SELECT * FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect`.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS WHERE table_name='participants_JP'")
recrvar <- bigrquery::bq_table_download(recr_var, bigint="integer64",n_max = Inf, page_size = 10000)
urlfile<- "https://raw.githubusercontent.com/episphere/conceptGithubActions/master/csv/masterFile.csv" ###to grab the updated dd from github 
y <- read.csv(urlfile)
recrvar_nd <- recrvar[which(grepl("d_",recrvar$column_name)),c("column_name","field_path")]
recrvar_nd$last.CID <- ifelse(grepl("d_",recrvar_nd$column_name),substring(sapply(strsplit(recrvar_nd$column_name,"d_"),tail,1),1,9),NA)
recrvar_nd_label <- base::merge(recrvar_nd, y[,c("Primary.Source","conceptId.2","conceptId.3","Variable.Label","conceptId.4")],by.x="last.CID",by.y="conceptId.3",all.x=TRUE)
recrvar.bio <- recrvar_nd_label[which(recrvar_nd_label$Primary.Source == "Biospecimen" | grepl("biospecimen|blood|urine|mouthwash|Blood|Urine|Mouthwash|collection",recrvar_nd_label$Variable.Label)),] #49 updated due to the changes of the master DD
recrvar.bio <- recrvar.bio[!duplicated(recrvar.bio[,c("last.CID","column_name")]),] #53 updated 10/05/2023 due to the updated dictionary
query <- recrvar.bio$column_name
select <- paste(recrvar.bio$column_name,collapse=",")
#tb_bq <- eval(parse(text=paste("bq_project_query(project, query=\"SELECT token,Connect_ID,d_512820379,d_821247024,d_914594314,d_827220437,d_699625233, date,", select,"FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.participants_JP` Where d_821247024 = '197316935' \")",sep=" ")))

tb_bq <- eval(parse(text=paste("bq_project_query(project, query=\"SELECT token,Connect_ID,d_512820379,d_821247024,d_914594314,d_827220437,d_699625233, date,d_265193023, d_822499427, d_222161762,", select,"FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.participants_JP` Where d_821247024 = '197316935' \")",sep=" ")))
 
recr.bio <- bigrquery::bq_table_download(tb_bq,bigint="integer64",n_max = Inf, page_size = 10000)
##below are the commone variables in the recruitment table on Biospecimen to apply for the analysis. In case any new variables popping up, i would like #to use the one above directly from the resources (master DD and recruitment table schema to get the most updated version on this biospecimen data
# tb <- bq_project_query(project, query="SELECT d_512820379,d_512820379, d_821247024, d_914594314, d_822499427, d_222161762, Connect_ID, d_827220437, token,d_265193023, d_878865966, d_167958071, d_684635302, d_253883960, d_534669573, d_764863765, d_331584571_d_266600170_d_135591601,d_331584571_d_266600170_d_840048338,  d_331584571_d_266600170_d_343048998, d_173836415_d_266600170_d_139245758, d_173836415_d_266600170_d_185243482,
# d_173836415_d_266600170_d_198261154, d_173836415_d_266600170_d_210921343, d_173836415_d_266600170_d_224596428,
# d_173836415_d_266600170_d_316824786, d_173836415_d_266600170_d_341570479, d_173836415_d_266600170_d_398645039,
# d_173836415_d_266600170_d_448660695, d_173836415_d_266600170_d_452847912, d_173836415_d_266600170_d_453452655,
# d_173836415_d_266600170_d_530173840, d_173836415_d_266600170_d_534041351, d_173836415_d_266600170_d_541311218,
# d_173836415_d_266600170_d_561681068, d_173836415_d_266600170_d_592099155, d_173836415_d_266600170_d_611091485,
# d_173836415_d_266600170_d_646899796, d_173836415_d_266600170_d_693370086, d_173836415_d_266600170_d_718172863,
# d_173836415_d_266600170_d_728696253, d_173836415_d_266600170_d_740582332, d_173836415_d_266600170_d_769615780,
# d_173836415_d_266600170_d_786930107, d_173836415_d_266600170_d_822274939, d_173836415_d_266600170_d_847159717,
# d_173836415_d_266600170_d_860477844, d_173836415_d_266600170_d_915179629, d_173836415_d_266600170_d_939818935,
# d_173836415_d_266600170_d_951355211, d_173836415_d_266600170_d_982213346 FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.participants_JP` WHERE d_821247024 = '197316935'")
##to convert to numeric
cnames <- names(recr.bio)
recrver <- recr.bio
for (i in 1: length(cnames)){
  varname <- cnames[i]
  var<-pull(recrver,varname)
  recrver[,cnames[i]] <- ifelse(numbers_only(var), as.numeric(as.character(var)), var)
}
##to get the labels of each variable
recrver_CID <- as.data.frame(sapply((strsplit(colnames(recrver),"d_")),tail,1))
colnames(recrver_CID)[1] <- "CID"
recrver_CID$variable <- names(recr.bio)
recrver_ver1 <- base::merge(dd,recrver_CID,by="CID")
recrver1 <- expss::apply_labels(recrver,
                        d_512820379 = "Recruitment type",#RcrtSI_RecruitType_v1r0
                        d_512820379=c(	"Not active"=180583933,  
                                       "Active"= 486306141, 
                                       "Passive"=854703046),
                        d_821247024 = "Verification status", #RcrtV_Verification_v1r0
                        d_821247024 = c("Not yet verified" =875007964,
                                        "Verified"=197316935,  
                                        "Cannot be verified"=219863910, 
                                        "Duplicate"=922622075 , 
                                        "Outreach timed out"= 160161595),
                        d_827220437 = "Site",#RcrtES_Site_v1r0
                        d_827220437 = c("HealthPartners"= 531629870, "Henry Ford Health System"=548392715,"Marshfield Clinic Health System" = 303349821,"Sanford Health" = 657167265, "University of Chicago Medicine" = 809703864,"Kaiser Permanente Colorado" = 125001209,"Kaiser Permanente Georgia" = 327912200,"Kaiser Permanente Hawaii" = 300267574,"Kaiser Permanente Northwest" = 452412599,"National Cancer Institute" = 517700004,"National Cancer Institute" = 13,"Other" = 181769837),
                        d_914594314 = "Verification status time",   #RcrtV_VerificationTm_V1R0
                        d_878865966 = "Baseline blood sample collected", #BioFin_BaseBloodCol_v1r0
                        d_878865966 = c("Any blood collected"=353358909, "No blood collected"=104430631),
                        d_173836415_d_266600170_d_561681068 = "Date/time basline Research Blood Collected",#BL_BioFin_BBTime_v1r0
                        d_684635302 = "Baseline Mouthwash Collected",    #BioFin_BaseMWCol_v1r0
                        d_684635302 = c("Any mouthwash collected"=353358909,"No mouthwash collected"= 104430631  ),
                        d_173836415_d_266600170_d_448660695 = "Date/time Mouthwash Collected", #
                        d_167958071 = "Baseline Urine collected", 
                        d_167958071 = c( "Any urine collected"=353358909, "No urine collected"=104430631),
                        d_173836415_d_266600170_d_847159717 = "Baseline Date/time Urine collected",
                        d_331584571_d_266600170_d_135591601 = "Baseline Check-In Complete",#BL_BioChk_Complete_v1r0
                        d_331584571_d_266600170_d_135591601 =  c( "No"=104430631, "Yes"=353358909 ),
                        d_331584571_d_266600170_d_840048338 = "Date/Time Baseline Check-In Complete",
                        d_331584571_d_266600170_d_343048998 = "Time Baseline check out complete",#
                        
                        d_173836415_d_266600170_d_530173840 = "Blood Order Placed",#BioClin_BldOrderPlaced_v1r0  ## I ADDED
                        d_173836415_d_266600170_d_530173840 =c( "No"=104430631, "Yes"=353358909 ), ## I ADDED
                        
                        d_173836415_d_266600170_d_592099155 = "Blood Collection Setting",#BL_BioSpm_BloodSetting_v1r0  
                        d_173836415_d_266600170_d_592099155 =c("Research"=534621077, "Clinical"= 664882224,"Home" =103209024),
                        d_173836415_d_266600170_d_718172863 = "Urine Collection Setting",#BL_BioSpm_UrineSetting_v1r0
                        d_173836415_d_266600170_d_718172863 =c("Research"=534621077, "Clinical"= 664882224,"Home" =103209024),
                        d_173836415_d_266600170_d_915179629 = "Mouthwash Collection Setting",#BL_BioSpm_MWSetting_v1r0
                        d_173836415_d_266600170_d_915179629 =c("Research"=534621077, "Clinical"= 664882224,"Home" =103209024),
                        
                        d_265193023 = "Blood/urine/mouthwash combined research survey-Complete",   
                        d_265193023 = c(	"Not Started" =	972455046, "Started"= 615768760,"Submitted"= 231311385),#SrvBLM_ResSrvCompl_v1r0
                        d_822499427 = "Placeholder (Autogenerated) - Date/time Status of Start of blood/urine/mouthwash research survey",#SrvBLM_TmStart_v1r0
                        d_222161762  = "Placeholder (Autogenerated)- Date/Time blood/urine/mouthwash research survey completed" #   SrvBLM_TmComplete_v1r0
)
###to convert to categorical variables
recrver1$RcrtSI_RecruitType_v1r0 <- factor(recrver1$d_512820379, exclude=NULL)
recrver1$RcrtV_Verification_v1r0 <- factor(recrver1$d_821247024, exclude=NULL)
recrver1$BioFin_BaseMWCol_v1r0  <-factor(recrver1$d_684635302,exclude=NULL)
recrver1$BioFin_BaseBloodCol_v1r0 <- factor(recrver1$d_878865966,exclude=NULL)
recrver1$BioFin_BaseUrineCol_v1r0 <- factor(recrver1$d_167958071,exclude=NULL)

recrver1$BioClin_BldOrderPlaced_v1r0 <- factor(recrver1$d_173836415_d_266600170_d_530173840,exclude=NULL) ## I ADDED

recrver1$SrvBLM_ResSrvCompl_v1r0 <-factor(recrver1$d_265193023,exclude=NULL)
recrver1$BL_BioSpm_MWSetting_v1r0 <- factor(recrver1$d_173836415_d_266600170_d_915179629,levels=c("Clinical","Research","Home"))  
recrver1$BL_BioSpm_UrineSetting_v1r0 <- factor(recrver1$d_173836415_d_266600170_d_718172863, levels=c("Clinical","Research","Home"))  
recrver1$BL_BioSpm_BloodSetting_v1r0 <- factor(recrver1$d_173836415_d_266600170_d_592099155,levels=c("Clinical","Research","Home"))  
recrver1$BL_BioChk_Complete_v1r0 <- factor(recrver1$d_331584571_d_266600170_d_135591601,exclude=NULL)
recrver1$Site <-factor(recrver1$d_827220437,levels=c("HealthPartners", "Henry Ford Health System","Marshfield Clinic Health System",
                             "Sanford Health", "University of Chicago Medicine","Kaiser Permanente Colorado",
                             "Kaiser Permanente Georgia","Kaiser Permanente Hawaii","Kaiser Permanente Northwest",
                             "National Cancer Institute","Other"))
recrver1<- recrver1 %>% mutate(BldCollection = ifelse(recrver1$BioFin_BaseBloodCol_v1r0 == 353358909, "YES", "No"))

##to update the censoring time based on Kelsey's request to be consistent with the weekly log: from Monday to Sunday
veristart.date = as.Date(min(as.POSIXct(recr.bio$d_914594314),na.rm=TRUE))
veristart.date + days(5)
#[1] "2021-08-01"
recrver1$verified.week <- ceiling(as.numeric(difftime(as.Date(ymd_hms(recrver1$d_914594314)),as.Date(veristart.date-days(2)),units="days"))/7)
recrver1$verified.Sunday.date <- veristart.date + days(5)+ dweeks(recrver1$verified.week-1)



##to check the duplicate collection by verified participants Connect_ID
biospe[duplicated(biospe$Connect_ID),c("Connect_ID","d_820476880","d_410912345","d_387108065")]
biospe[duplicated(biospe$Connect_ID),"Connect_ID"]
biospe$Connect_ID[duplicated(biospe$Connect_ID)]
dupid <- biospe$Connect_ID[duplicated(biospe$Connect_ID)]
#biospe[which(biospe$Connect_ID %in% dupid),c("Connect_ID","d_820476880","d_410912345","d_387108065","d_143615646_d_593843561","d_973670172_d_593843561")]
##the biospecimen concepts for the biospecimen variablesbles
biospe_var <- as.data.frame((colnames(biospe)))
colnames(biospe_var)[1] <- "variable"
biospe_var$cid1 <- sapply(strsplit(colnames(biospe),"_"), "[", 2)
biospe_var$cid2 <- sapply(strsplit(colnames(biospe),"_"), "[", 4)
biospe_var$cid3 <- sapply(strsplit(colnames(biospe),"_"), "[", 6)
biospe_var$cid_tail <- sapply(strsplit(colnames(biospe),"_"), tail,1)
biospe_CID <- dd[which(dd$CID %in% CID),]
biospe_dd<- base::merge(biospe_var,biospe_CID,by.x="cid_tail",by.y="CID", all.x=TRUE)
tubes <- dd[grepl(" Tube ",dd$`Variable Label`),]
urine <- dd[grepl("Urine",dd$`Variable Label`),]
mouthwash <- dd[grepl("Mouthwash",dd$`Variable Label`),]



```



```{r Table1, warning=FALSE, eval=TRUE,echo=FALSE}

#Denominator
  #recrver1$d_821247024 == verified --> all participants in this BQ pull are verfied already
  #d_410912345 is null
#Numerator
  # days between today and verification date d_914594314, confirmed none are null



recrver1 <- recrver1 %>% mutate(BiospeCollection = ifelse((recrver1$d_684635302 == 353358909 | recrver1$d_878865966 == 353358909| recrver1$d_167958071 == 353358909), "Any biospecimen Collections","No biospecimen collections"))

recrver1$Site<- droplevels(recrver1$Site)



bio.appoint <- biospe %>% arrange(Connect_ID, d_410912345) %>% group_by(Connect_ID) %>% summarise(d_410912345=mean(d_410912345,na.rm=TRUE)) #to remove the multiple collections by Connect_ID
 
biocol.tb <- base::merge(recrver1[,c("Connect_ID","Site","BiospeCollection","d_878865966","d_684635302","d_167958071", "d_914594314")],bio.appoint,by.x="Connect_ID",by.y="Connect_ID",all.x=TRUE )
 
table1 <- biocol.tb %>% filter(recrver1$d_821247024==197316935) %>%
  mutate(#appointment = ifelse((d_410912345!= 353358909 | is.na(d_410912345)), 104430631, 353358909),
         biocol.appoint = case_when(BiospeCollection == "Any biospecimen Collections" & d_410912345== 353358909 ~ "Baseline Collection",
                                    #BiospeCollection == "No biospecimen collections" & (d_410912345!= 353358909 | is.na(d_410912345)) ~ "No Baseline Collection"
                                    TRUE ~ "No Baseline Collection"))  



#RESEARCH 
currentDate <- Sys.Date()

ver_date_diff <-table1  %>% filter(biocol.appoint=="No Baseline Collection")  %>% group_by(Site) %>% 
  mutate(day_past = difftime(as.Date(currentDate), as.Date(d_914594314), units="days"),
         coll_days_diff = ifelse(as.numeric(day_past)<30,"< 30 Days",
                                 ifelse(as.numeric(day_past)<60,"30 to <60 Days",
                                        ifelse(as.numeric(day_past)<90,"60 to <90 Days",
                                        ifelse(as.numeric(day_past)<180,"90 to 180 Days",
                                               ifelse(as.numeric(day_past)<270,"180 to <270 Days",
                                                             "270 Days or More"))))))


ver_date_diff$Connect_ID <- as.numeric(ver_date_diff$Connect_ID)

table.coll_bptl <- ctable(ver_date_diff$Site,ver_date_diff$coll_days_diff)
crosstable.coll_bptl <- as.data.frame(cbind(table.coll_bptl$cross_table,table.coll_bptl$proportions))
crosstable.coll_bptl$Sites <-trimws(rownames(crosstable.coll_bptl))


crosstable.coll_bptl$n_pct_30_Day <-  paste(format(crosstable.coll_bptl[,1],big.mark=","),"(", round(100*crosstable.coll_bptl[,8],1),"%)",sep=" ")
crosstable.coll_bptl$n_pct_60_Day <-  paste(format(crosstable.coll_bptl[,4],big.mark=","),"(", round(100*crosstable.coll_bptl[,11],1),"%)",sep=" ")
crosstable.coll_bptl$n_pct_90_Day <-  paste(format(crosstable.coll_bptl[,5],big.mark=","),"(", round(100*crosstable.coll_bptl[,12],1),"%)",sep=" ")
crosstable.coll_bptl$n_pct_180_Day <-  paste(format(crosstable.coll_bptl[,6],big.mark=","),"(", round(100*crosstable.coll_bptl[,13],1),"%)",sep=" ")
crosstable.coll_bptl$n_pct_270_Day <-  paste(format(crosstable.coll_bptl[,2],big.mark=","),"(", round(100*crosstable.coll_bptl[,9],1),"%)",sep=" ")
crosstable.coll_bptl$n_pct_270_plus_days =  paste(format(crosstable.coll_bptl[,3],big.mark=","),"(", round(100*crosstable.coll_bptl[,10],1),"%)",sep=" ")
crosstable.coll_bptl$Total <- paste(crosstable.coll_bptl$Total, " (100%)")
#nrow(crosstable.coll_bptl)
         
crosstable.coll_bptl1 <- crosstable.coll_bptl[, c(15:21, 7)]

#crosstable.coll_bptl1 %>% gt(groupname_col = "Site")



library(kableExtra)


coll_bplt_knitr <- knitr::kable(crosstable.coll_bptl1, col.names=c("Site", "< 30 Days", "30 to <60 Days","60 to <90 Days", "90 to <180 Days", "180 to <270 Days", "270 Days or More", "Total"), caption='Time (In Days) Since Verification Among Participants with No Baseline Biospecimen Collection by Site', row.names=FALSE, align=c("l","c","c","c","c","c","c","c"), booktabs = TRUE) %>% kable_styling(latex_options = "scale_down") 
coll_bplt_knitr
```

