---
title: "Ad-Hoc UC Biospecimen Metrics"
author: "Kelsey Dowling"
date: "Data Extracted and Report Ran: `r Sys.Date()`"
header-includes:  
    \usepackage[labelformat=empty]{caption}
    \usepackage{placeins}
    \usepackage{booktabs}
    \usepackage{pdflscape}


output:
  pdf_document:
    extra_dependencies: ["float"]
    toc: false
    keep_tex: yes
    fig_width: 7
    fig_height: 5
    fig_caption: true

    df_print: paged 
---



```{r setup,eval=TRUE,include=FALSE,echo=FALSE, warning=FALSE}


#    latex_engine: xelatex

#old.packages()
#update.packages()  


library(bigrquery)
library(data.table) ###to write or read and data management 
library(dplyr) ###data management
# library(boxr) ###read or write data from/to box
library(tidyverse) ###for data management
library(reshape)  ###to work on transition from long to wide or wide to long data
library(listr) ###to work on a list of vector, files or..
library(sqldf) ##sql
library(lubridate) ###date time
library(ggplot2) ###plots
#library(ggpubr) ###for the publications of plots
library(RColorBrewer) ###visions color http://www.sthda.com/english/wiki/colors-in-r
library(gridExtra)
library(stringr) ###to work on patterns, charaters
#library(plyr)
library(tinytex) #for pdf
library(rmarkdown) ###for the output tables into other files: pdf, rtf, etc.
library(janitor) #to get the summary sum
library(finalfit) #https://cran.r-project.org/web/packages/finalfit/vignettes/export.html t
library(expss) ###to add labels
library(epiDisplay) ##recommended applied here crosstable, tab1
library(summarytools) ##recommended
library(gmodels) ##recommended
library(magrittr)
library(arsenal)
library(gtsummary)
library(kableExtra)
library(gt)
library(crosstable)
library(cowplot)
library(webshot2)
library(glue) 
#options(knitr.table.format = "latex")
currentDate <- Sys.Date()

bq_auth()

### Set Box folders for output CSV files #######################################
use_test_box_folder <- TRUE # Local user sets this (Jake or Kelsey)

# Over-ride if using plumber api on GCP (USER DOESN'T TOUCH THIS!)
# Check if the environment variable exists and is not empty
if (!is.null(Sys.getenv("USE_TEST_BOX_FOLDER")) &&
    Sys.getenv("USE_TEST_BOX_FOLDER") != "") {
  use_test_box_folder <- as.logical(Sys.getenv("USE_TEST_BOX_FOLDER"))
}

if (use_test_box_folder) {
  boxfolder <- 222593912729 # test box folder
} else {
  boxfolder <- 221280601453 # destination of CSV files (not pdf)
}


##### Making sure personal C drives aren't referenced if this code is being used by others


#Change to FALSE if referencing this code
write_to_local_drive = F #F

#local_drive="C:/Users/dowlingk2/Documents/Module-Missingness-and-Metrics/data/"    


### This function below is put before any write.csv functions, and "filename" is updated. It determines wheteher the file will be created locally or not.
#filename=
local_drive= ifelse(write_to_local_drive, "C:/Users/dowlingk2/Documents/Module-Missingness-and-Metrics/data/", "")

```


```{r BQPull, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}
##import data to R

project <- "nih-nci-dceg-connect-prod-6d04"
billing <- "nih-nci-dceg-connect-prod-6d04" ##project and billing should be consistent

bio_tb <- bq_project_query(project, query='SELECT * FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.biospecimen_JP` where d_410912345 is not null')  
biospe <- bq_table_download(bio_tb,bigint="integer64",n_max = Inf) #, page_size = 1000)

cnames <- names(biospe)
###to check variables in recr_noinact_wl1

numbers_only <- function(x) !grepl("\\D", x)

for (i in 1: length(cnames)){
  varname <- cnames[i]
  var<-pull(biospe,varname)
  biospe[,cnames[i]] <- ifelse(numbers_only(var), as.numeric(as.character(var)), var)
}
tb_box <- bq_project_query(project, query="SELECT * FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.boxes_JP`")
box_wl_flat <- bigrquery::bq_table_download(tb_box,bigint="integer64",n_max = Inf, page_size = 1000)
#y <- read_table(urlfile1,header = TRUE, sep = "\t", na.strings = c("NA","N/A",""),fill = TRUE, quote='')

library(readr)
urlfile<- "https://raw.githubusercontent.com/episphere/conceptGithubActions/master/csv/masterFile.csv" ###to grab the updated dd from github
y <- read.csv(urlfile) #the masterDD has just been updated which can't easily pulled from github directly as before. I need to download from the raw file in the github
#y <- read_table(urlfile1,header = TRUE, sep = "\t", na.strings = c("NA","N/A",""),fill = TRUE, quote='')

library(rio)
dictionary <- rio::import("https://episphere.github.io/conceptGithubActions/aggregate.json",format = "json")
dd<-rbindlist(dictionary,fill=TRUE,use.names=TRUE,idcol="CID") #THIS TABLE HAS REPLICATED (CIDS+LABELS) WITH DIFFERENT VARIABLE NAMES,
# dd <- as.data.frame(do.call("rbind",dictionary))
# colnames(dd) <- c("Variable Label", "Variable Name")
# dd$CID <- rownames(dd)
box_CID <- as.data.frame(as.numeric(sapply((strsplit(colnames(box_wl_flat),"d_")),tail,1)))
box_CID$variable <- colnames(box_wl_flat)
colnames(box_CID)[1] <-"CID"
box_CID_dd <- base::merge(box_CID, dd,by="CID",all.x=TRUE)
#to convert the numeric variables
numbers_only <- function(x) !grepl("\\D", x)
 cnames <- names(box_wl_flat)
 ###to check variables in recr_noinact_wl1
 data2 <- box_wl_flat
 for (i in 1: length(cnames)){
   varname <- cnames[i]
   var<-pull(data2,varname)
   data2[,cnames[i]] <- ifelse(numbers_only(var), as.numeric(as.character(var)), var)
 }
# 
pct_tb <- function(x,y){
  table1 <- CrossTable(x,y, prop.t=FALSE, prop.r=FALSE, prop.c=TRUE,chisq=FALSE)
  pct <- as.data.frame(cbind(table1$prop.row,table1$t))
  if(ncol(pct)==2){
    total <- as.numeric(sum(pct[,2]))
    pct[nrow(pct)+1,c(1:2)] <- c(1,total)
    rownames(pct)[nrow(pct)] <- "Total"
    colnames(pct)[1] <- paste0("pct_",colnames(pct)[1])
    colnames(pct)[2] <- paste0("n_",colnames(pct)[2])
    
  }
  else  if(ncol(pct)>2 ){
    total <- as.numeric(sum(pct[,3] + pct[,4]))
    pct[nrow(pct)+1,c(1:4)] <- c(sum(pct[,3])/total,sum(pct[,4])/total,sum(pct[,3]),sum(pct[,4]))
    rownames(pct)[nrow(pct)] <- "Total"
    colnames(pct)[c(1:2)] <- paste0("pct_",colnames(pct[c(1:2)]))
    colnames(pct)[c(3:4)] <- paste0("n_",colnames(pct)[c(3:4)])
  
    pct[,5] <- paste0(format(pct[,3],big.mark=","), " (",round(100*pct[,1],1), " %)")
    pct[,6] <- paste0(format(pct[,4],big.mark=","), " (",round(100*pct[,2],1), " %)") 
    colnames(pct)[5] <- paste0("n_",colnames(pct)[1])
    colnames(pct)[6] <- paste0("n_",colnames(pct)[2])
  }
return(pct)
}
##to select biospecimen data in recruitment 
recr_var <- bq_project_query(project, query="SELECT * FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect`.INFORMATION_SCHEMA.COLUMN_FIELD_PATHS WHERE table_name='participants_JP'")
recrvar <- bigrquery::bq_table_download(recr_var, bigint="integer64",n_max = Inf, page_size = 10000)
urlfile<- "https://raw.githubusercontent.com/episphere/conceptGithubActions/master/csv/masterFile.csv" ###to grab the updated dd from github 
y <- read.csv(urlfile)
recrvar_nd <- recrvar[which(grepl("d_",recrvar$column_name)),c("column_name","field_path")]


recrvar_nd$last.CID <- ifelse(grepl("d_",recrvar_nd$column_name),substring(sapply(strsplit(recrvar_nd$column_name,"d_"),tail,1),1,9),NA)
recrvar_nd_label <- base::merge(recrvar_nd, y[,c("Primary.Source","conceptId.2","conceptId.3","Variable.Label","conceptId.4","Current.Format.Value")],by.x="last.CID",by.y="conceptId.3",all.x=TRUE)


#recrvar_nd_label <- base::merge(recrvar_nd, y[,c("Primary.Source","conceptId.2","conceptId.3","Variable.Label","conceptId.4")],by.x="last.CID",by.y="conceptId.3",all.x=TRUE)
#recrvar.bio <- recrvar_nd_label[which(recrvar_nd_label$Primary.Source == "Biospecimen" | grepl("biospecimen|blood|urine|mouthwash|Blood|Urine|Mouthwash|collection",recrvar_nd_label$Variable.Label)),] #49 updated due to the changes of the master DD
#recrvar.bio <- recrvar.bio[!duplicated(recrvar.bio[,c("last.CID","column_name")]),] #53 updated 10/05/2023 due to the updated dictionary #should this line be kept?

recrvar.bio <- recrvar_nd_label[which(recrvar_nd_label$Primary.Source =="Biospecimen" | grepl("biospecimen|blood|urine|mouthwash|collection|Blood|Urine|Mouthwash|MW|Ur|Ur Surv|MW Surv",recrvar_nd_label$Variable.Label)),] #49
query <- unique(recrvar.bio$column_name)

select <- paste(recrvar.bio$column_name,collapse=",")
#tb_bq <- eval(parse(text=paste("bq_project_query(project, query=\"SELECT token,Connect_ID,d_512820379,d_821247024,d_914594314,d_827220437,d_699625233, date,", select,"FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.participants_JP` Where d_821247024 = '197316935' \")",sep=" ")))

tb_bq <- eval(parse(text=paste("bq_project_query(project, query=\"SELECT token,Connect_ID,d_512820379,d_821247024,d_914594314,d_827220437,d_699625233, date,d_265193023, d_822499427, d_222161762,", select,"FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.participants_JP` Where d_821247024 = '197316935' \")",sep=" ")))
 

recr.bio <- bigrquery::bq_table_download(tb_bq,bigint="integer64",n_max = Inf, page_size = 1000)

##below are the commone variables in the recruitment table on Biospecimen to apply for the analysis. In case any new variables popping up, i would like #to use the one above directly from the resources (master DD and recruitment table schema to get the most updated version on this biospecimen data
# tb <- bq_project_query(project, query="SELECT d_512820379,d_512820379, d_821247024, d_914594314, d_822499427, d_222161762, Connect_ID, d_827220437, token,d_265193023, d_878865966, d_167958071, d_684635302, d_253883960, d_534669573, d_764863765, d_331584571_d_266600170_d_135591601,d_331584571_d_266600170_d_840048338,  d_331584571_d_266600170_d_343048998, d_173836415_d_266600170_d_139245758, d_173836415_d_266600170_d_185243482,
# d_173836415_d_266600170_d_198261154, d_173836415_d_266600170_d_210921343, d_173836415_d_266600170_d_224596428,
# d_173836415_d_266600170_d_316824786, d_173836415_d_266600170_d_341570479, d_173836415_d_266600170_d_398645039,
# d_173836415_d_266600170_d_448660695, d_173836415_d_266600170_d_452847912, d_173836415_d_266600170_d_453452655,
# d_173836415_d_266600170_d_530173840, d_173836415_d_266600170_d_534041351, d_173836415_d_266600170_d_541311218,
# d_173836415_d_266600170_d_561681068, d_173836415_d_266600170_d_592099155, d_173836415_d_266600170_d_611091485,
# d_173836415_d_266600170_d_646899796, d_173836415_d_266600170_d_693370086, d_173836415_d_266600170_d_718172863,
# d_173836415_d_266600170_d_728696253, d_173836415_d_266600170_d_740582332, d_173836415_d_266600170_d_769615780,
# d_173836415_d_266600170_d_786930107, d_173836415_d_266600170_d_822274939, d_173836415_d_266600170_d_847159717,
# d_173836415_d_266600170_d_860477844, d_173836415_d_266600170_d_915179629, d_173836415_d_266600170_d_939818935,
# d_173836415_d_266600170_d_951355211, d_173836415_d_266600170_d_982213346 FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.participants_JP` WHERE d_821247024 = '197316935'")
##to convert to numeric
cnames <- names(recr.bio)
recrver <- recr.bio
for (i in 1: length(cnames)){
  varname <- cnames[i]
  var<-pull(recrver,varname)
  recrver[,cnames[i]] <- ifelse(numbers_only(var), as.numeric(as.character(var)), var)
}
##to get the labels of each variable
recrver_CID <- as.data.frame(sapply((strsplit(colnames(recrver),"d_")),tail,1))
colnames(recrver_CID)[1] <- "CID"
recrver_CID$variable <- names(recr.bio)
recrver_ver1 <- base::merge(dd,recrver_CID,by="CID")
recrver1 <- expss::apply_labels(recrver,
                        d_512820379 = "Recruitment type",#RcrtSI_RecruitType_v1r0
                        d_512820379=c(	"Not active"=180583933,  
                                       "Active"= 486306141, 
                                       "Passive"=854703046),
                        d_821247024 = "Verification status", #RcrtV_Verification_v1r0
                        d_821247024 = c("Not yet verified" =875007964,
                                        "Verified"=197316935,  
                                        "Cannot be verified"=219863910, 
                                        "Duplicate"=922622075 , 
                                        "Outreach timed out"= 160161595),
                        d_827220437 = "Site",#RcrtES_Site_v1r0
                        d_827220437 = c("HealthPartners"= 531629870, "Henry Ford Health System"=548392715,"Marshfield Clinic Health System" = 303349821,"Sanford Health" = 657167265, "University of Chicago Medicine" = 809703864,"Kaiser Permanente Colorado" = 125001209,"Kaiser Permanente Georgia" = 327912200,"Kaiser Permanente Hawaii" = 300267574,"Kaiser Permanente Northwest" = 452412599,"National Cancer Institute" = 517700004,"National Cancer Institute" = 13,"Other" = 181769837),
                        d_914594314 = "Verification status time",   #RcrtV_VerificationTm_V1R0
                        d_878865966 = "Baseline blood sample collected", #BioFin_BaseBloodCol_v1r0
                        d_878865966 = c("Any blood collected"=353358909, "No blood collected"=104430631),
                        d_173836415_d_266600170_d_561681068 = "Date/time basline Research Blood Collected",#BL_BioFin_BBTime_v1r0
                        d_684635302 = "Baseline Mouthwash Collected",    #BioFin_BaseMWCol_v1r0
                        d_684635302 = c("Any mouthwash collected"=353358909,"No mouthwash collected"= 104430631  ),
                        d_173836415_d_266600170_d_448660695 = "Date/time Mouthwash Collected", #
                        d_167958071 = "Baseline Urine collected", 
                        d_167958071 = c( "Any urine collected"=353358909, "No urine collected"=104430631),
                        d_173836415_d_266600170_d_847159717 = "Baseline Date/time Urine collected",
                        d_331584571_d_266600170_d_135591601 = "Baseline Check-In Complete",#BL_BioChk_Complete_v1r0
                        d_331584571_d_266600170_d_135591601 =  c( "No"=104430631, "Yes"=353358909 ),
                        d_331584571_d_266600170_d_840048338 = "Date/Time Baseline Check-In Complete",
                        d_331584571_d_266600170_d_343048998 = "Time Baseline check out complete",#
                        
                        d_173836415_d_266600170_d_530173840 = "Blood Order Placed",#BioClin_BldOrderPlaced_v1r0  ## I ADDED
                        d_173836415_d_266600170_d_530173840 =c( "No"=104430631, "Yes"=353358909 ), ## I ADDED
                        
                        d_173836415_d_266600170_d_592099155 = "Blood Collection Setting",#BL_BioSpm_BloodSetting_v1r0  
                        d_173836415_d_266600170_d_592099155 =c("Research"=534621077, "Clinical"= 664882224,"Home" =103209024),
                        d_173836415_d_266600170_d_718172863 = "Urine Collection Setting",#BL_BioSpm_UrineSetting_v1r0
                        d_173836415_d_266600170_d_718172863 =c("Research"=534621077, "Clinical"= 664882224,"Home" =103209024),
                        d_173836415_d_266600170_d_915179629 = "Mouthwash Collection Setting",#BL_BioSpm_MWSetting_v1r0
                        d_173836415_d_266600170_d_915179629 =c("Research"=534621077, "Clinical"= 664882224,"Home" =103209024),
                        
                        d_265193023 = "Blood/urine/mouthwash combined research survey-Complete",   
                        d_265193023 = c(	"Not Started" =	972455046, "Started"= 615768760,"Submitted"= 231311385),#SrvBLM_ResSrvCompl_v1r0
                        d_822499427 = "Placeholder (Autogenerated) - Date/time Status of Start of blood/urine/mouthwash research survey",#SrvBLM_TmStart_v1r0
                        d_222161762  = "Placeholder (Autogenerated)- Date/Time blood/urine/mouthwash research survey completed" #   SrvBLM_TmComplete_v1r0
)




###to convert to categorical variables
recrver1$RcrtSI_RecruitType_v1r0 <- factor(recrver1$d_512820379, exclude=NULL)
recrver1$RcrtV_Verification_v1r0 <- factor(recrver1$d_821247024, exclude=NULL)
recrver1$BioFin_BaseMWCol_v1r0  <-factor(recrver1$d_684635302,exclude=NULL)
recrver1$BioFin_BaseBloodCol_v1r0 <- factor(recrver1$d_878865966,exclude=NULL)
recrver1$BioFin_BaseUrineCol_v1r0 <- factor(recrver1$d_167958071,exclude=NULL)

recrver1$BioClin_BldOrderPlaced_v1r0 <- factor(recrver1$d_173836415_d_266600170_d_530173840,exclude=NULL) ## I ADDED

recrver1$SrvBLM_ResSrvCompl_v1r0 <-factor(recrver1$d_265193023,exclude=NULL)
recrver1$BL_BioSpm_MWSetting_v1r0 <- factor(recrver1$d_173836415_d_266600170_d_915179629,levels=c("Clinical","Research","Home"))  
recrver1$BL_BioSpm_UrineSetting_v1r0 <- factor(recrver1$d_173836415_d_266600170_d_718172863, levels=c("Clinical","Research","Home"))  
recrver1$BL_BioSpm_BloodSetting_v1r0 <- factor(recrver1$d_173836415_d_266600170_d_592099155,levels=c("Clinical","Research","Home"))  
recrver1$BL_BioChk_Complete_v1r0 <- factor(recrver1$d_331584571_d_266600170_d_135591601,exclude=NULL)
recrver1$Site <-factor(recrver1$d_827220437,levels=c("HealthPartners", "Henry Ford Health System","Marshfield Clinic Health System",
                             "Sanford Health", "University of Chicago Medicine","Kaiser Permanente Colorado",
                             "Kaiser Permanente Georgia","Kaiser Permanente Hawaii","Kaiser Permanente Northwest",
                             "National Cancer Institute","Other"))
recrver1<- recrver1 %>% mutate(BldCollection = ifelse(recrver1$BioFin_BaseBloodCol_v1r0 == 353358909, "YES", "No"))

##to update the censoring time based on Kelsey's request to be consistent with the weekly log: from Monday to Sunday
veristart.date = as.Date(min(as.POSIXct(recr.bio$d_914594314),na.rm=TRUE))
veristart.date + days(5)
#[1] "2021-08-01"
recrver1$verified.week <- ceiling(as.numeric(difftime(as.Date(ymd_hms(recrver1$d_914594314)),as.Date(veristart.date-days(2)),units="days"))/7)
recrver1$verified.Sunday.date <- veristart.date + days(5)+ dweeks(recrver1$verified.week-1)



##to check the duplicate collection by verified participants Connect_ID
biospe[duplicated(biospe$Connect_ID),c("Connect_ID","d_820476880","d_410912345","d_387108065")]
biospe[duplicated(biospe$Connect_ID),"Connect_ID"]
biospe$Connect_ID[duplicated(biospe$Connect_ID)]
dupid <- biospe$Connect_ID[duplicated(biospe$Connect_ID)]
#biospe[which(biospe$Connect_ID %in% dupid),c("Connect_ID","d_820476880","d_410912345","d_387108065","d_143615646_d_593843561","d_973670172_d_593843561")]
##the biospecimen concepts for the biospecimen variablesbles
biospe_var <- as.data.frame((colnames(biospe)))
colnames(biospe_var)[1] <- "variable"
biospe_var$cid1 <- sapply(strsplit(colnames(biospe),"_"), "[", 2)
biospe_var$cid2 <- sapply(strsplit(colnames(biospe),"_"), "[", 4)
biospe_var$cid3 <- sapply(strsplit(colnames(biospe),"_"), "[", 6)
biospe_var$cid_tail <- sapply(strsplit(colnames(biospe),"_"), tail,1)

CID <- unique(c(biospe_var$cid1,biospe_var$cid2,biospe_var$cid3)) #this line is missing from your code in github.
#biospe_CID <- dd[which(dd$CID %in% CID),]
biospe_CID <- y[which(y$conceptId.3 %in% CID),]
biospe_dd<- base::merge(biospe_var,biospe_CID,by.x="cid_tail",by.y="conceptId.3", all.x=TRUE)
biospe_dd <- biospe_dd%>% arrange(variable,conceptId.1) %>% filter(!duplicated(variable))
#tubes <- dd[grepl(" Tube ",dd$`Variable Label`),] #updated 12/11/2023
tubes <- unique(y[grepl(" Tube ",y$`Secondary.Source`),c("conceptId.1","Secondary.Source")])


urine <- dd[grepl("Urine",dd$`Variable Label`),]
mouthwash <- dd[grepl("Mouthwash",dd$`Variable Label`),]



```




\FloatBarrier




```{r Tables1_2, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}
# \newpage
# \FloatBarrier
# # Tables

## Tables 1-4

#### FOR TABLES 1-4 I CHANGED NO SAMPLES COLLECTED TO BE NO COLLECTED SAMPLES AND ALSO THAT THE PARTICIPANTS DID HAVE A COLLECTION APPOINTMENT, SO THAT THOSE WHO HAVEN'T EVEN SCHEDULEN AN APPT YET ARE NOT COUNTED IN THE NO SAMPLES COLLECTED COLUMN

#sapply((strsplit(colnames(recrver),"d_")),tail,1)
###table1 Percent (and number) of verified participants with baseline biospecimen collections by site
##for any biospecimen collections
recrver1 <- recrver1 %>% mutate(BiospeCollection = ifelse((recrver1$d_684635302 == 353358909 | recrver1$d_878865966 == 353358909| recrver1$d_167958071 == 353358909), "Any biospecimen Collections","No biospecimen collections"))











bio.appoint <- biospe %>% arrange(Connect_ID, d_410912345) %>% group_by(Connect_ID) %>% summarise(d_410912345=mean(d_410912345,na.rm=TRUE)) #to remove the multiple collections by Connect_ID
 
biocol.tb <- base::merge(recrver1[,c("Connect_ID","Site","BiospeCollection","d_878865966","d_684635302","d_167958071")],bio.appoint,by.x="Connect_ID",by.y="Connect_ID",all.x=TRUE )
 
table1 <- biocol.tb %>% filter(recrver1$d_821247024==197316935) %>%
  mutate(#appointment = ifelse((d_410912345!= 353358909 | is.na(d_410912345)), 104430631, 353358909),
         biocol.appoint = case_when(BiospeCollection == "Any biospecimen Collections" & d_410912345== 353358909 ~ "Baseline Collection",
                                    #BiospeCollection == "No biospecimen collections" & (d_410912345!= 353358909 | is.na(d_410912345)) ~ "No Baseline Collection"
                                    TRUE ~ "No Baseline Collection")) %>%  
  mutate(biocol.appoint = factor(biocol.appoint, levels=c("Baseline Collection","No Baseline Collection"))) %>% dplyr::select(Site, biocol.appoint )  %>% 
  tbl_cross(
    row = Site,
    col = biocol.appoint,
    digits=c(0,1),
    percent = "row",
    label=list(Site="Site",
                biocol.appoint = " "),
    missing="ifany",
    margin_text="Total") 
 
 










table2 <- biocol.tb %>% filter(d_410912345== 353358909) %>%
  mutate(#appointment = ifelse((d_410912345!= 353358909 | is.na(d_410912345)), 104430631, 353358909),
         biocol.appoint = case_when(d_878865966== 353358909  ~ "Any Baseline Blood Collected",
                                    TRUE ~ "No Baseline Blood Collected")) %>%  
  mutate(biocol.appoint = factor(biocol.appoint, levels=c("Any Baseline Blood Collected","No Baseline Blood Collected"))) %>% dplyr::select(Site, biocol.appoint )  %>% 
  tbl_cross(
    row = Site,
    col = biocol.appoint,
    digits=c(0,1),
    percent = "row",
    label=list(Site="Site",
               biocol.appoint = " "),
    missing="ifany",
    margin_text="Total") 
 
 
table2[["table_body"]]$stat_0 <- sapply(strsplit(table2[["table_body"]]$stat_0," "),"[",1)
 
table2 <- table2%>%
  #bold_labels() %>%
  #italicize_levels() %>% 
  modify_header(stat_0 = "Total") %>%
  modify_caption("Table 2: Baseline Blood Collection Status Among Baseline Collections by Site") %>%
  as_kable_extra(escape = FALSE, addtl_fmt = TRUE)



biospe.bld <- table2

```







```{r RemovedTable6, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}
# ###Table 6 Baseline biospecimen collection status among verified participants research collection
# levels(recrver1$BioFin_BaseBloodCol_v1r0)
# 
# biocol <- recrver1   %>%  group_by(BioFin_BaseBloodCol_v1r0,BioFin_BaseUrineCol_v1r0,BioFin_BaseMWCol_v1r0) %>% dplyr::tally()   #%>% filter(d_410912345==353358909)
# 
# biocol$BioFin_BaseBloodCol_v1r0= ifelse(biocol$BioFin_BaseBloodCol_v1r0=="Any blood collected", "Yes", "No")
# biocol$BioFin_BaseUrineCol_v1r0= ifelse(biocol$BioFin_BaseUrineCol_v1r0=="Any urine collected", "Yes", "No")
# biocol$BioFin_BaseMWCol_v1r0= ifelse(biocol$BioFin_BaseMWCol_v1r0=="Any mouthwash collected", "Yes", "No")
# 
# total <- nrow(recrver1)
# biocol$pct <- round(100*biocol$n/nrow(recrver1),digits=1)
# #biocol$cumcount <- cumsum(biocol$n)
# #biocol$cumpct <- round(100*cumsum(biocol$n)/nrow(recrver1),digits=1)
# 
# # biocol <- apply_labels(biocol, total,
# #                        pct="percentage of Total verified %")
# #                        #cumcount="cumulative counts of verified",
# #                        #cumpct="cumulative percentage")
# 
# db <- dim(biocol)[[1]]
# #biocol <- as_kable(biocol)
# func <- function(z) {ifelse(is.numeric(z), round(sum(z), digits=0),'')}
# sumrow <- as.data.frame(lapply(biocol, func))
# #kable(rbind(df, sumrow))
# biocol[,5]
# biocol[(db+1),] <- sumrow
# biocol[(db+1),1] <- "Total"
# biocol[(db+1),2] <- "-"
# biocol[(db+1),3] <- "-"
# 
# colnames(biocol) <- c("Any Blood Collected","Urine Collected","Mouthwash Collected","Number","Percent")
# 
# ###Table 6. by site
# biocol.site <- list()
# recrver1$Site <- droplevels(recrver1$Site)
# for(site in unique(recrver1$Site)){
#   
#   site.sub <- recrver1 %>% filter(Site==site) %>% 
#     group_by(BioFin_BaseBloodCol_v1r0,BioFin_BaseUrineCol_v1r0,BioFin_BaseMWCol_v1r0) %>% dplyr::tally() 
#   
#   site.sub$BioFin_BaseBloodCol_v1r0= ifelse(site.sub$BioFin_BaseBloodCol_v1r0=="Any blood collected", "Yes", "No")
#   site.sub$BioFin_BaseUrineCol_v1r0= ifelse(site.sub$BioFin_BaseUrineCol_v1r0=="Any urine collected", "Yes", "No")
#   site.sub$BioFin_BaseMWCol_v1r0= ifelse(site.sub$BioFin_BaseMWCol_v1r0=="Any mouthwash collected", "Yes", "No")
#   
#   total <- as.numeric(nrow(recrver1[which(recrver1$Site==site),]))
#   site.sub$pct <- round(100*site.sub$n/total,digits=1)
#   
# ds <- dim(site.sub)[[1]]
# func <- function(z) {ifelse(is.numeric(z), round(sum(z), digits=0),'')}
# sumrow <- as.data.frame(lapply(site.sub, func))
# #kable(rbind(df, sumrow))
# #site.sub[,5]
# site.sub[(ds+1),] <- sumrow
# site.sub[(ds+1),1] <- "Total"
# site.sub[(ds+1),2] <- "-"
# site.sub[(ds+1),3] <- "-"
# 
#   
#   #site.sub$cumcount <- cumsum(site.sub$n)
#   #site.sub$cumpct <- round(100*cumsum(site.sub$n)/total,digits=1)
#   biocol.site[[site]] <- site.sub
# 
# }

```



```{r Table5a5b, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}







# #FOR AD HOC UC REPORT ONLY
biospe<- expss::apply_labels(biospe,d_827220437 = "Site",#RcrtES_Site_v1r0
                     d_827220437 = c("HealthPartners"= 531629870, "Henry Ford Health System"=548392715,"Marshfield Clinic Health System" = 303349821,"Sanford Health" = 657167265, "University of Chicago Medicine" = 809703864, "Kaiser Permanente Colorado" = 125001209,"Kaiser Permanente Georgia" = 327912200,"Kaiser Permanente Hawaii" = 300267574,"Kaiser Permanente Northwest" = 452412599,"National Cancer Institute" = 517700004,"National Cancer Institute" = 13,"Other" = 181769837))

biospe$Site <- factor(biospe$d_827220437, levels= c("HealthPartners", "Henry Ford Health System","Marshfield Clinic Health System","Sanford Health", "University of Chicago Medicine","Kaiser Permanente Colorado","Kaiser Permanente Georgia","Kaiser Permanente Hawaii","Kaiser Permanente Northwest"))
# 
# 
# # biospe <- biospe %>%  filter(Site=="University of Chicago Medicine")
# # biospe$Site<- droplevels(biospe$Site)
# 
# 
# 
# biospeUC<- expss::apply_labels(biospe,d_951355211 = "Collection_Location",#RcrtES_Site_v1r0
#                      d_827220437 = c("UC-DCAM"= 777644826, "Ingalls Harvey"=548392715,"River East" = 303349821, "South Loop" = 657167265, "UCM Pop-Up" = 809703864))
# 
# biospeUC$Collection_Location <- factor(biospeUC$d_951355211, levels= c("UC-DCAM", "Ingalls Harvey","River East", "South Loop", "UCM Pop-Up"))
# 
# biospeUC$Collection_Location<- droplevels(biospeUC$Collection_Location)

biospe_UC <- biospe %>%  filter(Site=="University of Chicago Medicine")

biospeUC<-biospe_UC %>% mutate(Collection_Location = case_when(d_951355211==777644826 ~ "UC-DCAM",

                                                      d_951355211==145191545 ~ "Ingalls Harvey",
                                                      d_951355211==489380324 ~ "River East",
                                                      d_951355211==120264574 ~ "South Loop",
                                                      d_951355211==319518299 ~ "UCM Pop-Up",
                                                      d_951355211==940329442 ~ "Orland Park",
                                                      TRUE ~ "Null Collection Location"))

biospeUC <- biospeUC #%>%  filter(Collection_Location != "Error")

b6 <- biospeUC %>%  select(Connect_ID, Collection_Location, d_650516960, d_410912345)


spec_collt <- recrver1 %>%  select(Connect_ID, BioFin_BaseBloodCol_v1r0,BioFin_BaseUrineCol_v1r0,BioFin_BaseMWCol_v1r0)

rb_table6 <- left_join(spec_collt, b6, by="Connect_ID")

#rb_table6$Site <- droplevels(rb_table6$Site)
  
site.sub1 <- rb_table6 %>% filter(d_410912345==353358909) 
  
  
site.sub <- site.sub1 %>%  mutate(Setting = case_when(d_650516960==534621077 ~ "Research Collections",
                                                        d_650516960==664882224 ~ "Clinical Collections",
                                                        TRUE ~ "No Collections"),
                                'Specimens Collected'= case_when((BioFin_BaseBloodCol_v1r0=="Any blood collected" & BioFin_BaseUrineCol_v1r0=="Any urine collected" & BioFin_BaseMWCol_v1r0=="Any mouthwash collected") ~ 'Blood, Urine, Mouthwash (All)',
                                                                 (BioFin_BaseBloodCol_v1r0=="Any blood collected" & BioFin_BaseUrineCol_v1r0=="Any urine collected" & BioFin_BaseMWCol_v1r0!="Any mouthwash collected") ~ 'Blood & Urine Only',
                                                                 (BioFin_BaseBloodCol_v1r0=="Any blood collected" & BioFin_BaseUrineCol_v1r0!="Any urine collected" & BioFin_BaseMWCol_v1r0=="Any mouthwash collected") ~ 'Blood & Mouthwash Only',
                                                                 (BioFin_BaseBloodCol_v1r0!="Any blood collected" & BioFin_BaseUrineCol_v1r0=="Any urine collected" & BioFin_BaseMWCol_v1r0=="Any mouthwash collected") ~ 'Urine & Mouthwash Only',
                                                                 (BioFin_BaseBloodCol_v1r0=="Any blood collected" & BioFin_BaseUrineCol_v1r0!="Any urine collected" & BioFin_BaseMWCol_v1r0!="Any mouthwash collected") ~ 'Blood Only',
                                                                 (BioFin_BaseBloodCol_v1r0!="Any blood collected" & BioFin_BaseUrineCol_v1r0=="Any urine collected" & BioFin_BaseMWCol_v1r0!="Any mouthwash collected") ~ 'Urine Only',
                                                                 (BioFin_BaseBloodCol_v1r0!="Any blood collected" & BioFin_BaseUrineCol_v1r0!="Any urine collected" & BioFin_BaseMWCol_v1r0=="Any mouthwash collected") ~ 'Mouthwash Only',
                                                                 (BioFin_BaseBloodCol_v1r0!="Any blood collected" & BioFin_BaseUrineCol_v1r0!="Any urine collected" & BioFin_BaseMWCol_v1r0!="Any mouthwash collected") ~ 'No Specimens Collected'))
site.sub$'Specimens Collected' <- factor(site.sub$'Specimens Collected',levels=c('Blood, Urine, Mouthwash (All)', 'Blood & Urine Only','Blood & Mouthwash Only','Urine & Mouthwash Only','Blood Only','Urine Only','Mouthwash Only','No Specimens Collected'))

table4_redone__R <- site.sub %>% filter(Setting=="Research Collections") 
#table4_redone__R$Collection_Location <- droplevels(table4_redone__R$Collection_Location)
table4_redone__R$'Specimens Collected' <- droplevels(table4_redone__R$'Specimens Collected')
coll_completenessR <- table4_redone__R %>% dplyr::select('Specimens Collected', Collection_Location )  %>% 
  tbl_cross(
    row =  Collection_Location,
    col = 'Specimens Collected',
    digits=c(0,1),
    percent = "row",
    label=list(Collection_Location=" "),
    missing="ifany",
    margin_text="Total")

coll_completenessR <- coll_completenessR %>%
  #bold_labels() %>%
  #italicize_levels() %>% 
  modify_header(stat_0 = "Total") %>%
  modify_caption("Table 1. Baseline Research Collection Completeness by Collection Location ") %>%
  as_kable_extra(escape = FALSE, addtl_fmt = TRUE)

```








```{r Table7s, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}

##Fig 1(table6)
recrver1 <- recrver1 %>% mutate(BiospmCols_v1r0 = 
                                  case_when((recrver1$d_684635302 == 353358909 & recrver1$d_878865966 == 353358909 & recrver1$d_167958071 == 353358909) ~ "All blood, urine and mouthwash",
                                            (recrver1$d_684635302 == 353358909 & recrver1$d_878865966 == 353358909 & recrver1$d_167958071 == 104430631) ~ "Mouthwash and blood, no urine",
                                            (recrver1$d_684635302 == 353358909 & recrver1$d_878865966 == 104430631 & recrver1$d_167958071 == 104430631) ~ "Only mouthwash,no blood or urine",
                                            (recrver1$d_684635302 == 104430631 & recrver1$d_878865966 == 353358909 & recrver1$d_167958071 == 353358909) ~ "Blood and urine, no mouthwash",
                                            (recrver1$d_684635302 == 104430631 & recrver1$d_878865966 == 104430631 & recrver1$d_167958071 == 353358909) ~ "Only urine, no blood or mouthwash",
                                            (recrver1$d_684635302 == 353358909 & recrver1$d_878865966 == 104430631 & recrver1$d_167958071 == 353358909) ~ "Mouthwash and urine, no blood",
                                            (recrver1$d_684635302 == 104430631 & recrver1$d_878865966 == 353358909 & recrver1$d_167958071 == 104430631) ~ "Only blood, no urine or mouthwash",
                                            ((recrver1$d_684635302 == 104430631 | is.na(recrver1$d_684635302)) & (recrver1$d_878865966 == 104430631 | is.na(recrver1$d_878865966)) & (is.na(recrver1$d_167958071) |recrver1$d_167958071 == 104430631)) ~ "No any biospecimen collections"))

table(as.character(recrver1$d_684635302))








### NOT SURE WHAT THIS CODE SECTION GOES TO 
table_colspm <- recrver1[which(recrver1$d_684635302 == 353358909 | recrver1$d_878865966 == 353358909 | recrver1$d_167958071 == 353358909),] %>%
        group_by(BiospmCols_v1r0) %>% dplyr::summarise(count=n()) 
table_colspm$count_pct <- paste0(table_colspm$count," (", round(100*table_colspm$count/sum(table_colspm$count),digits=1),"%)")
table_colspm <- table_colspm[order(-table_colspm$count),]
table_colspm$midpoint = cumsum(table_colspm$count) - (table_colspm$count / 2)
table_colspm$midpoint <- ifelse(table_colspm$count>7, table_colspm$count, cumsum(table_colspm$count) - (table_colspm$count / 2))
table_colspm$midpoint
ggplot(table_colspm, aes(x = "", y = count, fill = BiospmCols_v1r0)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar(theta = "y", start = 0) +
  scale_fill_manual(values = c("light blue", "Red", "Green", "Orange", "Pink", "Purple","Yellow")) +
  scale_colour_brewer(palette = "Set1") +
  labs(x = "", y = "", title = "Percent (and number) of Biospecimen Collection Completion among baseline collections",
       fill = "BiospmCols_v1r0") + 
  geom_text(aes(x=1.6, label=count_pct),
            position =  position_stack(vjust=0.6), size=3) +
  geom_text(aes(x = 1.3, y = midpoint , label = count_pct), color="black",
            fontface = "bold") +
  theme(plot.title = element_text(hjust = 0.5), 
        legend.title = element_text(hjust = 0.5, face="bold", size = 10))


#label outside
ggplot(table_colspm, aes(x = "", y = count, fill = BiospmCols_v1r0)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar(theta = "y", start = 0) +
  scale_fill_manual(values = c("light blue", "Red", "Green", "Orange", "Pink", "Purple","Yellow")) +
  #scale_colour_brewer(palette = "Set1") +
  labs(x = "", y = "", title = "Percent (and number) of Biospecimen Collection Completion among baseline collections",
       fill = "BiospmCols_v1r0") + 
  geom_text(aes(x=1.6, label=count_pct),
            position =  position_stack(vjust=0.6), size=3, color="black",fontface = "bold") +
  theme(panel.background = element_blank(),
        plot.title = element_text(hjust = 0.0, face="bold"), 
        axis.ticks = element_blank(),axis.text = element_blank(),
        legend.title = element_text(hjust = 0.5, face="bold", size = 10))


###for the biospecimen data:collections, deviation, and nocollections# ###Table 14. Number of blood, urine, and mouthwash collected by collection setting
pct_tb <- function(x,y){
  table1 <- CrossTable(x,y, prop.t=FALSE, prop.r=FALSE, prop.c=TRUE,chisq=FALSE)
  pct <- as.data.frame(cbind(table1$prop.row,table1$t))
  if(ncol(pct)==2){
    total <- as.numeric(sum(pct[,2]))
    pct[nrow(pct)+1,c(1:2)] <- c(1,total)
    rownames(pct)[nrow(pct)] <- "Total"
    colnames(pct)[1] <- paste0("pct_",colnames(pct)[1])
    colnames(pct)[2] <- paste0("n_",colnames(pct)[2])
    
  }
  else  if(ncol(pct)>2 ){
    total <- as.numeric(sum(pct[,3] + pct[,4]))
    pct[nrow(pct)+1,c(1:4)] <- c(sum(pct[,3])/total,sum(pct[,4])/total,sum(pct[,3]),sum(pct[,4]))
    rownames(pct)[nrow(pct)] <- "Total"
    colnames(pct)[c(1:2)] <- paste0("pct_",colnames(pct[c(1:2)]))
    colnames(pct)[c(3:4)] <- paste0("n_",colnames(pct)[c(3:4)])
    
    pct[,5] <- paste0(format(pct[,3],big.mark=","), " (",round(100*pct[,1],1), "%)")
    pct[,6] <- paste0(format(pct[,4],big.mark=","), " (",round(100*pct[,2],1), "%)") 
    colnames(pct)[5] <- paste0("n_",colnames(pct)[1])
    colnames(pct)[6] <- paste0("n_",colnames(pct)[2])
  }
  return(pct)
}



###Tables on the biospecimen samples
##Table6_bysite. the research blood collection completions
##for blood collection based on the biospecimen data individually
biospe<- expss::apply_labels(biospe,d_827220437 = "Site",#RcrtES_Site_v1r0
                     d_827220437 = c("HealthPartners"= 531629870, "Henry Ford Health System"=548392715,"Marshfield Clinic Health System" = 303349821,"Sanford Health" = 657167265, "University of Chicago Medicine" = 809703864, "Kaiser Permanente Colorado" = 125001209,"Kaiser Permanente Georgia" = 327912200,"Kaiser Permanente Hawaii" = 300267574,"Kaiser Permanente Northwest" = 452412599,"National Cancer Institute" = 517700004,"National Cancer Institute" = 13,"Other" = 181769837))

biospe$Site <- factor(biospe$d_827220437, levels= c("HealthPartners", "Henry Ford Health System","Marshfield Clinic Health System","Sanford Health", "University of Chicago Medicine","Kaiser Permanente Colorado","Kaiser Permanente Georgia","Kaiser Permanente Hawaii","Kaiser Permanente Northwest")) 

#125001209 300267574 303349821 327912200 452412599 531629870 548392715 657167265 809703864 
#        2         2       329         1         4       417       169       200       314 
                      
#125001209 300267574 303349821 327912200 452412599 531629870 548392715 657167265 809703864 
#        2         2       329         1         4       417       169       200       314 
biospe <- biospe %>% arrange(Site)
tubes <- dd[grepl(" Tube ",dd$`Variable Label`),]
tubes[grepl("00", tubes$`Variable Name`),]
###         CID         Variable Label    Variable Name
# 2: 299553921 Serum Separator Tube 1 BioCol_0001_v1r0
# 9: 703954371 Serum Separator Tube 2 BioCol_0002_v1r0
# 3: 376960806 Serum Separator Tube 3 BioCol_0011_v1r0
# 1: 232343615 Serum Separator Tube 4 BioCol_0012_v1r0
# 5: 589588440 Serum Separator Tube 5 BioCol_0021_v1r0
# 4: 454453939            EDTA Tube 1 BioCol_0004_v1r0
# 7: 677469051            EDTA Tube 2 BioCol_0014_v1r0
# 8: 683613884            EDTA Tube 3 BioCol_0024_v1r0
# 10: 838567176         Heparin Tube 1 BioCol_0003_v1r0
# 11: 958646668         Heparin Tube 2 BioCol_0013_v1r0
# 6: 652357376             ACD Tube 1 BioCol_0005_v1r0
bld.ls <- c("d_299553921","d_703954371","d_454453939","d_838567176","d_652357376","d_376960806","d_232343615","d_589588440","d_677469051", "d_683613884","d_958646668") #blood tube types CIDs: the first 5 tubes are research, add the rest are clinical
#bld.ls <- c("d_299553921","d_703954371","d_454453939","d_838567176","d_652357376") #blood tube types CIDs research collections
##research collection tubes
 ##biospeciment tube type CIDs
tubeid <- grep("d_825582494", names(biospe), value=TRUE) #tube ID
deviation <- grep("d_678857215",names(biospe),value=TRUE) 
colid <- grep("d_593843561", names(biospe), value=TRUE) #collected yes/no
discard <- grep("d_762124027",names(biospe),value=TRUE) #discard yes/no
biodiscard <- biospe[,(which(names(biospe) %in% discard))]
#eval(parse(text=paste("varlong <-grep(",\"d_593843561\",",names(biospe),value=TRUE)",sep="")))
###Table 6. Percent (and number) of Blood Completeness among baseline collections
###reshape the data: binary variables for tube collections: collected(y/n),deviation(y/n), tubeID, discarded (y/n), notcollection reasons:5,
###notcollection Notes (338286049), deviation notes (536710547)
biospe$blddev <-0 #blood deviations
biospe$bldcol <- 0 #blood collections
biospe$blddid <- 0 #discarded
for(i in 1:length(bld.ls)){
  
  bldcol <- ifelse(biospe[,paste(bld.ls[i],"d_593843561",sep="_")] == 104430631 | is.na(biospe[,paste(bld.ls[i],"d_593843561",sep="_")]),0,1)  ##for tube collected
  
  blddev <- ifelse(biospe[,paste(bld.ls[i],"d_678857215",sep="_")]==104430631 | is.na(biospe[,paste(bld.ls[i],"d_678857215",sep="_")]),0,1) #for tube deviations yes/no
  
  blddid <- ifelse(biospe[,paste(bld.ls[i],"d_762124027",sep="_")]==104430631 | is.na(biospe[,paste(bld.ls[i],"d_762124027",sep="_")]),0,1)
  
  biospe$blddev <- biospe$blddev+blddev
  biospe$bldcol <- bldcol + biospe$bldcol ###to check collection
  biospe$blddid <- biospe$blddid+blddid  
  # k the completion of the blood collection of 5 types
  
}
table(biospe$d_650516960,biospe$bldcol)
biospe <- biospe %>% mutate(bloodcomplete = ifelse((d_650516960==534621077 & bldcol == 5) | (d_650516960==664882224 & bldcol == 11), "Blood.Completion" ,#blood collection completion
                                          ifelse( (d_650516960==534621077 & (bldcol<5 & bldcol>0)) | (d_650516960==664882224 & (bldcol <  11 & bldcol < 0)),"Blood.Incompleted","NoBlood")),
                            Urine_col = ifelse(d_973670172_d_593843561==353358909, 1, ifelse(d_973670172_d_593843561==104430631,0,0)),
                            MW_col = ifelse(d_143615646_d_593843561==353358909,1,ifelse(d_143615646_d_593843561==104430631,0,0)),
                            biocol_Setting = case_when(d_650516960==534621077  ~"Research",
                                                        d_650516960==664882224 ~ "Clinical",
                                                         d_650516960 ==103209024 ~ "Home")) 
biospe$Biospe_col <- biospe$bldcol + biospe$Urine_col + biospe$MW_col    
biospe$BaseBLDCol <-ifelse(biospe$bldcol>0,1,ifelse(is.na(biospe$bldcol),NA,0)) #blood collection Yes/No
biospe[duplicated(biospe$Connect_ID),]$Connect_ID







### Table 5
tube_col <- biospe  %>% group_by(as.character(Connect_ID),Site,d_650516960) %>% 
  dplyr::summarise(bldcol_max = max(bldcol),
                   Urine_col_max= max(Urine_col),
                   MW_col_max=max(MW_col),
                   d_973670172_d_593843561_max=max(d_973670172_d_593843561),
                   d_143615646_d_593843561_max = max(d_143615646_d_593843561),
                   d_410912345_max=max(d_410912345),
                   collection.tm =max(as.POSIXct(ymd_hms(d_556788178))),
                   schedulecol.tm =min(as.POSIXct(ymd_hms(d_678166505))))



table(tube_col$d_650516960)
#534621077 664882224 
#     1421        10 
tube_col$Connect_ID <- as.numeric(tube_col$`as.character(Connect_ID)`)
#tube_col[duplicated(tube_col$Connect_ID),]$Connect_ID #only 1 2310991421
tube_research <- tube_col %>% filter(d_650516960==534621077) %>%
  mutate(bld.complt = ifelse(bldcol_max==5,"BloodCompletion",ifelse(bldcol_max==0, "NoBlood","BloodIncomplet")))
#tube_research$Site <- droplevels(tube_research$Site)
table.bldcol <- ctable(tube_research$Site,tube_research$bld.complt)
bldcol_research <- as.data.frame(cbind(table.bldcol$cross_table,table.bldcol$proportions))
bldcol_research$Site <-trimws(rownames(bldcol_research))
                             
bldcol_research$n_pct_BloodCompletion <- ifelse(!grepl("Total",rownames(bldcol_research)),  paste(format(bldcol_research[,1],big.mark=","),"(", round(100*bldcol_research[,5],1),"%)",sep=" "), format(bldcol_research[,1],big.mark="," ))
bldcol_research$n_pct_BloodInompletion = ifelse(!grepl("Total",rownames(bldcol_research)),  paste(format(bldcol_research[,2],big.mark=","),"(", round(100*bldcol_research[,6],1),"%)",sep=" "), format(bldcol_research[,2],big.mark="," ))
bldcol_research$n_pct_NoBlood = ifelse(!grepl("Total",rownames(bldcol_research)),  paste(format(bldcol_research[,3],big.mark=","),"(", round(100*bldcol_research[,7],1),"%)",sep=" "), format(bldcol_research[,3],big.mark="," ))
         
bldcol_research1 <- bldcol_research[c(1:5,10),c(9:12,4)] #c(9:12,4)





### Table 7.1- specifically for U-Chicago 
biospe= biospe  %>% filter(Site=="University of Chicago Medicine") %>% mutate(UC_Sites= case_when(d_951355211==777644826 ~ "UC-DCAM",
                                                      d_951355211==145191545 ~ "Ingalls Harvey",
                                                      d_951355211==489380324 ~ "River East",
                                                      d_951355211==120264574 ~ "South Loop",
                                                      d_951355211==319518299 ~ "UCM Pop-Up",
                                                      d_951355211==940329442 ~ "Orland Park",
                                                      TRUE~"Null Collection Location"))


tube_col_UC <- biospe  %>% group_by(as.character(Connect_ID),UC_Sites,d_650516960) %>% 
  #filter(!is.na(UC_Sites)) %>% 
  dplyr::summarise(bldcol_max = max(bldcol,na.rm=TRUE),
                   Urine_col_max= max(Urine_col,na.rm=TRUE),
                   MW_col_max=max(MW_col,na.rm=TRUE),
                   d_973670172_d_593843561_max=max(d_973670172_d_593843561,na.rm=TRUE),
                   d_143615646_d_593843561_max = max(d_143615646_d_593843561,na.rm=TRUE),
                   d_410912345_max=max(d_410912345,na.rm=TRUE),
                   collection.tm =max(as.POSIXct(ymd_hms(d_556788178)),na.rm=TRUE),
                   schedulecol.tm =min(as.POSIXct(ymd_hms(d_678166505)),na.rm=TRUE))
table(tube_col_UC$d_650516960)
#534621077 664882224 
#     1421        10 
tube_col_UC$Connect_ID <- as.numeric(tube_col_UC$`as.character(Connect_ID)`)
#tube_col_UC[duplicated(tube_col_UC$Connect_ID),]$Connect_ID #only 1 2310991421
tube_research_UC <- tube_col_UC %>% filter(d_650516960==534621077) %>%
  mutate(bld.complt = ifelse(bldcol_max==5,"BloodCompletion",ifelse(bldcol_max==0, "NoBlood","BloodIncomplet")))
#tube_research_UC$UC_Sites <- droplevels(tube_research_UC$UC_Sites)
table.bldcol_UC <- ctable(tube_research_UC$UC_Sites,tube_research_UC$bld.complt)
bldcol_research_UC <- as.data.frame(cbind(table.bldcol_UC$cross_table,table.bldcol_UC$proportions))
bldcol_research_UC$UC_Sites <-trimws(rownames(bldcol_research_UC))
                             
bldcol_research_UC$n_pct_BloodCompletion <- ifelse(!grepl("Total",rownames(bldcol_research_UC)),  paste(format(bldcol_research_UC[,1],big.mark=","),"(", round(100*bldcol_research_UC[,5],1),"%)",sep=" "), format(bldcol_research_UC[,1],big.mark="," ))
bldcol_research_UC$n_pct_BloodInompletion = ifelse(!grepl("Total",rownames(bldcol_research_UC)),  paste(format(bldcol_research_UC[,2],big.mark=","),"(", round(100*bldcol_research_UC[,6],1),"%)",sep=" "), format(bldcol_research_UC[,2],big.mark="," ))
bldcol_research_UC$n_pct_NoBlood = ifelse(!grepl("Total",rownames(bldcol_research_UC)),  paste(format(bldcol_research_UC[,3],big.mark=","),"(", round(100*bldcol_research_UC[,7],1),"%)",sep=" "), format(bldcol_research_UC[,3],big.mark="," ))
         
bldcol_research_UC1 <- bldcol_research_UC[,c(9:12,4)]


```



```{r Table9, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}
### Table 8- renumbered
pct_n <- function(x,y){ paste0(x,"( ", round(100*y,2), " %)")}
n_pct_table <- function(x,y){
  #x<-clinicnotes.notcol$Site
  #y<-clinicnotes.notcol$notcol.notes
  ctable<- CrossTable(x,y)
count <- as.data.frame.matrix(ctable$t)
perc <- as.data.frame.matrix(ctable$prop.col)
n<- as.numeric(length(levels(x)))
m <- as.numeric(length(levels(y)))
tb_combo <- array(pct_n(ctable$t,ctable$prop.col),dim=c(n,m))
  tb_combo <- as.data.frame(tb_combo)
  colnames(tb_combo) <- colnames(count)

  total <- sum(count)
  count$Total <- apply(count,1,sum)
  tb_combo$Total <- paste0(count$Total, "( ", round(100*(count$Total)/total,2), " %)")

  tb_combo$Site <- rownames(count)
  tb_combo[(n+1),c(1:(m+1))] <- as.character(apply(count,2,sum))
  tb_combo$Site[is.na(tb_combo$Site)] <- replace_na("Total")
  return(tb_combo)
}

```





```{r Table11, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}


#Table 13 
#Participants who checked in for a baseline biospecimen visit but did not give any samples
dd[grepl("BioChk",dd$`Variable Name`),]
recr_bio <- base::merge(recrver1,tube_col,by="Connect_ID")
bio_checkin_resh <- recr_bio  %>% filter(!is.na(d_331584571_d_266600170_d_840048338) & d_650516960==534621077) %>% select(BiospeCollection ) %>% tbl_summary()
table(bio_checkin_resh$BiospeCollection)
#Table 12 Number (and percent) of tubes with any deviation by site
#dd[grepl("BioCol_00",dd$`Variable Name`),] %>% arrange(`Variable Label`)
#          CID                          Variable Label    Variable Name
#  1: 143615646                               Mouthwash BioCol_0007_v1r0
#  2: 223999569            Biohazard Bag (mouthwash) ID BioCol_0009_v1r0
#  3: 232343615                  Serum Separator Tube 4 BioCol_0012_v1r0
#  4: 299553921                  Serum Separator Tube 1 BioCol_0001_v1r0
#  5: 376960806                  Serum Separator Tube 3 BioCol_0011_v1r0
#  6: 454453939                             EDTA Tube 1 BioCol_0004_v1r0
#  7: 589588440                  Serum Separator Tube 5 BioCol_0021_v1r0
#  8: 652357376                              ACD Tube 1 BioCol_0005_v1r0
#  9: 677469051                             EDTA Tube 2 BioCol_0014_v1r0
# 10: 683613884                             EDTA Tube 3 BioCol_0024_v1r0
# 11: 703954371                  Serum Separator Tube 2 BioCol_0002_v1r0
# 12: 787237543 Biohazard Bag (Blood or Blood/Urine) ID BioCol_0008_v1r0
# 13: 838567176                          Heparin Tube 1 BioCol_0003_v1r0
# 14: 958646668                          Heparin Tube 2 BioCol_0013_v1r0
# 15: 973670172                                   Urine BioCol_0006_v1r0
tubes <- dd[which(grepl("BioCol_00",as.character(dd$`Variable Name`)) & !grepl("Biohazard Bag", dd$`Variable Label`) & !grepl("Biohaz Bag", dd$`Variable Label`)),] #Biohazard changed to Biohaz, noticed 2/21/24
tubes <- tubes[order(tubes$"Variable Name"),]
tube.ls <- paste0("d_", trimws(paste(tubes[which(grepl("00", tubes$`Variable Name`)),]$CID,collapes="")))
# [1] "d_299553921" "d_703954371" "d_838567176" "d_454453939" "d_652357376" "d_973670172" "d_143615646"
# [8] "d_376960806" "d_232343615" "d_958646668" "d_677469051" "d_589588440" "d_683613884"
biospe$tubedev <-0 #biospecimen deviations
biospe$tubecol <- 0 #tube collections
biospe$tubedid <- 0 #tube discarded
for(i in 1:length(tube.ls)){
  
  tubecol <- ifelse(biospe[,paste(tube.ls[i],"d_593843561",sep="_")] == 104430631 | is.na(biospe[,paste(tube.ls[i],"d_593843561",sep="_")]),0,1)  ##for tube collected
  
  tubedev <- ifelse(biospe[,paste(tube.ls[i],"d_678857215",sep="_")]==104430631 | is.na(biospe[,paste(tube.ls[i],"d_678857215",sep="_")]),0,1) #for tube deviations yes/no
  
  tubedid <- ifelse(biospe[,paste(tube.ls[i],"d_762124027",sep="_")]==104430631 | is.na(biospe[,paste(tube.ls[i],"d_762124027",sep="_")]),0,1)
  
  biospe$tubedev <- biospe$tubedev+tubedev
  biospe$tubecol <- tubecol + biospe$tubecol ###to check collection
  biospe$tubedid <- biospe$tubedid+tubedid  
  # k the completion of the 13 tube collections
}
table(biospe$tubecol)
table(biospe$tubedev)
biospe$d_827220437 <- as.numeric(biospe$d_827220437)
biospe <- apply_labels(biospe,d_827220437 = "Site",#RcrtES_Site_v1r0
                       d_827220437 = c("HealthPartners"= 531629870, "Henry Ford Health System"=548392715, "Kaiser Permanente Colorado" = 125001209,
                                      "Kaiser Permanente Georgia" = 327912200,"Kaiser Permanente Hawaii" = 300267574,"Kaiser Permanente Northwest" = 452412599,
                                      "Marshfield Clinic Health System" = 303349821,"Sanford Health" = 657167265, "University of Chicago Medicine" = 809703864,
                                      "National Cancer Institute" = 517700004,"National Cancer Institute" = 13,"Other" = 181769837))
biospe$tube_nodev <- biospe$tubecol-biospe$tubedev
total1 <- sum(biospe$tubedev) 
total2 <- sum(biospe$tube_nodev) 
tube_dev <- as.data.frame(aggregate( biospe$tubedev,                # Specify data column[,c("tubedev","tube_nodev")]
                                     by = list(biospe$Site),              # Specify group indicator
                                     FUN = sum))
tube_nodev <- as.data.frame(aggregate( biospe$tube_nodev,                # Specify data column[,c("tubedev","tube_nodev")]
                                     by = list(biospe$Site),              # Specify group indicator
                                     FUN = sum))

  #changed Table17 to Deviation_Freq to match report

Deviation_Freq <- base::merge(tube_dev,tube_nodev,by="row.names")

Deviation_Freq <- Deviation_Freq[,c(2,3,5)]
Deviation_Freq$Total <- Deviation_Freq[,2]+Deviation_Freq[,3]
Deviation_Freq$dev_n_pct <- ifelse(Deviation_Freq[,2] >0, paste0(format(Deviation_Freq[,2],big.mark=",")," (", round(100*Deviation_Freq[,2]/Deviation_Freq$Total, 1)," %)"), "0 (0 %)")
Deviation_Freq$nodev_n_pct <- ifelse(Deviation_Freq[,3] >0, paste0(format(Deviation_Freq[,3],big.mark=",")," (",  round(100*Deviation_Freq[,3]/Deviation_Freq$Total,1), " %)"), "0 (0 %)")

Deviation_Freq[10,c(1:6)] <- c("Total",total1, total2,format(sum(biospe$tubecol),big.mark=","),
                        paste0(format(total1,big.mark=",")," (", round(100*sum(as.numeric(Deviation_Freq[1:9,2]))/sum(as.numeric(Deviation_Freq$Total), na.rm=T), 1)," %)"),  
                        paste0(format(total2,big.mark=",")," (", round(100*sum(as.numeric(Deviation_Freq[1:9,3]))/sum(as.numeric(Deviation_Freq$Total), na.rm=T),1)," %)"))     
Deviation_Freq <- Deviation_Freq %>% mutate(Site = ifelse(is.na(Group.1.x), "Total Tubes Collected",  as.character(Group.1.x))) ###to replace NA in the factor variable

```


```{r Deviations, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}
#Table 14. Number of deviations by biospecimen type and by tube type 
#keep this table for CCC version but remove from version that we are sharing with the sites
dev_tube <- NULL
for (i in 1:length(tube.ls)){
  
  id <- paste(tube.ls[i],"d_825582494",sep="_")
  tube <- paste(tube.ls[i],"d_678857215",sep="_")
  #note <- paste(tube.ls[i],"d_536710547",sep="_")
  tube_dev <- paste(tube.ls[i],"d_248868659", sep="_")
  deviation <- grep(tube_dev,colnames(biospe),value=TRUE)
  tmp <- as.data.frame(biospe[,which(colnames(biospe) %in% c(id,tube,deviation))] )
  tmp <- tmp[which(!is.na(tmp[,(colnames(tmp) == id)])),]
  
    dev_long <- data.table::melt(tmp,
                   id.vars=c(id,tube), 
                   measure.vars=deviation,
                   variable.name="dev_type",
                   value.name="deviation")
    
    
  colnames(dev_long)[grep("d_678857215",names(dev_long))] <- "d_678857215"
  colnames(dev_long)[grep("d_825582494",names(dev_long))] <- "TubeID"
  #colnames(dev_long)[grep("d_536710547",names(dev_long))] <- "d_536710547"
  
  dev_long <- dev_long[complete.cases(dev_long[,c("TubeID","d_678857215","dev_type","deviation")]),]
  #colnames(dev_long)[1] <- "d_678857215"
  #dev_long$d_536710547 <- as.character(dev_long$d_536710547)
  
  #dev_tube[[i]] <- dev_long
  dev_tube <- dplyr::bind_rows(dev_tube,dev_long)
  #print(c(i,bios.ls[i]))
}  
#329
   dev_tube1   <- dev_tube %>% filter(d_678857215 ==353358909 & deviation == 353358909)  %>%  
     mutate(biospecimen=ifelse(grepl("d_973670172",dev_type), "urine",
                                  ifelse(grepl("d_143615646",dev_type),"Mouthwash","blood")),
            tube_type = case_when(grepl("d_973670172",dev_type) ~ "Urine Tube1",
                                  grepl("d_143615646",dev_type) ~ "MW Tube1",
                                  grepl("d_299553921",dev_type) ~ "SS Tube1",
                                  grepl("d_703954371",dev_type) ~ "SS Tube2",
                                  grepl("d_454453939",dev_type) ~ "EDTA Tube1",
                                  grepl("d_838567176",dev_type) ~ "Heparin Tube1",
                                  grepl("d_652357376",dev_type) ~ "ACD Tube1",
                                  grepl("d_677469051",dev_type) ~ "EDTA Tube2",
                                  grepl("d_683613884",dev_type) ~ "EDTA Tube3",
                                  grepl("d_376960806",dev_type) ~ "SS Tube3",
                                  grepl("d_232343615",dev_type) ~ "SS Tube4",
                                  grepl("d_589588440",dev_type) ~ "SS Tube5",
                                  grepl("d_958646668",dev_type) ~ "Heparin Tube2"),
            
              deviationnotes =case_when(sapply(strsplit(as.character(dev_type),"d_"),tail,1) =="102695484" ~ "Deviation Clot < 30min",
                  sapply(strsplit(as.character(dev_type),"d_"),"[[",4) =="242307474" ~ "Hemolyzed", 
                  sapply(strsplit(as.character(dev_type),"d_"),"[[",4) =="283900611" ~ "Mislabel Resolved",
                  sapply(strsplit(as.character(dev_type),"d_"),"[[",4) =="313097539" ~ "Outside Contamated",
                  sapply(strsplit(as.character(dev_type),"d_"),"[[",4) =="453343022" ~ "Other",
                  sapply(strsplit(as.character(dev_type),"d_"),"[[",4) =="472864016" ~ "Broken", 
                  sapply(strsplit(as.character(dev_type),"d_"),"[[",4) =="550088682" ~ "Temparture Too Low",
                  sapply(strsplit(as.character(dev_type),"d_"),"[[",4) =="561005927" ~ "Cent Low",
                  sapply(strsplit(as.character(dev_type),"d_"),"[[",4) =="635875253" ~ "Broken Gel",
                  sapply(strsplit(as.character(dev_type),"d_"),"[[",4) =="654002184" ~ "Centrifuge Too Long",
                  sapply(strsplit(as.character(dev_type),"d_"),"[[",4) =="684617815" ~ "MisLabled Discard",
                  sapply(strsplit(as.character(dev_type),"d_"),"[[",4) =="690540566" ~"Tempature Too High",
              sapply(strsplit(as.character(dev_type),"d_"),"[[",4) =="728366619" ~"Low Volume-(tube/container partially filled but still usable)",
              sapply(strsplit(as.character(dev_type),"d_"),"[[",4) =="742806035" ~"MW < 30s",
              sapply(strsplit(as.character(dev_type),"d_"),"[[",4) =="757246707" ~"Leak/Spilled",
              sapply(strsplit(as.character(dev_type),"d_"),"[[",4) =="777486216" ~"Tube Size",
              sapply(strsplit(as.character(dev_type),"d_"),"[[",4) =="810960823" ~"Discard",
              sapply(strsplit(as.character(dev_type),"d_"),"[[",4) =="861162895" ~"Cent High",
              sapply(strsplit(as.character(dev_type),"d_"),"[[",4) =="912088602" ~"Clot > 2h",
              sapply(strsplit(as.character(dev_type),"d_"),"[[",4) =="937362785" ~"Centrifuge Too Short",
              sapply(strsplit(as.character(dev_type),"d_"),"[[",4) =="956345366" ~"Insufficient Volume",
              sapply(strsplit(as.character(dev_type),"d_"),"[[",4) =="982885431" ~ "Not Found"))
notcol_tubes <- colnames(biospe)[grepl("883732523",colnames(biospe))] #7
col_tubes <- colnames(biospe)[grepl("d_593843561",colnames(biospe))] #13
dev_tubes <- colnames(biospe)[grepl("d_678857215",colnames(biospe))] #13
notcol.ls <- sapply(strsplit(notcol_tubes, "_d"),"[[",1)
   notcol_tube <- NULL
   tubenotcol.ls <-list()
 
   for (i in 1:length(notcol.ls)){
     
     tubecol <- paste(notcol.ls[i],"d_593843561",sep="_")
     tube_notcol <- paste(notcol.ls[i],"d_883732523", sep="_") #notcolnotes
     TubeID <- paste(tube.ls[i],"d_825582494",sep="_")
     #tube_notcolnotes <- paste(tube.ls[i],"d_338286049", sep="_")
     tube_deviation <- paste(notcol.ls[i], "d_678857215",sep="_")
     #tube_devnotes <- paste(notcol.ls[i],"d_536710547",sep="_") 
     #select <- c(tubecol,tube_notcol,tube_notcolnotes,tube_deviation,tube_devnotes)
     select <- c(TubeID,tubecol,tube_notcol,tube_deviation)
     tmp <- biospe[,(colnames(biospe)%in% c(select,"d_820476880","Site","biocol_Setting"))] 
     notcol <- tmp 
     colnames(notcol)[colnames(notcol)==TubeID] <- "TubeID"
     colnames(notcol)[colnames(notcol)==tubecol] <- "tubecol"
     colnames(notcol)[colnames(notcol)==tube_notcol] <- "tube_notcol"
     #colnames(notcol)[colnames(notcol)==tube_notcolnotes] <- "tube_notcolnotes"
     colnames(notcol)[colnames(notcol)==tube_deviation] <- "tube_deviation"
     #colnames(notcol)[colnames(notcol)==tube_devnotes] <- "tube_deviationnotes"
     
     #if(!grepl("tube_notcolnotes",colnames(notcol))){notcol$tube_notcolnotes <- NA}   
     #if(!grepl("tube_deviationnotes",colnames(notcol))){notcol$tube_deviationnotes <- NA} 
     
     notcol$tubeID <- notcol.ls[i]
     #notcol1 <- notcol[which(notcol$tubecol==104430631),] 
     notcol_tube <- dplyr::bind_rows(notcol_tube,notcol)
     #tubenotcol.ls[[i]] <- notcol1
     #collection_long <- dplyr::bind_rows(collection_long,notcol)
   } 
   
   #collection_long <- as.data.frame(do.call("rbind",notcol_tube))
   
   ##collected tube and deviaton (both have the same length oftubes)
      collection_long <- NULL
   for (i in 1:length(tube.ls)){
     
     tubeid <- paste(tube.ls[i],"d_825582494",sep="_")
     tubecol <- paste(tube.ls[i],"d_593843561",sep="_")
     tube_deviation <- paste(tube.ls[i], "d_678857215",sep="_")
     tube_discard <- paste(tube.ls[i], "d_762124027",sep="_")
     #select <- c(tubecol,tube_notcol,tube_notcolnotes,tube_deviation,tube_devnotes)
     select <- c(tubeid,tubecol,tube_deviation,tube_discard)
     tmp <- biospe[,(colnames(biospe)%in% c(select,"d_820476880","Site","biocol_Setting"))] 
     col <- tmp 
     colnames(col)[colnames(col)==tubeid] <- "TubeID"
     colnames(col)[colnames(col)==tubecol] <- "tubecol"
     colnames(col)[colnames(col)==tube_deviation] <- "tube_deviation"
     colnames(col)[colnames(col)==tube_discard] <- "tube_discard"
     
     col$tubeID <- tube.ls[i]
     collection_long <- dplyr::bind_rows(collection_long,col)
   } 
   
   collection_long <- collection_long  %>% 
     dplyr:: mutate(deviation = case_when(tube_deviation == 353358909 ~ "Any Deviation",
                                          tube_deviation == 104430631 ~ "No Deviation"),
                    Collected = case_when(tubecol ==353358909 ~ "Collected",
                                          tubecol == 104430631 ~ "Not  Collected"),
                    Discarded = case_when(tube_discard == 353358909 ~ "Any Discard",
                                          tube_discard == 104430631 ~ "No Discard"),
                    biospecimen=ifelse(tubeID=="d_973670172", "urine",
                                  ifelse(tubeID=="d_143615646","Mouthwash","blood")),
                    tube_type = case_when(tubeID == "d_973670172"  ~ "Urine Tube1",
                                          tubeID == "d_143615646"  ~ "MW Tube1",
                                          tubeID == "d_299553921"  ~ "SS Tube1",
                                          tubeID == "d_703954371"  ~ "SS Tube2",
                                          tubeID == "d_454453939"  ~ "EDTA Tube1",
                                          tubeID == "d_838567176"  ~ "Heparin Tube1",
                                          tubeID == "d_652357376"  ~ "ACD Tube1",
                                          tubeID == "d_677469051"  ~ "EDTA Tube2",
                                          tubeID == "d_683613884"  ~ "EDTA Tube3",
                                          tubeID == "d_376960806"  ~ "SS Tube3",
                                          tubeID == "d_232343615"  ~ "SS Tube4",
                                          tubeID == "d_589588440"  ~ "SS Tube5",
                                          tubeID == "d_958646668"  ~ "Heparin Tube2"))
  collection_long$tube_type <- factor(collection_long$tube_type, levels=c("SS Tube1", "SS Tube2","SS Tube3", "SS Tube4", "SS Tube5","Heparin Tube1","Heparin Tube2","EDTA Tube1", "EDTA Tube2","EDTA Tube3","ACD Tube1","Urine Tube1","MW Tube1" ) )  
     
   Table17_option2 <- collection_long %>% mutate(deviation = dplyr::case_when(tube_deviation == 353358909 ~ "Any Deviation",
                                                                              tube_deviation == 104430631 ~ "No Deviation"),
                                                   Collected = dplyr::case_when(tubecol ==353358909 ~ "Collected",
                                                                                tubecol == 104430631 ~ "Not Collected")) %>%  #filter(d_650516960==534621077 & !is.na(d_331584571_d_266600170_d_343048998) ) %>% 
     select(Site,deviation) %>%
     tbl_cross(    col = deviation,
                   row = Site,
                   percent = "row",
                   #label=(),
                   missing="no") %>%
     bold_labels() %>%
     italicize_levels() %>% 
     modify_header() %>%
     modify_caption("Table 17. Number (and percent) of tubes with any deviation by site") %>%
     as_kable()#tab_header(title = "Patient Characteristics", subtitle = "Presented by treatment")
   
   
   dev_tube1$tube_dev <- paste(dev_tube1$tube_type,"Deviation", dev_tube1$deviationnotes,sep=" ")
   dev_tube1$tubeID <- substr(dev_tube1$dev_type,1,11)
  dev <- collection_long %>% filter(tube_deviation==353358909) 
  dev_tube2 <- base::merge(dev,dev_tube1[,c("dev_type","TubeID","tubeID","deviationnotes","tube_dev")],by.x=c("TubeID","tubeID"), by.y=c("TubeID","tubeID")) ##to get the deviation notes


#This is referencred directly in table 12  
  dev_count <- dev_tube2 %>% group_by(biocol_Setting,biospecimen,tube_dev) %>%   dplyr::summarize(count=n()) 
  #dev_count <- dev_count[3:4] #removed setting and type as requested-- maybe add that when table is actually ran?
  #dev_count <- dev_count %>%  mutate(Site=droplevels(Site))   #try this for later filtering 
  colnames(dev_count) <- c("Deviation","Number")
  

  
   dev_count.site <- list() 
dev_tube2$Site <- droplevels(dev_tube2$Site)
for(site in unique(dev_tube2$Site)){
  
  site.sub <- dev_tube2 %>% filter(Site==site) %>% 
    group_by(tube_dev) %>% dplyr::tally() 
  total <- as.numeric(nrow(dev_tube2[which(dev_tube2$Site==site),]))
  dev_count.site[[site]] <- site.sub
}
```
  
  

  
  
  
  
```{r Table8, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}
# 
# biospe= biospe  %>% mutate(UC_Sites= case_when(d_951355211==777644826 ~ "UC-DCAM",
#                                        d_951355211==145191545 ~ "Ingalls Harvey",
#                                        d_951355211==489380324 ~ "River East",
#                                        d_951355211==120264574 ~ "South Loop"))
# tube_col_UC <- biospe  %>% group_by(as.character(Connect_ID),UC_Sites,d_650516960) %>% 
#   filter(UC_Sites=="UC-DCAM" | UC_Sites=="Ingalls Harvey" |  UC_Sites=="River East" |  UC_Sites=="South Loop" ) %>% 
#   dplyr::summarise(bldcol_max = max(bldcol,na.rm=TRUE),
#                    Urine_col_max= max(Urine_col,na.rm=TRUE),
#                    MW_col_max=max(MW_col,na.rm=TRUE),
#                    d_973670172_d_593843561_max=max(d_973670172_d_593843561,na.rm=TRUE),
#                    d_143615646_d_593843561_max = max(d_143615646_d_593843561,na.rm=TRUE),
#                    d_410912345_max=max(d_410912345,na.rm=TRUE),
#                    collection.tm =max(as.POSIXct(ymd_hms(d_556788178)),na.rm=TRUE),
#                    schedulecol.tm =min(as.POSIXct(ymd_hms(d_678166505)),na.rm=TRUE))

  research.coltube<- collection_long %>% filter(biocol_Setting == "Research" & tubecol == 104430631) %>%     
    mutate(Site=droplevels(Site),
           tube_type = factor(tube_type,levels=c("SS Tube1", "SS Tube2","Heparin Tube1","EDTA Tube1","ACD Tube1","Urine Tube1","MW Tube1" )))
  
  
    research.coltube.bld.only<- collection_long %>% filter(Site == "University of Chicago Medicine" & tubecol == 104430631) %>% 
    mutate(Site=droplevels(Site),
           tube_type = factor(tube_type,levels=c("SS Tube1", "SS Tube2","Heparin Tube1","EDTA Tube1","ACD Tube1")))
    research.coltube.bld.only<- research.coltube.bld.only %>%  mutate(tube_type=droplevels(tube_type))


T8UC <- biospeUC %>%  select(Collection_Location, Site) ##MAY NOT WORK ADDING CONNECTID 
T8__UC <- left_join(research.coltube.bld.only, T8UC, by= "Site") #aDDING IN CONNECT id IS A PROBLEM, BUT i NEED A WAY TO DISTINGUISH PARTICIPANTS SO THEY'RE NOT COUNTED REPEATEDLY
# tube_col_UC3 <- tube_col_UC %>% select(UC_Sites)
# tube_col_UC3$Collection_Location <- tube_col_UC3$UC_Sites 
# df3 <- left_join(tube_col_UC3, T8__UC, by='Collection_Location')
# tube_col_UC3 <- tube_col_UC %>% select(UC_Sites)
# 
# table3_tubes <- research.coltube.bld.only %>% select(tube_type, Site)



tube_col_UC3 <- tube_col_UC %>% select(UC_Sites, Connect_ID, bldcol_max)

All_UC3 <- biospeUC %>% select(Collection_Location, Connect_ID,  d_820476880,  d_299553921_d_825582494,  d_454453939_d_825582494, d_652357376_d_825582494, d_703954371_d_825582494,  d_838567176_d_825582494) #d_505347689_d_825582494,
tube_col_UC3$Collection_Location <- tube_col_UC3$UC_Sites 
df3 <- left_join(tube_col_UC3, All_UC3, by=c("Connect_ID", 'Collection_Location'))

df3 <- df3 %>% mutate(tube_type = case_when(!is.na(d_299553921_d_825582494) ~ "SS Tube1",
                                          !is.na(d_703954371_d_825582494) ~ "SS Tube2",
                                          !is.na(d_454453939_d_825582494) ~ "EDTA Tube1",
                                          !is.na(d_838567176_d_825582494) ~ "Heparin Tube1",
                                          !is.na(d_652357376_d_825582494) ~ "ACD Tube1"))



#df4 <- left_join(df3, All_UC3, by=c("Connect_ID", 'Collection_Location'))    


tbl_3 <- df3 %>%  filter(bldcol_max!=5 & bldcol_max!=0)
tbl_3_ncol <- tbl_3 %>% dplyr::select(Collection_Location, tube_type )  %>% tbl_cross(
  row = Collection_Location,
  col = tube_type, 
  digits=c(0,1),
  percent = "row",
  label=list(Collection_Location ~ " ", tube_type ~ " "),
  # label=list(Collection_Location,="",

  #            tube_type = ""),
  missing="ifany") %>%
  #bold_labels() %>%
  #italicize_levels() %>%
  modify_header() %>%
  modify_caption("Table 3. Research Blood Tubes Not Collected Among Partial Blood Collections by Collection Location") %>%
  as_kable_extra(escape = FALSE, addtl_fmt = TRUE)



 
  

# ctable <-  CrossTable(T8__UC$Collection_Location, T8__UC$tube_type)

# 
# 
# nocol.type <- as.data.frame(cbind(ctable$t,ctable$prop.col))
# 
#   pct_n <- function(x,y){ paste0(x,"( ", round(100*y,1), " %)")}
#       count <- as.data.frame.matrix(ctable$t) # to convert the S3 table into the same dimention table via as.data.frame.matrix
#       perc <- as.data.frame.matrix(ctable$prop.col)
#       
#       
#    pct_n2 <- function(x,y){ paste0(x,"( ", round(100*y,1), " %)")}
#       count2 <- as.data.frame.matrix(ctable$t) # to convert the S3 table into the same dimention table via as.data.frame.matrix
#       perc2 <- as.data.frame.matrix(ctable$prop.col)     
# 
# 
#   #notcol_combo = array(pct_n(ctable$t,ctable$prop.col),dim=c(5,7))
#   notcol_combo = array(pct_n(ctable$t,ctable$prop.col),dim=c(4,5))
# 
#   notcol_combo <- as.data.frame(notcol_combo)
#   colnames(notcol_combo) <- colnames(count2)
#   #notcol_combo <- notcol_combo[, c(1:5)] # I added to get rid of MW and Urine, to fix total column
#   
#   count2$Total.NotCol <- apply(count2,1,sum)
#   total <- sum(count2)
#   #notcol_combo$Total.Notcol <- paste0(apply(count[c(1:5),c(1:7)],1,sum), "( ", round(100*apply(count2[c(1:5),c(1:7)],1,sum)/total,2), " %)")
#   notcol_combo$Total.Notcol <- paste0(count2$Total.NotCol, "( ", round(100*count2$Total.NotCol/sum(count2$Total.NotCol),1), " %)")
#   

#   notcol_combo$Collection_Location <- rownames(count2)
# 
#   #notcol_combo[6,c(1:8)] <- as.character(apply(count,2,sum))
# notcol_combo[6,c(1:6)] <- as.character(apply(count2,2,sum))
#   notcol_combo$Collection_Location[is.na(notcol_combo$Collection_Location)] <- replace_na("Total") 

  
  
  
  

```







```{r Table12a12b, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}
  
## Table 15  
##Table X: Reason not collected by tube type and by site for research collections only
  a<- collection_long[which(collection_long$tubecol==104430631),]
  b <- notcol_tube[which(notcol_tube$tubecol == 104430631),]
  notcol_notes <- base::merge(a, b[,c("tubeID","d_820476880","tube_notcol")], by=c("tubeID","d_820476880"),all.x=TRUE)
notcol_notes <- notcol_notes %>% 
  mutate(notcol.notes = case_when(tubecol == 104430631 & tube_notcol==181769837 ~ "Other",
                                  tubecol == 104430631 & tube_notcol==234139565 ~ "Short Draw",
                                  tubecol == 104430631 & tube_notcol==681745422 ~ "Participant Refusal",
                                  tubecol == 104430631 & tube_notcol==745205161 ~ "Participant Attempted",
                                  tubecol == 104430631 & tube_notcol==889386523 ~ "Supply Unavailable",
                                  tubecol == 104430631 & is.na(tube_notcol) ~ "Missing Reasons"),
         Collected = case_when(tubecol ==353358909 ~ "Collected",
                               tubecol == 104430631 ~ "Not  Collected"),
                    biospecimen=ifelse(tubeID=="d_973670172", "urine",
                                  ifelse(tubeID=="d_143615646","Mouthwash","blood")),
                    tube_type = case_when(tubeID == "d_973670172"  ~ "Urine Tube1",
                                          tubeID == "d_143615646"  ~ "MW Tube1",
                                          tubeID == "d_299553921"  ~ "SS Tube1",
                                          tubeID == "d_703954371"  ~ "SS Tube2",
                                          tubeID == "d_454453939"  ~ "EDTA Tube1",
                                          tubeID == "d_838567176"  ~ "Heparin Tube1",
                                          tubeID == "d_652357376"  ~ "ACD Tube1",
                                          tubeID == "d_677469051"  ~ "EDTA Tube2",
                                          tubeID == "d_683613884"  ~ "EDTA Tube3",
                                          tubeID == "d_376960806"  ~ "SS Tube3",
                                          tubeID == "d_232343615"  ~ "SS Tube4",
                                          tubeID == "d_589588440"  ~ "SS Tube5",
                                          tubeID == "d_958646668"  ~ "Heparin Tube2"))
notcol_notes$tube_type <- factor(notcol_notes$tube_type, levels=c("SS Tube1", "SS Tube2","SS Tube3", "SS Tube4", "SS Tube5","Heparin Tube1","Heparin Tube2","EDTA Tube1", "EDTA Tube2","EDTA Tube3","ACD Tube1","Urine Tube1","MW Tube1" ) ) 
notcol_notes$notcol.notes <- factor(notcol_notes$notcol.notes, levels=c("Short Draw","Participant Attempted", "Other", "Participant Refusal", "Supply Unavailable", "Missing Reasons"))




n_pct_table <- function(x,y){
  #x<-clinicnotes.notcol$Site
  #y<-clinicnotes.notcol$notcol.notes
  ctable<- CrossTable(x,y)
count <- as.data.frame.matrix(ctable$t)
perc <- as.data.frame.matrix(ctable$prop.col)
n<- as.numeric(length(levels(x)))
m <- as.numeric(length(levels(y)))
tb_combo <- array(pct_n(ctable$t,ctable$prop.col),dim=c(n,m)) 
  tb_combo <- as.data.frame(tb_combo)
  colnames(tb_combo) <- colnames(count)
  
  total <- sum(count)
  count$Total <- apply(count,1,sum)
  tb_combo$Total <- paste0(count$Total, "( ", round(100*(count$Total)/total,1), " %)")
  
  tb_combo$Site <- rownames(count)
  tb_combo[(n+1),c(1:(m+1))] <- as.character(apply(count,2,sum))
  tb_combo$Site[is.na(tb_combo$Site)] <- replace_na("Total")  
  return(tb_combo)
}
research.notcol <- notcol_notes %>% filter(biocol_Setting=="Research" & tubecol==104430631) %>% 
   mutate(Site=droplevels(Site),
           tube_type = factor(tube_type,levels=c("SS Tube1", "SS Tube2","Heparin Tube1","EDTA Tube1","ACD Tube1","Urine Tube1","MW Tube1" )))
research.notcol$notcol.notes <- factor(research.notcol$notcol.notes, levels=c("Short Draw","Participant Attempted", "Participant Refusal", "Supply Unavailable","Other",  "Missing Reasons"))
#research.notcol$notcol.notes <- droplevels(research.notcol$notcol.notes)
reseachnotes.notcol <- n_pct_table(research.notcol$Site,research.notcol$notcol.notes)
reseachnotes.coltype <- n_pct_table(research.notcol$tube_type,research.notcol$notcol.notes)
notcol.reasons.research <- rbind(reseachnotes.notcol,reseachnotes.coltype)



#research.notcol$Collection_Location <- droplevels(research.notcol$Collection_Location)



T12__UC <- research.notcol %>% filter(Site=="University of Chicago Medicine")
T12__UC$Site=droplevels(T12__UC$Site)


notcol_notes_table4 <- research.notcol %>% filter(biospecimen=="blood" & Site=="University of Chicago Medicine")
T12UC <- left_join(notcol_notes_table4, df3, by="d_820476880") #aDDING IN CONNECT id IS A PROBLEM, BUT i NEED A WAY TO DISTINGUISH PARTICIPANTS SO THEY'RE NOT COUNTED REPEATEDLY


df3$Collection_Location <- df3$UC_Sites

T12UC <- T12UC %>%  filter(!is.na(Collection_Location))

research.notcolnotes_site <- T12UC %>% select(notcol.notes,Collection_Location) %>% 
  tbl_cross(  col = notcol.notes,
                  row = Collection_Location,
                   percent = "row",
                   digits= c(0,1),
                   label= c(notcol.notes~ " ", Collection_Location ~ " "),
                   missing="ifany",
                   missing_text="0 ( 0 %)")%>%
     modify_header() %>%
     modify_caption("Table 4. Reason Not Collected for Research Tubes Not Collected by Collection Location ") %>% 
  as_kable_extra() %>% kable_styling(latex_options = "scale_down")


#tbl_3_ncol
research.notcolnotes_site 





```


```{r Table13, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}








## Table 16 
#Table Number of tube tubes Discarded by tube type and site


tube_col_UC3 <- tube_col_UC %>% select(UC_Sites, Connect_ID, bldcol_max)

All_UC3 <- biospeUC %>% select(Collection_Location, Connect_ID,  d_820476880,  d_299553921_d_825582494,  d_454453939_d_825582494, d_652357376_d_825582494, d_703954371_d_825582494,  d_838567176_d_825582494) #d_505347689_d_825582494,
tube_col_UC3$Collection_Location <- tube_col_UC3$UC_Sites 
df3 <- left_join(tube_col_UC3, All_UC3, by=c("Connect_ID", 'Collection_Location'))

df3 <- df3 %>% mutate(tube_type = case_when(!is.na(d_299553921_d_825582494) ~ "SS Tube1",
                                          !is.na(d_703954371_d_825582494) ~ "SS Tube2",
                                          !is.na(d_454453939_d_825582494) ~ "EDTA Tube1",
                                          !is.na(d_838567176_d_825582494) ~ "Heparin Tube1",
                                          !is.na(d_652357376_d_825582494) ~ "ACD Tube1"))



#df4 <- left_join(df3, All_UC3, by=c("Connect_ID", 'Collection_Location'))    


tbl_3 <- df3 %>%  filter(bldcol_max!=5 & bldcol_max!=0)
tbl_3_ncol <- tbl_3 %>% dplyr::select(Collection_Location, tube_type )  %>% tbl_cross(
  row = Collection_Location,
  col = tube_type, 
  digits=c(0,1),
  percent = "row",
  label=list(Collection_Location ~ " ", tube_type ~ " "),
  # label=list(Collection_Location,="",
  #            tube_type = ""),
  missing="ifany") %>%
  #bold_labels() %>%
  #italicize_levels() %>%
  modify_header() %>%
  modify_caption("Table 3. Research Blood Tubes Not Collected Among Partial Blood Collections by Collection Location") %>%
  as_kable_extra(escape = FALSE, addtl_fmt = TRUE)




T12__16 <- left_join(collection_long, T8UC, by= "Site")

discard.tb <- T12__16  %>% filter(tube_discard == 353358909) %>% 
  mutate(#Collection_Location=droplevels(Collection_Location),
           tube_type = droplevels(tube_type))


collection_long_disc <- collection_long %>% filter(tube_discard==353358909)
collection_long_disc2 <- collection_long_disc %>% filter(Site=="University of Chicago Medicine")


tube_disc5 <- collection_long_disc2 %>% select(Site, d_820476880) 

All_UC5 <- biospeUC %>% select(Site, Collection_Location, Connect_ID,  d_820476880,  d_299553921_d_825582494,  d_454453939_d_825582494, d_652357376_d_825582494, d_703954371_d_825582494,  d_838567176_d_825582494, d_820476880, d_589588440_d_825582494, d_958646668_d_825582494, d_973670172_d_825582494) #d_505347689_d_825582494,

df5 <- left_join(tube_disc5, All_UC5, by=c("Site", "d_820476880"))


df5_2 <- df5 %>% mutate(tube_type = case_when(!is.na(d_299553921_d_825582494) ~ "SS Tube1",
                                          !is.na(d_703954371_d_825582494) ~ "SS Tube2",
                                          !is.na(d_589588440_d_825582494) ~ "SS Tube5",
                                          !is.na(d_454453939_d_825582494) ~ "EDTA Tube1",
                                          !is.na(d_838567176_d_825582494) ~ "Heparin Tube1",
                                          !is.na(d_958646668_d_825582494) ~ "Heparin Tube2",
                                          !is.na(d_652357376_d_825582494) ~ "ACD Tube1",
                                          !is.na(d_973670172_d_825582494) ~ "Urine Tube1"))

#sstube1, sstube2, sstube5 589588440, heptuube1, heptub2 958646668, edtatube1, acdtube1, urinetube1 973670172

#17- by site

discard.site5 <- df5_2 %>% dplyr::select(Collection_Location, tube_type )  %>% tbl_cross(
    row = Collection_Location,
    col = tube_type, 
    digits=c(0,1),
    percent = "row",
    label=list(Collection_Location ~ " ", tube_type ~ " "),
    # label=list(Collection_Location,="",

    #            tube_type = ""),
    missing="ifany") %>%
    #bold_labels() %>%
    #italicize_levels() %>%
    modify_header() %>%
    modify_caption("Table 5. Research Tube Types Discarded by Collection Location") %>%
    as_kable_extra(escape = FALSE, addtl_fmt = TRUE)





```


```{r Table14, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}

###back to the recruitment table
biospe.tm <- recrvar.bio$column_name[which(grepl("Date|time|Time", recrvar.bio$Variable.Label))]
recrvar.bio[which(grepl("Date|time|Time", recrvar.bio$Variable.Label)),c("field_path","Variable.Label")]
#                              field_path                                                     Variable.Label
# 12  d_173836415_d_266600170_d_139245758                                 Date/time Clinical Urine collected
# 43                          d_222161762          Date/Time blood/urine/mouthwash research survey completed
# 48  d_173836415_d_266600170_d_224596428                       Clinical Site Urine RRL Date / Time Received
# 85  d_331584571_d_266600170_d_343048998                                            Time check out complete
# 100                         d_390198398                            Date/time refused baseline blood sample
# 101 d_173836415_d_266600170_d_398645039                           Clinical DB blood RRL Date/Time Received
# 121 d_173836415_d_266600170_d_448660695                                      Date/time Mouthwash Collected
# 156                         d_534669573                    Date/time Status of Start of blood/urine survey
# 161 d_173836415_d_266600170_d_541311218                           Clinical DB urine RRL Date/Time received
# 170 d_173836415_d_266600170_d_561681068                                 Date/time Research Blood Collected
# 240 d_173836415_d_266600170_d_740582332    Autogenerated date/time stamp for Any specimen collected at RRL
# 247                         d_764863765                             Date/Time blood/urine survey completed
# 249 d_173836415_d_266600170_d_769615780                                       Date/Time Blood Order Placed
# 260                         d_808663245                            Date/time refused baseline urine sample
# 266 d_173836415_d_266600170_d_822274939                       Clinical Site Blood RRL Date / Time Received
# 267                         d_822499427 Date/time Status of Start of blood/urine/mouthwash research survey
# 276 d_331584571_d_266600170_d_840048338                                        Date/Time Check-In Complete
# 278 d_173836415_d_266600170_d_847159717                                 Date/time Research Urine collected
# 306 d_173836415_d_266600170_d_939818935                                       Date/Time Urine Order Placed
# 319 d_173836415_d_266600170_d_982213346                                 Date/time Clinical Blood Collected
recrvar.bio[which(grepl("Survey", recrvar.bio$Primary.Source)),c("field_path","Primary.Source","Variable.Label")]
#      field_path Primary.Source                                                     Variable.Label
# 43  d_222161762         Survey          Date/Time blood/urine/mouthwash research survey completed
# 52  d_253883960         Survey                                        Flag for blood/urine survey
# 58  d_265193023         Survey                     Blood/urine/mouthwash combined research survey
# 156 d_534669573         Survey                    Date/time Status of Start of blood/urine survey
# 164 d_547363263         Survey                                          Flag for mouthwash survey
# 247 d_764863765         Survey                             Date/Time blood/urine survey completed
# 267 d_822499427         Survey Date/time Status of Start of blood/urine/mouthwash research survey





#Table 17
#recr.bio

Test_res_plots <- recr.bio %>%  select(Connect_ID, d_173836415_d_266600170_d_561681068, d_173836415_d_266600170_d_847159717, d_173836415_d_266600170_d_448660695)
Test_res_plots$Connect_ID <- as.numeric(Test_res_plots$Connect_ID)
tube_col$Connect_ID <- as.numeric(tube_col$Connect_ID)
tube_col_plots <- left_join(tube_col, Test_res_plots, by="Connect_ID")
#head(tube_col_plots)

# tube_col_plots <- tube_col_plots %>%
#   mutate(bldcol.time = case_when(bldcol_max >0 ~ pmin(as.POSIXct(d_173836415_d_266600170_d_561681068),na.rm=TRUE)),
#          urine.time = case_when(Urine_col_max >0 ~ pmin(as.POSIXct(d_173836415_d_266600170_d_847159717),na.rm=TRUE)),
#          mw.time = case_when(MW_col_max >0 ~ pmin(as.POSIXct(d_173836415_d_266600170_d_448660695),na.rm=TRUE)),
#          BUM.time = pmin(as.POSIXct(bldcol.time),as.POSIXct(urine.time),as.POSIXct(mw.time), na.rm = TRUE)) ## matches up exactly with operations code but causes issues with plots 6 & 7
tube_col_plots$BUM.time <- tube_col$collection.tm

tube_col_plots$col.Sunday.week <- ceiling(as.numeric(difftime(tube_col_plots$BUM.time,as.Date(veristart.date-days(2)),units="days"))/7)
#tube_col$col.Sunday.week <-  ceiling(as.numeric(difftime(as.Date(ymd_hms(tube_col$collection.tm)),as.Date(veristart.date-days(2)),units="days"))/7)
tube_col_plots$col.Sunday.date <- veristart.date + days(5) + dweeks(tube_col_plots$col.Sunday.week-1) 
tube_col_plots$col.Monday.date <- tube_col_plots$col.Sunday.date-days(6)
 

recr.biospe <- base::merge(recr.bio,tube_col_plots,by="Connect_ID")
recr.biospe <- recr.biospe %>%
  mutate(research.sv = case_when(d_265193023 == 231311385 ~ "Submitted",
                                 d_265193023 == 615768760 ~ "Started",
                                 d_265193023 == 972455046 ~ "Not Started"),
          clinic.sv = case_when(d_253883960 == 231311385 ~ "Submitted",
                               d_253883960 == 615768760 ~ "Started",
                               d_253883960 == 972455046 ~ "Not Started"))
##Total number and percent of research biospecimen survey status
research.survey <- recr.biospe %>% filter(d_650516960 == 534621077)
 research.survey <- research.survey %>% 
   mutate(research.svtime =  difftime(as.POSIXct(ymd_hms(d_222161762)),as.POSIXct(ymd_hms(d_822499427)),units="hours"),##survey time from start to complete
         tm_biocolsuv = difftime(as.POSIXct(ymd_hms(d_222161762)),as.POSIXct(ymd_hms(d_331584571_d_266600170_d_840048338)),units="hours")) #time between survey completion to biospecimen collection visit check in
research.survey <-research.survey %>%
           mutate(checktmvisit = case_when( as.numeric(tm_biocolsuv) >72 ~"Greater than 72hrs (3 days)",
                                            72 >= as.numeric(tm_biocolsuv) & as.numeric(tm_biocolsuv) > 48 ~ "> 48 hrs to 72 hrs",
                                            48 >= as.numeric(tm_biocolsuv) & as.numeric(tm_biocolsuv) > 24 ~ "> 24 hrs to 48 hrs",   
                                            24 >= as.numeric(tm_biocolsuv) & as.numeric(tm_biocolsuv) > 12 ~ "> 12 hrs to 24 hrs",
                                            12 >= as.numeric(tm_biocolsuv) & as.numeric(tm_biocolsuv) > 3 ~ "> 3 hrs to 12 hrs",  
                                            3 >= as.numeric(tm_biocolsuv) & as.numeric(tm_biocolsuv) >= 0 ~ "0 hrs to 3 hrs",
                                            d_265193023 != 231311385 ~ "Not Submitted", 
                                            TRUE ~ "Missing Time"), #changed from NA to "Missing"
         time_biochk = difftime(as.POSIXct(ymd_hms(d_331584571_d_266600170_d_343048998)),as.POSIXct(ymd_hms(d_331584571_d_266600170_d_840048338)),units="mins"))
research.survey$biochk_outlier <- ifelse(is.na(research.survey$time_biochk), "Missing (not checked out)", ifelse( 0<= as.numeric(research.survey$time_biochk)/60 & as.numeric(research.survey$time_biochk)/60 <= 24, "No Outlier", ifelse(as.numeric(research.survey$time_biochk)/60 > 24, "Outlier",  "Undefined")) )   
research.survey$biochk_outlier <- factor(research.survey$biochk_outlier,levels=c("No Outlier","Outlier","Missing (not checked out)"))
research.survey$checktmvisit <- factor(research.survey$checktmvisit, levels=c( "Not Submitted", "Missing Time", "0 hrs to 3 hrs","> 3 hrs to 12 hrs","> 12 hrs to 24 hrs","> 24 hrs to 48 hrs","> 48 hrs to 72 hrs","Greater than 72hrs (3 days)")) 
research.survey[which(research.survey$research.svtime <0),c("Connect_ID","d_650516960","Site","d_265193023","d_222161762","d_822499427")]
#     Connect_ID d_650516960                            Site d_265193023              d_222161762              d_822499427
# 259 2848814334   534621077 Marshfield Clinic Health System   231311385 2022-08-26T08:00:00.000Z 2022-08-30T00:43:06.653Z
# 274 2927684519   534621077 Marshfield Clinic Health System   231311385 2022-11-16T08:00:00.000Z 2022-11-30T22:39:24.145Z
# 337 3342756222   534621077                  HealthPartners   231311385 2022-10-22T08:00:00.000Z 2022-11-08T03:48:34.373Z
# 661 5226692703   534621077                  HealthPartners   231311385 2022-08-15T08:00:00.000Z 2022-08-15T22:49:30.154Z
##these four participants' survey time viloted the time sequential rule
research.survey[which(as.numeric(research.survey$tm_biocolsuv)<0),c("Connect_ID","d_650516960","Site","d_265193023","d_222161762","d_822499427","d_331584571_d_266600170_d_840048338")]
#     Connect_ID d_650516960                            Site d_265193023              d_222161762              d_822499427
# 274 2927684519   534621077 Marshfield Clinic Health System   231311385 2022-11-16T08:00:00.000Z 2022-11-30T22:39:24.145Z
#     d_331584571_d_266600170_d_840048338
# 274            2022-11-16T13:10:58.573Z
sv.complete <- as.data.frame(tab1(research.survey$research.sv))
sv.complete <- sv.complete %>% mutate(cumulative.Freq = ifelse(output.table.Percent<100.0, cumsum(output.table.Frequency),output.table.Frequency)) 



bum_compl <- recrver1 %>%  select(d_265193023, Site, Connect_ID) %>% filter( Site=="University of Chicago Medicine")
T8UC <- biospeUC %>%  select(Collection_Location, Site, Connect_ID)  
T14_UC <- left_join(bum_compl, T8UC, by= c("Site", "Connect_ID"))

T14_UC <- T14_UC %>%  mutate(research.sv= case_when(d_265193023==972455046 ~ "Not Started",
                                                    d_265193023==615768760 ~ "Started",
                                                    d_265193023==231311385 ~ "Submitted"))
#T14__UC <- T14_UC %>% distinct(T14_UC$Connect_ID)

#17- by site
#test17 <- T14_UC %>%  filter( Site=="University of Chicago Medicine")
T14_UC$Collection_Location[is.na(T14_UC$Collection_Location)]="Null Collection Location"
T14_UC$Collection_Location <- factor(T14_UC$Collection_Location, levels = c('Ingalls Harvey', 'Orland Park', 'River East', 'South Loop', 'UC-DCAM', 'UCM Pop-Up', 'Null Collection Location'))

Res_Survey_status <- T14_UC %>% dplyr::select(Collection_Location, research.sv )  %>% 
  #arrange(factor(Collection_Location, levels = c('Ingalls Harvey', 'Orland Park', 'River East', 'South Loop', 'UC-DCAM', 'UCM Pop-Up', 'Null Collection Location	'))) %>%
  tbl_cross(
  row = Collection_Location,
  col = research.sv, 
  digits=c(0,1),
  percent = "row",
  label=list(Collection_Location ~ " ", research.sv ~ " "),
  # label=list(Collection_Location,="",
  #            research.sv = ""),
  missing="ifany") %>%
   

  #bold_labels() %>%
  #italicize_levels() %>%
  modify_header() %>%
  modify_caption("Table 6. Baseline Research Biospecimen Survey Status by Collection Location") %>%
  as_kable_extra(escape = FALSE, addtl_fmt = TRUE)

```








```{r Table16a16b, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}


## Table 19
# Baseline research biospecimen survey completion time from time of visit check-in
    ## added requirement: BioChk_Complete_v1r0 is not null instead of survey completed
      ## Jing's original code already does this!!! recrver1$BL_BioChk_Complete_v1r0 
time.sv_checkin <- research.survey  %>% select(checktmvisit) %>% #%>% filter(d_265193023==231311385)
  tbl_summary(
    label=checktmvisit~"Time from Research Biospecimen Survey Completion Time from Time of Visit Check-In",
    statistic = list(all_categorical() ~ "{n}  ({p}%)"),
              digits = all_categorical() ~ c(0, 2),
    missing_text="Missing"
  )
total <- as.numeric(nrow(research.survey)) #[which(research.survey$d_265193023==231311385),]
time.sv_checkin <- as.data.frame(tab1(research.survey$checktmvisit)) #[which(research.survey$d_265193023==231311385),]
time.sv_checkin <-time.sv_checkin %>% 
  mutate(cumulative.Freq = ifelse(trimws(rownames(time.sv_checkin))!="Total", cumsum(output.table.Frequency),output.table.Frequency),
         cumulative.Perc = round(100*cumulative.Freq/total,1))

check<-research.survey[which(is.na(research.survey$checktmvisit) & !is.na(research.survey$d_331584571_d_266600170_d_135591601)),   c("Connect_ID","d_265193023","d_222161762","d_822499427","d_331584571_d_266600170_d_840048338","tm_biocolsuv","checktmvisit")]
     #research.survey$d_265193023==231311385 & 


test17 <- research.survey %>%  filter(Site=="University of Chicago Medicine")

test17_b <- test17 %>%  filter(d_222161762<as.Date("2023-07-05") & (checktmvisit=="Greater than 72hrs (3 days)" | checktmvisit=="> 48 hrs to 72 hrs" | checktmvisit=="> 24 hrs to 48 hrs" | 
  checktmvisit=="> 12 hrs to 24 hrs" |checktmvisit=="> 3 hrs to 12 hrs" |checktmvisit=="0 hrs to 3 hrs" | checktmvisit=="Missing Time"))
test17_b$checktmvisit<- droplevels(test17_b$checktmvisit)
test17_a <- test17 %>%  filter(d_222161762>=as.Date("2023-07-05") & (checktmvisit=="Greater than 72hrs (3 days)" | checktmvisit=="> 48 hrs to 72 hrs" | checktmvisit=="> 24 hrs to 48 hrs" | 
  checktmvisit=="> 12 hrs to 24 hrs" |checktmvisit=="> 3 hrs to 12 hrs" |checktmvisit=="0 hrs to 3 hrs" | checktmvisit=="Missing Time"))
test17_a$checktmvisit<- droplevels(test17_a$checktmvisit) 

test17_b$Connect_ID <- as.numeric(test17_b$Connect_ID)
test17_a$Connect_ID <- as.numeric(test17_a$Connect_ID)
T14_UC$Connect_ID <- as.numeric(T14_UC$Connect_ID)

testing7b <- left_join(test17_b, T14_UC, by=c("Site", "research.sv", "Connect_ID"))
testing7a <- left_join(test17_a, T14_UC, by=c("Site", "research.sv", "Connect_ID"))


Table7A_combinedB <- testing7b %>% dplyr::select(Collection_Location, checktmvisit )  %>% tbl_cross(
    row = Collection_Location,
    col = checktmvisit,
    digits=c(0,2),
    percent = "row",
    label=list(Collection_Location ~ " ", checktmvisit ~ " "),
    missing="ifany") %>%
    #bold_labels() %>%
    #italicize_levels() %>% 
    modify_header() %>%
    modify_caption("Table 7a. Baseline Research Biospecimen Survey Completion Time from Visit Check-In Time (Pre-COVID-19 Questions Removal) ") %>%
    as_kable_extra(escape = FALSE, addtl_fmt = TRUE)



Table7B_combinedA <- testing7a %>% dplyr::select(Collection_Location, checktmvisit )  %>% tbl_cross(
    row = Collection_Location,
    col = checktmvisit,
    digits=c(0,2),
    percent = "row",
    label=list(Collection_Location ~ " ", checktmvisit ~ " "),
    missing="ifany") %>%
    #bold_labels() %>%
    #italicize_levels() %>% 
    modify_header() %>%
    modify_caption("Table 7b. Baseline Research Biospecimen Survey Completion Time from Visit Check-In Time (Post-COVID-19 Questions Removal) ") %>%
    as_kable_extra(escape = FALSE, addtl_fmt = TRUE)

```








```{r Table18a18b, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}




# T8UC <- biospeUC %>%  select(Collection_Location, Site)  
# T8AB_UC <- left_join(recrver1, T8UC, by= "Site")
# 
# test21r <- T8AB_UC %>%  filter(d_265193023==231311385 & !is.na(d_222161762) & !is.na(d_822499427)) 
# test21r <-  test21r %>% mutate(ctime = as.numeric(difftime(as.POSIXct(ymd_hms(d_222161762)),as.POSIXct(ymd_hms(d_822499427)),units="mins")))
# test21rb <-  test21r %>%  filter(d_222161762<as.Date("2023-07-05") & ctime>0)
# test21ra <-  test21r %>%  filter(d_222161762>as.Date("2023-07-05"))
# 
# test21rb$Collection_Location <- droplevels(test21rb$Collection_Location)
# test21ra$Collection_Location <- droplevels(test21ra$Collection_Location)


test8 <- research.survey %>%  filter(Site=="University of Chicago Medicine" & d_265193023==231311385 & !is.na(d_222161762) & !is.na(d_822499427))
# 
# test8_b <- test8 %>%  filter(d_222161762<as.Date("2023-07-05") & (checktmvisit=="Greater than 72hrs (3 days)" | checktmvisit=="> 48 hrs to 72 hrs" | checktmvisit=="> 24 hrs to 48 hrs" |
#   checktmvisit=="> 12 hrs to 24 hrs" |checktmvisit=="> 3 hrs to 12 hrs" |checktmvisit=="0 hrs to 3 hrs" | checktmvisit=="Missing Time"))
# test8_b$checktmvisit<- droplevels(test8_b$checktmvisit)
# test8_a <- test8 %>%  filter(d_222161762>=as.Date("2023-07-05") & (checktmvisit=="Greater than 72hrs (3 days)" | checktmvisit=="> 48 hrs to 72 hrs" | checktmvisit=="> 24 hrs to 48 hrs" |
#   checktmvisit=="> 12 hrs to 24 hrs" |checktmvisit=="> 3 hrs to 12 hrs" |checktmvisit=="0 hrs to 3 hrs" | checktmvisit=="Missing Time"))
# test8_a$checktmvisit<- droplevels(test8_a$checktmvisit)
# 
# test8_b$Connect_ID <- as.numeric(test8_b$Connect_ID)
# test8_a$Connect_ID <- as.numeric(test8_a$Connect_ID)
# T14_UC$Connect_ID <- as.numeric(T14_UC$Connect_ID)

testing8 <- merge(test8, T14_UC, by=c("Site", "research.sv", "Connect_ID"))

#test21rb <- testing7b %>%  filter(d_265193023==231311385 & !is.na(d_222161762) & !is.na(d_822499427)) 
test8_all <-  testing8 %>% mutate(ctime = as.numeric(difftime(as.POSIXct(ymd_hms(d_222161762)),as.POSIXct(ymd_hms(d_822499427)),units="mins")))
test21r__b <-  test8_all %>%  filter(d_222161762<as.Date("2023-07-05") & ctime>0)
test21r__a <-  test8_all %>%  filter(d_222161762>=as.Date("2023-07-05") & ctime>0)

# test21ra <- testing7a %>%  filter(d_265193023==231311385 & !is.na(d_222161762) & !is.na(d_822499427)) 
# test21r_a <-  test21r %>% mutate(ctime = as.numeric(difftime(as.POSIXct(ymd_hms(d_222161762)),as.POSIXct(ymd_hms(d_822499427)),units="mins")))
# test21r__a <-  test21r_a %>%  filter(d_222161762<as.Date("2023-07-05") & ctime>0)

#test21ra <-  test21r %>%  filter(d_222161762>=as.Date("2023-07-05"))



Table8_Before = test21r__b %>% group_by(Collection_Location) %>% 
  dplyr::summarize(#'Number of Collection Visits'=n(),
                   Min = min(ctime),
                   Q1 = quantile(ctime, 0.25),
                   Median = median(ctime),
                   Mean = mean(ctime),
                   SD=sd(ctime),
                   Q3 = quantile(ctime, 0.75),
                   Perc.95= quantile(ctime, 0.95),
                   Max = max(ctime))


Table8_After = test21r__a %>% group_by(Collection_Location) %>% 
  dplyr::summarize(#'Number of Collection Visits'=n(),
                   Min = min(ctime),
                   Q1 = quantile(ctime, 0.25),
                   Median = median(ctime),
                   Mean = mean(ctime),
                   SD=sd(ctime),
                   Q3 = quantile(ctime, 0.75),
                   Perc.95= quantile(ctime, 0.95),
                   Max = max(ctime))






statics_biock <- tapply(as.numeric(testing8$time_biochk),testing8$biochk_outlier,summary)
tab32a <- bind_rows(statics_biock)
##tab32a$`Outlier Present?` <- ifelse(rownames(statics_biock)==1,"no outliers","outlier")   ## I commented out--- wasn't running for me 
research.vt.length <- testing8 %>%  mutate(time=as.numeric(time_biochk)) 
#research.vt.length = research.vt.length %>%  filter(8<time) # & time<500) 
research.vt.length9 = research.vt.length %>%group_by(Collection_Location) %>% #biochk_outlier,
  dplyr::summarize(#'Number of Collection Visits'=n(),
                   Min = min(time,na.rm = TRUE),
                   Q1 = quantile(time, 0.25,na.rm = TRUE),
                   Median = median(time,na.rm = TRUE),
                   Mean = mean(time,na.rm = TRUE),
                   SD=sd(time,na.rm = TRUE),
                   Q3 = quantile(time, 0.75,na.rm = TRUE),
                   Perc.90= quantile(time, 0.90,na.rm = TRUE),
                   Perc.95= quantile(time, 0.95,na.rm = TRUE),
                   Perc.98= quantile(time, 0.98,na.rm = TRUE),
                   Max = max(time,na.rm = TRUE))
```



```{r KnitrTables1_4, eval=TRUE,echo=FALSE, ,results='asis'}
options(knitr.table.format = "latex")
options(kableExtra.auto_format = FALSE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 

### AD HOC UC TABLES

coll_completenessR %>% kable_styling(latex_options = "scale_down")

knitr::kable(bldcol_research_UC1, col.names=c("Collection Location","All Blood Tubes Collected","Partial Blood Tubes Collected","No Blood Tubes Collected","Total"), caption='Table 2. Blood Draw Completeness by Collection Location ', row.names=FALSE, align=c("l","c","c","c","c"), booktabs = TRUE) %>% kable_styling(latex_options = "scale_down")

#knitr::kable(tbl_3_ncol, caption='Table 3. Research Blood Tubes Not Collected Among Partial Blood Collections by Collection Location', row.names=FALSE,align=c("l","c","c","c","c","c","c","c"), booktabs = TRUE)  %>% kable_styling(latex_options = "scale_down") %>% landscape() 
tbl_3_ncol

research.notcolnotes_site  ##missing a site or 0, 0% unneeded
```

\FloatBarrier
```{r KnitrTables5, eval=TRUE,echo=FALSE, ,results='asis'}
discard.site5 %>% kable_styling(latex_options = "HOLD_position")
```

```{r KnitrTables6_9, eval=TRUE,echo=FALSE, ,results='asis'}


Res_Survey_status  ## this set up may be the easiest for all of these tables


T7a <- Table7A_combinedB %>% kable_styling(latex_options = "scale_down")
add_footnote(T7a, "Note: The COVID-19 survey questions were separated from the Biospecimen Survey on July 5, 2023.", notation = "none")

T7b <- Table7B_combinedA %>% kable_styling(latex_options = "scale_down")
add_footnote(T7b, "Note: The COVID-19 survey questions were separated from the Biospecimen Survey on July 5, 2023.", notation = "none")

#Table8_Before
#Table8_After

knitr::kable(Table8_Before,caption='Table 8a. Baseline Research Biospecimen Survey Completion Length (in Minutes) by Collection Location (Pre-COVID-19 Questions Removal) ',row.names=FALSE, align=c("l","c","c","c","c","c","c","c","c","c","c","c"),digits=1, booktabs = TRUE)%>% kable_styling(latex_options = "scale_down")

knitr::kable(Table8_After,caption='Table 8b. Baseline Research Biospecimen Survey Completion Length (in Minutes) by Collection Location (Post-COVID-19 Questions Removal) ',row.names=FALSE, align=c("l","c","c","c","c","c","c","c","c","c","c","c"),digits=1, booktabs = TRUE)%>% kable_styling(latex_options = "scale_down")


research.vt.length9

knitr::kable(research.vt.length9,caption='Table 9. Baseline Research Biospecimen Collection Visit Length (in Minutes) by Collection Location ',row.names=FALSE, align=c("l","c","c","c","c","c","c","c","c","c"),digits=1, booktabs = TRUE)%>% kable_styling(latex_options = "scale_down") 

```




