---
title: "Blood, Urine Survey Summary Statistics"
header-includes:  
    \usepackage[labelformat=empty]{caption}
    \usepackage{placeins}
    \usepackage{booktabs}



output:
  pdf_document:
    extra_dependencies: ["float"]
    toc: true
    toc_depth: 2
    keep_tex: yes
    fig_width: 7
    fig_height: 5
    fig_caption: true
    df_print: paged
---



```{r libraries, include=FALSE}

#old.packages()
#update.packages()

library(rlang)
library(bigrquery)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(scales)
library(gt)
#install(tinytex)
library(tinytex)
library(tidyr)
library(stringr)
library(lubridate)
library(knitr)
library(kableExtra)

options(tinytex.verbose = TRUE)

bq_auth()
```

```{r merge, include=FALSE}
project = "nih-nci-dceg-connect-prod-6d04"
billing= "nih-nci-dceg-connect-prod-6d04"
biospec <- "SELECT * FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.clinicalBioSurvey_v1_JP`    where Connect_ID is not null"
parts <- "SELECT Connect_ID, token, D_512820379, D_471593703, state_d_934298480, D_230663853,
D_335767902, D_982402227, D_919254129, D_699625233, D_564964481, D_795827569, D_544150384,
D_371067537, D_430551721, D_821247024, D_914594314,  state_d_725929722, 
D_949302066 , D_517311251, D_205553981, D_117249500, d_265193023, d_331584571_d_266600170_d_343048998, 
d_331584571_d_266600170_d_840048338,  d_534669573, d_764863765, d_827220437, d_253883960 FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.participants_JP` 
where Connect_ID IS NOT NULL and d_253883960='231311385'"
specimenBU <- "SELECT Connect_ID, d_556788178 FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.biospecimen_JP` where Connect_ID is not null"


biospec_table <- bq_project_query(project, biospec)
parts_table <- bq_project_query(project, parts)
specimenBU_table <- bq_project_query(project, specimenBU)


biospec_data <- bq_table_download(biospec_table, bigint = "integer64", n_max = Inf, page_size = 1000)
parts_data <- bq_table_download(parts_table, bigint = "integer64", n_max = Inf, page_size = 1000)
specimenBU_data <- bq_table_download(specimenBU_table, bigint = "integer64")

parts_data$Connect_ID <- as.numeric(parts_data$Connect_ID) 
biospec_data$Connect_ID <- as.numeric(biospec_data$Connect_ID) 
specimenBU_data$Connect_ID <- as.numeric(specimenBU_data$Connect_ID) 

bisp= left_join(biospec_data, parts_data, by="Connect_ID")  %>%  left_join(specimenBU_data, by="Connect_ID") 
#dim(bisp)


#Has a recruitment flag
bisp <- bisp %>% filter(D_512820379==486306141 | D_512820379==854703046)
#cat("Has a recruitment flag:", dim(bisp)[[1]])

#User consent submitted -- already included in verified?
#bisp <- bisp %>% filter(D_919254129==353358909)
#cat("User consent submitted:", dim(bisp)[[1]])

#User profile submitted -- already included in verified?
#bisp <- bisp %>% filter(D_699625233==353358909)
#cat("User profile submitted:", dim(bisp)[[1]])

#Verified by site
bisp <- bisp %>% filter(D_821247024==197316935)
#cat("Verified by site:", dim(bisp)[[1]])

#Check in time not null and Check out time not null, filtered in SQL query

#BU completed
BU <- bisp %>% filter(d_253883960==231311385)
cat("Particiapnts with Blood, Urine Survey Completed: ", dim(BU)[[1]])
#dim(BU)

BU_tib <- as_tibble(BU)
#dim(BU_tib)

knitr::opts_chunk$set(comment = NA)


```


```{r functions, include=FALSE}
##FUNCTIONS

BU_dict <- list("104430631"="No", "353358909"="Yes", "178420302"="Do not Know", "536341288"="Female", "576796184"="Intersex or Other", "654207589"="Male",
                 "110092955"="The same day", "952212668"="The day before", "330461666"="More than a day before", "974230748"="Yes, in the past day",
                 "936042740"="Yes, in the past two days", "731141335"="Yes, in the past week", "591670915"="Yes, in the past month", "111520945"="Not at all",
                 "548628123"="A little bit", "567908725"="Somewhat", "760969884"="Quite a bit", "464631026"="Very Much", "707601969"="Yes, another",
                 "232063618"="Less than 1 month", "948148236"="Between 1 and 3 months", "692824372"="More than 3 months", "224099497"="Yes, mostly",
                 "770236544"="No, I never experienced this", "931688701"="Yes, I am experiencing this now", "586272115"="Yes, I experienced this in the past",
                 "661871565"="Moderna", "657978450"="Pfizer", "411943417"="Johnson & Johnson", "113838601"="AstraZeneca","503154121"="Novavax" ,
                "807835037"="Other", 
                 "670680466"="Excellent", "927477599"="Very Good", "719933364"="Good", "131550264"="Fair", "138752522"="Poor", "648960871"="Never",
                 "693256778"="Less than Once Per Week", "735330419"="1-2 Times per Week", "138332277"="3-5 Times per Week", "858624942"="Once per Day", 
                 "85067541"="2-3 Times per Day", "317567178"="In the last month", "891558680"="In the last 1-6 months", "796081734"="In the past 6-12 months",
                 "752219885"="Over a year, in the Last Two Years", "314487612"="More than 2 years", "666365344"="Within the Last 24 Hours", 
                 "735136116"="In the Past 2-7 Days", "382679079"="In the last 2-4 weeks", "830677489"="More than 4 Weeks Ago", "349122068"="One",
                 "194129782"="Two to Four", "922737557"="Five to Nine", "945387130"="10+", "383505459"="More than 1 but Don't Remember", "832322940"="Don't Know",
                 "317811347"="Don't Know", "850675416"="Two or more times per day")

gt_functBU <- function(CID, Title){  
  CID_SYM <- rlang::ensym(CID)
  dt_select <- BU_tib %>%  select(Connect_ID, !!CID_SYM)
  gt_yn <- dt_select  %>% dplyr::group_by(!!CID_SYM) %>% dplyr::summarize(n=n(), percentage=100*n/nrow(.)) %>% dplyr::ungroup() %>% dplyr::mutate(answer=dplyr::recode(!!CID_SYM, !!!BU_dict)) %>% replace_na(list(answer="Skipped this Question")) %>%  select(answer, n, percentage)
  gt_yn %>%  gt::gt()  %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md(Title)) %>% 
  cols_label(answer = md("**Answer**"),  n = md("**N**"),  percentage = md("**%**")) %>% 
grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T)) %>% 
  tab_options(
      stub.font.weight = "bold"
    ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = answer,
    )
  ) 
}

menstrual_funct <- function(CID, Title){  
  CID_SYM <- rlang::ensym(CID)
  dt_select <- BU_tib %>%  select(Connect_ID, !!CID_SYM) %>%  filter(BU_tib$D_522008539==536341288)
  gt_yn <- dt_select  %>% dplyr::group_by(!!CID_SYM) %>% dplyr::summarize(n=n(), percentage=100*n/nrow(.)) %>% dplyr::ungroup()  %>%  mutate(answer=dplyr::recode(!!CID_SYM, !!!BU_dict)) %>% replace_na(list(answer="Skipped this Question")) %>%  select(answer, n, percentage)
  
  gt_yn %>%  gt::gt()  %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md(Title)) %>% 
  cols_label(answer = md("**Answer**"),  n = md("**N**"),  percentage = md("**%**")) %>% 
grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T)) %>%
  tab_options(
      stub.font.weight = "bold"
    ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = answer,
    )
  )
}


covid_once_funct <- function(CID, Title){  
  CID_SYM <- rlang::ensym(CID)
  dt_select <- BU_tib %>%  select(Connect_ID, !!CID_SYM) %>%  filter(BU_tib$d_764863765<as.Date("2023-07-05") & (as.numeric(BU_tib$D_860011428)>=1 | BU_tib$D_494226443=="353358909"))
  gt_yn <- dt_select  %>% dplyr::group_by(!!CID_SYM) %>% dplyr::summarize(n=n(), percentage=100*n/nrow(.)) %>% dplyr::ungroup()  %>%  mutate(answer=dplyr::recode(!!CID_SYM, !!!BU_dict)) %>% replace_na(list(answer="Skipped this Question")) %>%  select(answer, n, percentage)
  gt_yn %>%  gt::gt()  %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md(Title)) %>% 
  cols_label(answer = md("**Answer**"),  n = md("**N**"),  percentage = md("**%**")) %>% 
  grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T)) %>%
  tab_options(
      stub.font.weight = "bold"
    ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = answer,
    )
  ) 
}

covid_twice_funct <- function(CID, Title){  
  CID_SYM <- rlang::ensym(CID)
  dt_select <- BU_tib %>%  select(Connect_ID, !!CID_SYM) %>%  filter(BU_tib$d_764863765<as.Date("2023-07-05") & (as.numeric(BU_tib$D_860011428)>=2))
  gt_yn <- dt_select  %>% dplyr::group_by(!!CID_SYM) %>% dplyr::summarize(n=n(), percentage=100*n/nrow(.)) %>% dplyr::ungroup()  %>%  mutate(answer=dplyr::recode(!!CID_SYM, !!!BU_dict)) %>% replace_na(list(answer="Skipped this Question")) %>%  select(answer, n, percentage)
  gt_yn %>%  gt::gt()  %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md(Title)) %>% 
  cols_label(answer = md("**Answer**"),  n = md("**N**"),   percentage = md("**%**")) %>% 
  grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T)) %>%
  tab_options(
      stub.font.weight = "bold"
    ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = answer,
    )
  ) 
}

covid_thrice_funct <- function(CID, Title){  
  CID_SYM <- rlang::ensym(CID)
  dt_select <- BU_tib %>%  select(Connect_ID, !!CID_SYM) %>%  filter(BU_tib$d_764863765<as.Date("2023-07-05") & (as.numeric(BU_tib$D_860011428)>=3))
  gt_yn <- dt_select  %>% dplyr::group_by(!!CID_SYM) %>% dplyr::summarize(n=n(), percentage=100*n/nrow(.)) %>% dplyr::ungroup() %>%  mutate(answer=dplyr::recode(!!CID_SYM, !!!BU_dict)) %>% replace_na(list(answer="Skipped this Question")) %>%  select(answer, n, percentage)
  gt_yn %>%  gt::gt()  %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md(Title)) %>% 
  cols_label(answer = md("**Answer**"),  n = md("**N**"),   percentage = md("**%**")) %>% 
  grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T)) %>%
  tab_options(
      stub.font.weight = "bold"
    ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = answer,
    )
  ) 
}


#One skip logic (previous response)
one_skip_funct <- function(CID, Title, Previous_CID, Previous_Answer){  
  CID_SYM <- rlang::ensym(CID)
  CID_SYM_P <- rlang::ensym(Previous_CID)
  dt_select <- BU_tib %>%  filter(!!CID_SYM_P==Previous_Answer) %>%  select(Connect_ID, !!CID_SYM) 
  gt_yn <- dt_select  %>% dplyr::group_by(!!CID_SYM) %>% dplyr::summarize(n=n(), percentage=100*n/nrow(.)) %>% dplyr::ungroup() %>% dplyr::mutate(answer=dplyr::recode(!!CID_SYM, !!!BU_dict)) %>% replace_na(list(answer="Skipped this Question")) %>%  dplyr::select(answer, n, percentage)
  gt_yn %>%  gt::gt()  %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md(Title)) %>% 
  cols_label(answer = md("**Answer**"),  n = md("**N**"),  percentage = md("**%**")) %>% 
  grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T)) %>%
  tab_options(
      stub.font.weight = "bold"
    ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = answer,
    )
  ) 
}


#Two skip logic (previous response)
#did have covid questions 
two_skip_funct <- function(CID, Title, Previous_CID, Previous_Answer, Previous_CID2, Previous_Answer2){  
  CID_SYM <- rlang::ensym(CID)
  CID_SYM_P <- rlang::ensym(Previous_CID)
  CID_SYM_P2 <- rlang::ensym(Previous_CID2)
  dt_select2 <- BU_tib %>%  filter( !!CID_SYM_P==Previous_Answer | !!CID_SYM_P2==Previous_Answer2) %>% 
    select(Connect_ID, !!CID_SYM) 
  gt2_yn <- dt_select2  %>% dplyr::group_by(!!CID_SYM) %>% dplyr::summarize(n=n(), percentage=100*n/nrow(.)) %>% dplyr::ungroup() %>% dplyr::mutate(answer=recode(!!CID_SYM, !!!BU_dict)) %>% replace_na(list(answer="Skipped this Question")) %>%  dplyr::select(answer, n, percentage)
  gt2_yn %>%  gt::gt()  %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md(Title)) %>% 
  cols_label(answer = md("**Answer**"),  n = md("**N**"),  percentage = md("**%**")) %>% 
  grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T)) %>%
  tab_options(
      stub.font.weight = "bold"
    ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = answer,
    )
  ) 
}




#Histogram Function
hist_funct <- function(CID,Title, Xlab, Ylab) {
  CID_SYM <- rlang::ensym(CID)
  BU %>% dplyr::mutate(!!CID_SYM:=as.numeric(!!CID_SYM)) %>%
    filter(!is.na(!!CID_SYM)) %>% ggplot(aes(x=!!CID_SYM))+
     xlab(Xlab) + ylab(Ylab) + geom_histogram()+  ggtitle(Title)+
    geom_histogram(color="black")+ scale_y_continuous(breaks=pretty_breaks()) +
    geom_vline(aes(xintercept=mean(!!CID_SYM, na.rm=T)), colour="#2973A5", linetype="solid")
  
}

```


\newpage

```{r Tables1_3, warning=FALSE, echo=FALSE,  message=FALSE}


#NOTE: NO PARTICIAPNT STARTED THIS SURVEY BEFORE 11/30/22 SO NO VERSION 1 VARIABLES HAVE DATA, ONLY VERSION 2



#SEX
gt_functBU(D_522008539, "SEX: Biological Sex at Birth")



#SYMPTDAY

dt_SYMPTDAY= BU_tib %>%  mutate(multb2 = ifelse(D_470484596_D_756774083==1, 1, 0) + ifelse(D_470484596_D_235386560==1, 1, 0) + ifelse(D_470484596_D_955154600==1, 1, 0) + 
                                             ifelse(D_470484596_D_811126581==1, 1, 0) + ifelse(D_470484596_D_406943303==1, 1, 0)) 



which_sympt= dt_SYMPTDAY %>%  mutate(symptom= case_when(as.numeric(multb2)>1 ~ "Multiple Symptoms",
                                                        D_470484596_D_756774083==1 ~ "Cough",
                                                        D_470484596_D_235386560==1 ~ "Diarrhea",
                                                        D_470484596_D_955154600==1 ~ "Nasal Congestion",
                                                        D_470484596_D_811126581==1 ~ "Sick to Your Stomach or Vomitting",
                                                        D_470484596_D_406943303==1 ~ "Fever",
                                                        D_470484596_D_535003378==1 ~ "None of these",
                                                        TRUE   ~ "Skipped this Question"))

which_sympt$symptom <- factor(which_sympt$symptom,levels=c("Multiple Symptoms",  "Cough", "Diarrhea", "Nasal Congestion", "Sick to Your Stomach or Vomitting", "Fever", "None of these", "Skipped this Question"))


dt_SYMPTDAY_summary <- which_sympt %>% dplyr::group_by(symptom) %>%  dplyr::summarize(n=n(), percentage=round(100*n/nrow(.), digits=2)) %>%  dplyr::select(symptom, n, percentage)



dt_SYMPTDAY_summary  %>%  gt::gt() %>%
  fmt_number(columns = "percentage", decimals = 1) %>%
  tab_header(title = md("Table 2: Symptoms in the 24 hours Prior to Sample Donation")) %>%
  cols_label(symptom = md("**Answer**"), n = md("**N**"), percentage = md("**%**")) %>%
  grand_summary_rows(columns=c(n, percentage),
                     fns = ~sum(.,na.rm = T)) %>%
  tab_options(stub.font.weight = "bold") %>%
  tab_style(style = list(cell_text(weight = "bold")),
            locations = cells_body(columns = symptom)) 


#EATDRINKBEFORE
BU_tib$D_867307558 <- factor(BU_tib$D_867307558,levels=c(110092955, 952212668, 330461666, "Skipped this Question"))
gt_functBU(D_867307558, "Table 3: When Last Food or Beverage Consumed")



```




```{r merge2, include=FALSE, warning=FALSE}
avgP_ccc <-  "SELECT  Connect_ID, d_173836415_d_266600170_d_448660695, d_265193023, d_827220437 FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.participants_JP` 
where d_265193023='231311385' and d_173836415_d_266600170_d_448660695 is not null "
avgB_ccc <-  "SELECT Connect_ID, D_191057574, D_191057574_V2, D_867307558 FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.bioSurvey_v1_JP` 
where (D_191057574 is not null OR D_191057574_V2 is not null) "


avgP_table_cc <- bq_project_query(project, avgP_ccc)
avgB_table_cc <- bq_project_query(project, avgB_ccc)

avgP <- bq_table_download(avgP_table_cc, bigint = "integer64")
avgB <- bq_table_download(avgB_table_cc, bigint = "integer64")

avgP$Connect_ID <- as.numeric(avgP$Connect_ID)
avgB$Connect_ID <- as.numeric(avgB$Connect_ID)

average <- left_join(avgP, avgB , by="Connect_ID")

avg <- as_tibble(average)

```
```{r, echo=FALSE, warning=FALSE, message=FALSE}


avg_s <- avg %>%  filter((d_827220437==531629870 |  d_827220437==548392715 | d_827220437==303349821 | d_827220437==657167265 | d_827220437==809703864) & !is.na(D_867307558))
#avg$Site<- droplevels(avg$Site)

#(D_867307558==110092955 ~ "Same day",D_867307558==952212668 ~ "The Day before"))

avg_coll2 <- avg_s %>%  mutate(D_191057574V=case_when(!is.na(D_191057574_V2) ~ D_191057574_V2,
                                                      !is.na(D_191057574) ~ D_191057574))
#avg_coll3 <- avg_s %>%  mutate(D_191057574V=ifelse(!is.na(D_191057574), D_191057574, D_191057574_V2))


#avg_s$D_191057574 <- paste0("2023-", avg_s$D_191057574)
#avg_s$D_191057574 <- as.Date(avg_s$D_191057574, format="MM-DD")
avg_coll2$MW_date <- as.Date(avg_coll2$d_173836415_d_266600170_d_448660695) 
#class(avg_coll2$MW_date) 
avg_coll2$MW_dayb4 <- avg_coll2$MW_date - 1
#avg_coll2$MW_dayb4 <- paste0((avg_coll2$MW_date - 1), str_sub(avg_coll2$d_173836415_d_266600170_d_448660695,11,24))
#avg_coll2$MW_dayb4 <- avg_coll2$d_173836415_d_266600170_d_448660695-1

avg_coll2 <- avg_coll2 %>%  mutate(eat= case_when(D_867307558==110092955 ~ paste0(str_sub(avg_coll2$d_173836415_d_266600170_d_448660695,1,11), avg_coll2$D_191057574V, ":00.000Z"),
                                                  D_867307558==952212668 ~ paste0(avg_coll2$MW_dayb4, avg_coll2$D_191057574V, ":00.000Z" )))



avg_coll <- avg_coll2 %>%  mutate(time = as.numeric(difftime(as.POSIXct(ymd_hms(d_173836415_d_266600170_d_448660695)),as.POSIXct(ymd_hms(eat)),units="hours")))
                                 # Site = case_when(d_827220437==531629870 ~ "HealthPartners",
                                 #                  d_827220437==548392715 ~ "Henry Ford Health System",
                                 #                  d_827220437==303349821 ~ "Marshfield Clinic Health System",
                                 #                  d_827220437==657167265 ~ "Sanford Health",
                                 #                  d_827220437==809703864 ~ "University of Chicago Medicine"))

avg_coll <- avg_coll %>%  mutate(MW = case_when( as.numeric(abs(abs(time))) >72 ~">72hrs",
                                            72 >= as.numeric(abs(time)) & as.numeric(abs(time)) > 48 ~ "> 48 hrs to 72 hrs",
                                            48 >= as.numeric(abs(time)) & as.numeric(abs(time)) > 24 ~ "> 24 hrs to 48 hrs",   
                                            24 >= as.numeric(abs(time)) & as.numeric(abs(time)) > 12 ~ "> 12 hrs to 24 hrs",
                                            12 >= as.numeric(abs(time)) & as.numeric(abs(time)) > 3 ~ "> 3 hrs to 12 hrs",  
                                            3 >= as.numeric(abs(time)) & as.numeric(abs(time)) >= 0 ~ "0 hrs to 3 hrs",
                                            TRUE ~ "Missing Time"),
                                 Site=case_when(d_827220437==531629870 ~ "HealthPartners",
                                                 d_827220437==548392715 ~ "Henry Ford Health System",
                                                 d_827220437==303349821 ~ "Marshfield Clinical Health System",
                                                 d_827220437==657167265 ~ "Sanford Health",
                                                 d_827220437==809703864 ~ "University of Chicago Medicine",
                                                d_827220437==125001209 ~ "Kaiser Permanente Colorado",
                                                 d_827220437==327912200 ~ "Kaiser Permanente Georgia",
                                                 d_827220437==300267574 ~ "Kaiser Permanente Hawaii",
                                                 d_827220437==452412599 ~ "Kaiser Permanente Northwest"))
avg_coll$MW <- factor(avg_coll$MW, levels= c( "Missing Time", "0 hrs to 3 hrs", "> 3 hrs to 12 hrs", "> 12 hrs to 24 hrs", "> 24 hrs to 48 hrs", "> 48 hrs to 72 hrs", ">72hrs"))


MW_time1 <- avg_coll %>% dplyr::group_by(Site, MW) %>%  summarize(n=n(), percentage=100*n/nrow(.)) %>%  select(Site,  MW, n, percentage) # %>% dplyr::ungroup() #------ why is it saying MW is not a column????
#MW_time <- MW_time1 %>%  sort_by(Site) 
  
MW_time1 %>%  gt::gt()  %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md("Table 4. Time from Last Meal to Time of Mouthwash Collection")) %>% 
  cols_label(n= md("**Number**"), MW = md(" "), percentage = md("**Percent**")) %>%  
  grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T))


```

\FloatBarrier

```{r RemovedTables, warning=FALSE, echo=FALSE,  message=FALSE}

#EATDRINKTIME
EATDRINKTIME_V1=BU %>% filter(!is.na(D_191057574) & (D_867307558== "952212668"| D_867307558=="330461666")) %>% ggplot(aes(x=D_191057574))+ ylab("Count") + 
  xlab("Time (Military Time)") +geom_bar()+  ggtitle("EATDRINKTIME(V1): Time Food or Beverage Last Consumed") +theme(axis.text.x = element_text(angle = 90))

EATDRINKTIME_V2=BU %>% filter(!is.na(D_191057574_V2) & (D_867307558== "952212668"| D_867307558=="330461666")) %>% ggplot(aes(x=D_191057574_V2))+ ylab("Count") + 
  xlab("Time (Military Time)") +geom_bar()+  ggtitle("EATDRINKTIME(V2): Time Food or Beverage Last Consumed") +theme(axis.text.x = element_text(angle = 90))
#grid.arrange(EATDRINKTIME_V1, EATDRINKTIME_V2, nrow=2)


#SLEEPTIME
SLEEPTIME_V1=BU %>% filter(!is.na(D_299417266)) %>% ggplot(aes(x=D_299417266))+ ylab("Count") + 
  xlab("Time (Military Time)") +geom_bar()+  ggtitle("SLEEPTIME(V1): Bedtime the Night Before Donation") +theme(axis.text.x = element_text(angle = 90))

SLEEPTIME_V2=BU %>% filter(!is.na(D_299417266_V2)) %>% ggplot(aes(x=D_299417266_V2))+ ylab("Count") + 
  xlab("Time (Military Time)") +geom_bar()+  ggtitle("SLEEPTIME(V2): Bedtime the Night Before Donation") +theme(axis.text.x = element_text(angle = 90))
#grid.arrange(SLEEPTIME_V1, SLEEPTIME_V2, nrow=2)




BU_sig <- BU_tib %>%  filter(!is.na(D_299417266_V2)) %>%  
  mutate(sleep = paste0(str_sub(d_556788178,1,11), str_sub(D_299417266_V2,1,5), str_sub(d_556788178,17,24)),
         slptime= paste0(as.Date(sleep) -1, "T", str_sub(sleep,12,24)), #question is time you went to bed the night BEFORE, so have to subtract a day 
         time_sleep = difftime(as.POSIXct(ymd_hms(d_556788178)), as.POSIXct(ymd_hms(slptime)),units="hours"),
         time=as.numeric(time_sleep)) 


BU_SLEEP = BU_sig %>% #group_by(Site) %>% #biochk_outlier,
  dplyr::summarize('Number of Participants'=n(),
                   Min = min(time,na.rm = TRUE),
                   Q1 = quantile(time, 0.25,na.rm = TRUE),
                   Median = median(time,na.rm = TRUE),
                   Mean = mean(time,na.rm = TRUE),
                   SD=sd(time,na.rm = TRUE),
                   Q3 = quantile(time, 0.75,na.rm = TRUE),
                   Max = max(time,na.rm = TRUE))
bm_wake <- knitr::kable(BU_SLEEP,caption='Table 5: Hours Participant Fell Asleep Before Sample Donation',digits=1, booktabs = TRUE)%>% kable_styling(latex_options = "scale_down") #%>% landscape()
add_footnote(bm_wake,"Note: Those who did not answer this question are removed from the Number of Participants in order to calculate difference in existing times.", notation = "none") #and greater than 500 minutes 




#WAKETIME
WAKETIME_V1=BU %>% filter(!is.na(D_689861450)) %>% ggplot(aes(x=D_689861450))+ ylab("Count") + 
  xlab("Time (Military Time)") +geom_bar()+  ggtitle("WAKETIME(V1): Wake-up Time the Day of Donation") +theme(axis.text.x = element_text(angle = 90))

WAKETIME_V2=BU %>% filter(!is.na(D_689861450_V2)) %>% ggplot(aes(x=D_689861450_V2))+ ylab("Count") + 
  xlab("Time (Military Time)") +geom_bar()+  ggtitle("WAKETIME(V2): Wake-up Time the Day of Donation") +theme(axis.text.x = element_text(angle = 90))
#grid.arrange(WAKETIME_V1, WAKETIME_V2, nrow=2)




BU_sig <- BU_tib %>%  filter(!is.na(D_689861450_V2)) %>%  
  mutate(wake2 = paste0(str_sub(d_556788178,1,11), str_sub(D_689861450_V2,1,5), str_sub(d_556788178,17,24)),
         time_biochk2 = difftime(as.POSIXct(ymd_hms(d_556788178)), as.POSIXct(ymd_hms(wake2)),units="hours"),
         time2=as.numeric(time_biochk2)) 


BU_WAKE = BU_sig %>% #group_by(Site) %>% #biochk_outlier,
  dplyr::summarize('Number of Participants'=n(),
                   Min = min(time2,na.rm = TRUE),
                   Q1 = quantile(time2, 0.25,na.rm = TRUE),
                   Median = median(time2,na.rm = TRUE),
                   Mean = mean(time2,na.rm = TRUE),
                   SD=sd(time2,na.rm = TRUE),
                   Q3 = quantile(time2, 0.75,na.rm = TRUE),
                   Max = max(time2,na.rm = TRUE))
bm_wake <- knitr::kable(BU_WAKE,caption='Table 6: Hours Awakened Before Sample Donation',digits=1, booktabs = TRUE)%>% kable_styling(latex_options = "scale_down") #%>% landscape()
add_footnote(bm_wake,"Note: Those who did not answer this question are removed from the Number of Participants in order to calculate difference in existing times.", notation = "none") #and greater than 500 minutes 




```

\newpage

# Medications
```{r Meds, warning=FALSE, echo=FALSE,  message=FALSE}
BU_tib$D_487532606_D_619765650 <- factor(BU_tib$D_487532606_D_619765650,levels=c(104430631, 974230748, 936042740, 731141335, 591670915, "Skipped this Question"))
BU_tib$D_487532606_D_520755310 <- factor(BU_tib$D_487532606_D_520755310,levels=c(104430631, 974230748, 936042740, 731141335, 591670915, "Skipped this Question"))
BU_tib$D_487532606_D_839329467 <- factor(BU_tib$D_487532606_D_839329467,levels=c(104430631, 974230748, 936042740, 731141335, 591670915, "Skipped this Question"))

gt_functBU(D_487532606_D_619765650, "TYLENOL: Medication Taken, if so, Last Time Taken")

gt_functBU(D_487532606_D_520755310, "NSAIDS: Medication Taken, if so, Last Time Taken")

gt_functBU(D_487532606_D_839329467, "Acid Reducers: Medication Taken, if so, Last Time Taken")


```

\newpage

# Reproductive Health 
```{r ReproductiveHealth, warning=FALSE, echo=FALSE,  message=FALSE}

#MENSTPRD
menstrual_funct(D_380603392, "MENSTPRD: Had Menstrual Period in the Last 12 Months")


#MENST60
one_skip_funct(D_112151599, "MENST60: Had Menstrual Period in the Last 60 Days", D_380603392, "353358909") 



#MENSTART
BU_tibM <- BU_tib %>%  filter(!is.na(BU_tib$D_644459734) & BU_tib$D_112151599=="353358909")
str_sub(BU_tibM$D_644459734,1,4)[str_sub(BU_tibM$D_644459734,1,4)=="0024"] = "2024"
BU_tibM$Mdate <- as.Date(BU_tibM$D_644459734)

BU_TimeM <- BU_tibM  %>% dplyr::group_by(Mdate) %>% dplyr::summarize(n=n()) %>% dplyr::ungroup() %>%  dplyr::select(Mdate, n)

pM <- ggplot(BU_TimeM, aes(x=Mdate, y=n)) +
       geom_line() +xlab("Date") + ylab("Participants") +  ggtitle("Plot 1: Most Recent Menstrual Period Start Date")
pM + scale_x_date(date_labels = "%b %Y")


#PREGNANT
menstrual_funct(D_518916981, "PREGNANT: Currently Pregnant")

#PREG3MON
one_skip_funct(D_234714655, "Table 13: Been Pregnant in the Last 3 Months", D_518916981, "104430631") 

#BRSTFD
menstrual_funct(D_798452445, "Table 14: Currently Breastfeeding")

#BRSTFD3MON
one_skip_funct(D_563539159, "Table 15: Breastfed in the Last 3 Months", D_798452445, "104430631") 

#CONTRACEPT
one_skip_funct(D_875535246, "Table 16: Used Hormonal Contraceptives in the Last Month", D_518916981, "104430631") 

#HORMONE
one_skip_funct(D_130311122, "Table 17: Used Prescription Hormone Therapy in the Last Month", D_518916981, "104430631") 

```
