---
title: "Blood, Urine, Mouthwash Survey Summary Statistics"
author: "Kelsey Dowling"
date: "`r Sys.Date()`"
header-includes:  
    \usepackage[labelformat=empty]{caption}
    \usepackage{placeins}
    \usepackage{booktabs}



output:
  pdf_document:
    extra_dependencies: ["float"]
    toc: true
    toc_depth: 2
    keep_tex: yes
    fig_width: 7
    fig_height: 5
    fig_caption: true
    df_print: paged
---


```{r libraries, include=FALSE}
library(bigrquery)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(scales)
library(gt)
#install(tinytex)
library(tinytex)
library(tidyr)
library(knitr)
library(kableExtra)

options(tinytex.verbose = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

bq_auth()
```

```{r merge, include=FALSE}
project = "nih-nci-dceg-connect-prod-6d04"
billing= "nih-nci-dceg-connect-prod-6d04"
biospec <- "SELECT * FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.bioSurvey_v1_JP`  where Connect_ID is not null"
parts <- "SELECT Connect_ID, token, D_512820379, D_471593703, state_d_934298480, D_230663853,
D_335767902, D_982402227, D_919254129, D_699625233, D_564964481, D_795827569, D_544150384,
D_371067537, D_430551721, D_821247024, D_914594314,  state_d_725929722, d_822499427, d_222161762,
D_949302066 , D_517311251, D_205553981, D_117249500, d_265193023, d_331584571_d_266600170_d_343048998, d_331584571_d_266600170_d_840048338 FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.participants_JP` 
where Connect_ID IS NOT NULL and (D_512820379='486306141' OR D_512820379='854703046') and d_331584571_d_266600170_d_840048338 is not null and d_331584571_d_266600170_d_343048998 is not null and d_265193023='231311385'"
specimenBUM <- "SELECT Connect_ID, d_556788178 FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.biospecimen_JP` where Connect_ID is not null"


biospec_table <- bq_project_query(project, biospec, n_max = Inf, page_size = 1000)
parts_table <- bq_project_query(project, parts, n_max = Inf, page_size = 1000)

specimenBUM_table <- bq_project_query(project, specimenBUM)

biospec_data <- bq_table_download(biospec_table, bigint = "integer64")
parts_data <- bq_table_download(parts_table, bigint = "integer64")
specimenBUM_data <- bq_table_download(specimenBUM_table, bigint = "integer64",n_max = Inf, page_size = 1000)


parts_data$Connect_ID <- as.numeric(parts_data$Connect_ID) 
biospec_data$Connect_ID <- as.numeric(biospec_data$Connect_ID) 
specimenBUM_data$Connect_ID <- as.numeric(specimenBUM_data$Connect_ID) 


bisp= left_join(biospec_data, parts_data, by="Connect_ID") %>%  left_join(specimenBUM_data, by="Connect_ID") 
#dim(bisp)


cat("Particiapnts with Blood, Urine, Mouthwash Survey Completed: ", dim(bisp)[[1]])
#dim(BUM)

BUM_tib <- as_tibble(bisp)
#dim(BUM_tib)

knitr::opts_chunk$set(comment = NA)

```



```{r functions, include=FALSE}
##FUNCTIONS

BUM_dict <- list("104430631"="No", "353358909"="Yes", "178420302"="Unknown", "536341288"="Female", "576796184"="Intersex or Other", "654207589"="Male",
                 "110092955"="The same day", "952212668"="The day before", "330461666"="More than a day before", "974230748"="Yes, in the past day",
                 "936042740"="Yes, in the past two days", "731141335"="Yes, in the past week", "591670915"="Yes, in the past month", "111520945"="Not at all",
                 "548628123"="A little bit", "567908725"="Somewhat", "760969884"="Quite a bit", "464631026"="Very Much", "707601969"="Yes, another",
                 "232063618"="Less than 1 month", "948148236"="Between 1 and 3 months", "692824372"="More than 3 months", "224099497"="Yes, mostly",
                 "770236544"="No, I never experienced this", "931688701"="Yes, I am experiencing this now", 
                 "586272115"="Yes, I experienced this in the past", "503154121"="Novavax" ,
                 "661871565"="Moderna", "657978450"="Pfizer", "411943417"="Johnson & Johnson", "113838601"="AstraZeneca", "807835037"="Other", 
                 "670680466"="Excellent", "927477599"="Very Good", "719933364"="Good", "131550264"="Fair", "138752522"="Poor", "648960871"="Never",
                 "693256778"="Less than Once Per Week", "735330419"="1-2 Times per Week", "138332277"="3-5 Times per Week", "858624942"="Once per Day", 
                 "85067541"="2-3 Times per Day", "317567178"="In the last month", "891558680"="In the last 1-6 months", "796081734"="In the past 6-12 months",
                 "752219885"="Over a year, in the Last Two Years", "314487612"="More than 2 years", "666365344"="Within the Last 24 Hours", 
                 "735136116"="In the Past 2-7 Days", "382679079"="In the last 2-4 weeks", "830677489"="More than 4 Weeks Ago", "349122068"="One",
                 "194129782"="Two to Four", "922737557"="Five to Nine", "945387130"="10+", "383505459"="More than 1 but Don't Remember", "832322940"="Don't Know",
                 "317811347"="Don't Know", "850675416"="Two or more times per day")

gt_functBUM <- function(CID, Title){  
  CID_SYM <- rlang::ensym(CID)
  dt_select <- BUM_tib %>%  select(Connect_ID, !!CID_SYM)
  gt_yn <- dt_select  %>% group_by(!!CID_SYM) %>% summarize(n=n(), percentage=100*n/nrow(.)) %>% ungroup() %>% mutate(answer=dplyr::recode(!!CID_SYM, !!!BUM_dict)) %>% replace_na(list(answer="Skipped this Question")) %>%  select(answer, n, percentage)
  
  gt_yn %>%  gt::gt()  %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md(Title)) %>% 
  cols_label(answer = md("**Answer**"), n = md("**N**"), percentage = md("**%**")) %>% 
grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T)) %>% 
  tab_options(
      stub.font.weight = "bold"
    ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = answer,
    )
  ) %>% opt_row_striping()
}

menstrual_funct <- function(CID, Title){  
  CID_SYM <- rlang::ensym(CID)
  dt_select <- BUM_tib %>%  select(Connect_ID, !!CID_SYM) %>%  filter(BUM_tib$D_522008539==536341288)
  gt_yn <- dt_select  %>% group_by(!!CID_SYM) %>% summarize(n=n(), percentage=100*n/nrow(.)) %>% ungroup()  %>%  mutate(answer=dplyr::recode(!!CID_SYM, !!!BUM_dict)) %>% replace_na(list(answer="Skipped this Question")) %>%  select(answer, n, percentage)
  
  gt_yn %>%  gt::gt()  %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md(Title)) %>% 
  cols_label(answer = md("**Answer**"), n = md("**N**"), percentage = md("**%**")) %>% 
grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T)) %>% 
  tab_options(
      stub.font.weight = "bold"
    ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = answer,
    )
  ) %>% opt_row_striping()
}


covid_once_funct <- function(CID, Title){  
  CID_SYM <- rlang::ensym(CID)
  dt_select <- BUM_tib %>%  select(Connect_ID, !!CID_SYM) %>%  filter(BUM_tib$d_222161762<as.Date("2023-07-05") & (as.numeric(BUM_tib$D_860011428)>=1 | BUM_tib$D_494226443=="353358909"))
  gt_yn <- dt_select  %>% group_by(!!CID_SYM) %>% summarize(n=n(), percentage=100*n/nrow(.)) %>% ungroup()  %>%  mutate(answer=dplyr::recode(!!CID_SYM, !!!BUM_dict)) %>% replace_na(list(answer="Skipped this Question")) %>%  select(answer, n, percentage)
  
  gt_yn %>%  gt::gt()  %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md(Title)) %>% 
  cols_label(answer = md("**Answer**"), n = md("**N**"), percentage = md("**%**")) %>% 
grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T)) %>% 
  tab_options(
      stub.font.weight = "bold"
    ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = answer,
    )
  ) %>% opt_row_striping()
}

covid_twice_funct <- function(CID, Title){  
  CID_SYM <- rlang::ensym(CID)
  dt_select <- BUM_tib %>%  select(Connect_ID, !!CID_SYM) %>%  filter(BUM_tib$d_222161762<as.Date("2023-07-05") & as.numeric(BUM_tib$D_860011428)>=2)
  gt_yn <- dt_select  %>% group_by(!!CID_SYM) %>% summarize(n=n(), percentage=100*n/nrow(.)) %>% ungroup()  %>%  mutate(answer=dplyr::recode(!!CID_SYM, !!!BUM_dict)) %>% replace_na(list(answer="Skipped this Question")) %>%  select(answer, n, percentage)
  
  gt_yn %>%  gt::gt()  %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md(Title)) %>% 
  cols_label(answer = md("**Answer**"), n = md("**N**"), percentage = md("**%**")) %>% 
grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T)) %>% 
  tab_options(
      stub.font.weight = "bold"
    ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = answer,
    )
  ) %>% opt_row_striping()
}

covid_thrice_funct <- function(CID, Title){  
  CID_SYM <- rlang::ensym(CID)
  dt_select <- BUM_tib %>%  select(Connect_ID, !!CID_SYM) %>%  filter(BUM_tib$d_222161762<as.Date("2023-07-05")& as.numeric(BUM_tib$D_860011428)>=3)
  gt_yn <- dt_select  %>% group_by(!!CID_SYM) %>% summarize(n=n(), percentage=100*n/nrow(.)) %>% ungroup() %>%  mutate(answer=dplyr::recode(!!CID_SYM, !!!BUM_dict)) %>% replace_na(list(answer="Skipped this Question")) %>%  select(answer, n, percentage)
  
  gt_yn %>%  gt::gt()  %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md(Title)) %>% 
  cols_label(answer = md("**Answer**"), n = md("**N**"), percentage = md("**%**")) %>% 
grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T)) %>% 
  tab_options(
      stub.font.weight = "bold"
    ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = answer,
    )
  ) %>% opt_row_striping()
}


#One skip logic (previous response)


one_skip_funct <- function(CID, Title, Previous_CID, Previous_Answer){  
  CID_SYM <- rlang::ensym(CID)
  CID_SYM_P <- rlang::ensym(Previous_CID)
  dt_select <- BUM_tib %>%  filter(!!CID_SYM_P==Previous_Answer) %>%  select(Connect_ID, !!CID_SYM) 
  gt_yn <- dt_select  %>% dplyr::group_by(!!CID_SYM) %>% dplyr::summarize(n=n(), percentage=100*n/nrow(.)) %>% dplyr::ungroup() %>% dplyr::mutate(answer=dplyr::recode(!!CID_SYM, !!!BUM_dict)) %>% replace_na(list(answer="Skipped this Question")) %>%  dplyr::select(answer, n, percentage)
  gt_yn %>%  gt::gt()  %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md(Title)) %>% 
  cols_label(answer = md("**Answer**"),  n = md("**N**"),  percentage = md("**%**")) %>% 
  grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T)) %>%
  tab_options(
      stub.font.weight = "bold"
    ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = answer,
    )
  ) %>% opt_row_striping()
}


#Two skip logic (previous response)
two_skip_funct <- function(CID, Title, Previous_CID, Previous_Answer, Previous_CID2, Previous_Answer2){  
  CID_SYM <- rlang::ensym(CID)
  CID_SYM_P <- rlang::ensym(Previous_CID)
  CID_SYM_P2 <- rlang::ensym(Previous_CID2)
  dt_select2 <- BUM_tib %>%  filter(!!CID_SYM_P==Previous_Answer | !!CID_SYM_P2==Previous_Answer2) %>% 
    select(Connect_ID, !!CID_SYM) 
  gt2_yn <- dt_select2  %>% dplyr::group_by(!!CID_SYM) %>% dplyr::summarize(n=n(), percentage=100*n/nrow(.)) %>% dplyr::ungroup() %>% dplyr::mutate(answer=recode(!!CID_SYM, !!!BUM_dict)) %>% replace_na(list(answer="Skipped this Question")) %>%  dplyr::select(answer, n, percentage)
  gt2_yn %>%  gt::gt()  %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md(Title)) %>% 
  cols_label(answer = md("**Answer**"),  n = md("**N**"),  percentage = md("**%**")) %>% 
  grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T)) %>%
  tab_options(
      stub.font.weight = "bold"
    ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = answer,
    )
  ) 
}

#Histogram Function
hist_funct <- function(CID,Title, Xlab, Ylab) {
  CID_SYM <- rlang::ensym(CID)
  bisp %>% mutate(!!CID_SYM:=as.numeric(!!CID_SYM)) %>%
    filter(!is.na(!!CID_SYM)) %>% ggplot(aes(x=!!CID_SYM))+
     xlab(Xlab) + ylab(Ylab) + geom_histogram()+  ggtitle(Title)+
    geom_histogram(color="black")+ scale_y_continuous(breaks=pretty_breaks()) +
    geom_vline(aes(xintercept=mean(!!CID_SYM, na.rm=T)), colour="#2973A5", linetype="solid")
  
}

```



```{r intro, warning=FALSE, echo=FALSE,  message=FALSE, include=FALSE}


### All required questions:



#MENSTPRD
BUM_tib %>%  select(Connect_ID, d_265193023, d_822499427, d_222161762) %>%  filter(is.na(BUM_tib$D_380603392) & BUM_tib$D_522008539==536341288) ## =0

#MENST60
BUM_tib %>%  select(Connect_ID, d_265193023, d_822499427, d_222161762) %>%  filter(is.na(BUM_tib$D_112151599) & BUM_tib$D_522008539==536341288 & BUM_tib$D_380603392==353358909) ## ==0, but not required for everyone

#MENSTART
BUM_tib %>%  select(Connect_ID, d_265193023, d_822499427, d_222161762) %>%  filter(is.na(BUM_tib$D_644459734) & BUM_tib$D_522008539==536341288 & BUM_tib$D_112151599==353358909) ##==0, but not required for everyone

#COVID?
BUM_tib %>%  select(Connect_ID, d_265193023, d_822499427, d_222161762) %>%  filter(is.na(BUM_tib$D_494226443) & BUM_tib$D_522008539==536341288)  ## =0

```


\newpage

```{r Tables1_3, warning=FALSE, echo=FALSE,  message=FALSE}



#SEX
gt_functBUM(D_522008539, "SEX: Biological Sex at Birth")



#SYMPTDAY

dt_SYMPTDAY= BUM_tib %>%  mutate(multb2 = ifelse(D_470484596_D_756774083==1, 1, 0) + ifelse(D_470484596_D_235386560==1, 1, 0) + ifelse(D_470484596_D_955154600==1, 1, 0) + 
                                             ifelse(D_470484596_D_811126581==1, 1, 0) + ifelse(D_470484596_D_406943303==1, 1, 0))



 which_sympt= dt_SYMPTDAY %>%  mutate(symptom= case_when(as.numeric(multb2)>1 ~ "Multiple Symptoms",
                                                         D_470484596_D_756774083==1 ~ "Cough",
                                                         D_470484596_D_235386560==1 ~ "Diarrhea",
                                                         D_470484596_D_955154600==1 ~ "Nasal Congestion",
                                                         D_470484596_D_811126581==1 ~ "Sick to Your Stomach or Vomitting",
                                                         D_470484596_D_406943303==1 ~ "Fever",
                                                         D_470484596_D_535003378==1 ~ "None of these",
                                                         TRUE   ~ "Skipped this Question"))

 which_sympt$symptom <- factor(which_sympt$symptom,levels=c("Multiple Symptoms", "Cough", "Diarrhea", "Nasal Congestion", "Sick to Your Stomach or Vomitting", "Fever",  "None of these", "Skipped this Question"))


dt_SYMPTDAY_summary <- which_sympt %>% group_by(symptom) %>%  dplyr::summarize(n=n(), percentage=round(100*n/nrow(.), digits=2)) %>%  dplyr::select(symptom, n, percentage)


dt_SYMPTDAY_summary  %>%  gt::gt() %>%
  fmt_number(columns = "percentage", 
             decimals = 2) %>%
  tab_header(title = md("Table 2: Symptoms in the 24 hours Prior to Sample Donation")) %>%
  cols_label(symptom = md("**Answer**"), n = md("**Number**"), percentage = md("**Percentage**")) %>%
  grand_summary_rows(columns=c(n, percentage),
                     fns = ~sum(.,na.rm = T)) %>%
  tab_options(stub.font.weight = "bold") %>%
  tab_style(style = list(cell_text(weight = "bold")),
            locations = cells_body(columns = symptom))


#EATDRINKBEFORE
EATDRINKBEFORE <- gt_functBUM(D_867307558, "Table 3: When Last Food or Beverage Consumed")


which_eattime= BUM_tib %>%  mutate(answer= case_when(D_867307558==110092955 ~ "The same day",
                                             D_867307558==952212668 ~ "The day before",
                                             D_867307558==330461666 ~ "More than a day before",
                                             TRUE   ~ "Skipped this Question"))
which_eattime$answer <- factor(which_eattime$answer,levels=c("The same day", "The day before", "More than a day before","Skipped this Question"))


dt_eattime_summary <- which_eattime %>% group_by(answer) %>%  summarize(n=n(), percentage=100*n/nrow(.)) %>%  select(answer, n, percentage)


dt_eattime_summary %>%  gt::gt() %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md("Table 3: When Last Food or Beverage Consumed")) %>% 
  cols_label(answer = md("**Answer**"), n = md("**N**"), percentage = md("**%**")) %>% 
grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T)) %>% 
  tab_options(stub.font.weight = "bold") %>%
  tab_style(style = list(cell_text(weight = "bold")),locations = cells_body(columns = answer,)) %>% opt_row_striping()



```


```{r merge2, include=FALSE, warning=FALSE}

library(stringr)
library(lubridate)

avgP_ccc <-  "SELECT  Connect_ID, d_173836415_d_266600170_d_448660695, d_265193023, d_827220437 FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.participants_JP` 
where d_265193023='231311385' and d_173836415_d_266600170_d_448660695 is not null "
avgB_ccc <-  "SELECT Connect_ID, D_191057574, D_191057574_V2, D_867307558 FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.bioSurvey_v1_JP` 
where (D_191057574 is not null OR D_191057574_V2 is not null) "


avgP_table_cc <- bq_project_query(project, avgP_ccc)
avgB_table_cc <- bq_project_query(project, avgB_ccc)

avgP <- bq_table_download(avgP_table_cc, bigint = "integer64")
avgB <- bq_table_download(avgB_table_cc, bigint = "integer64")

avgP$Connect_ID <- as.numeric(avgP$Connect_ID)
avgB$Connect_ID <- as.numeric(avgB$Connect_ID)

average <- left_join(avgP, avgB , by="Connect_ID")

avg <- as_tibble(average)

```
```{r, echo=FALSE, warning=FALSE, message=FALSE}


avg_s <- avg %>%  filter((d_827220437==531629870 |  d_827220437==548392715 | d_827220437==303349821 | d_827220437==657167265 | d_827220437==809703864) & !is.na(D_867307558))
#avg$Site<- droplevels(avg$Site)

#(D_867307558==110092955 ~ "Same day",D_867307558==952212668 ~ "The Day before"))

avg_coll2 <- avg_s %>%  mutate(D_191057574V=case_when(!is.na(D_191057574_V2) ~ D_191057574_V2,
                                                      !is.na(D_191057574) ~ D_191057574))
#avg_coll3 <- avg_s %>%  mutate(D_191057574V=ifelse(!is.na(D_191057574), D_191057574, D_191057574_V2))


#avg_s$D_191057574 <- paste0("2023-", avg_s$D_191057574)
#avg_s$D_191057574 <- as.Date(avg_s$D_191057574, format="MM-DD")
avg_coll2$MW_date <- as.Date(avg_coll2$d_173836415_d_266600170_d_448660695) 
avg_coll2$MW_dayb4 <- avg_coll2$MW_date - 1
#avg_coll2$MW_dayb4 <- paste0((avg_coll2$MW_date - 1), str_sub(avg_coll2$d_173836415_d_266600170_d_448660695,11,24))
#avg_coll2$MW_dayb4 <- avg_coll2$d_173836415_d_266600170_d_448660695-1

avg_coll2 <- avg_coll2 %>%  mutate(eat= case_when(D_867307558==110092955 ~ paste0(str_sub(avg_coll2$d_173836415_d_266600170_d_448660695,1,11), avg_coll2$D_191057574V, ":00.000Z"),
                                                  D_867307558==952212668 ~ paste0(avg_coll2$MW_dayb4, avg_coll2$D_191057574V, ":00.000Z" )))


avg_coll <- avg_coll2 %>%  mutate(time = as.numeric(difftime(as.POSIXct(ymd_hms(d_173836415_d_266600170_d_448660695)),as.POSIXct(ymd_hms(eat)),units="hours")))
                                 # Site = case_when(d_827220437==531629870 ~ "HealthPartners",
                                 #                  d_827220437==548392715 ~ "Henry Ford Health System",
                                 #                  d_827220437==303349821 ~ "Marshfield Clinic Health System",
                                 #                  d_827220437==657167265 ~ "Sanford Health",
                                 #                  d_827220437==809703864 ~ "University of Chicago Medicine"))

avg_coll <- avg_coll %>%  mutate(MW = case_when( as.numeric(abs(abs(time))) >72 ~">72hrs",
                                            72 >= as.numeric(abs(time)) & as.numeric(abs(time)) > 48 ~ "> 48 hrs to 72 hrs",
                                            48 >= as.numeric(abs(time)) & as.numeric(abs(time)) > 24 ~ "> 24 hrs to 48 hrs",   
                                            24 >= as.numeric(abs(time)) & as.numeric(abs(time)) > 12 ~ "> 12 hrs to 24 hrs",
                                            12 >= as.numeric(abs(time)) & as.numeric(abs(time)) > 3 ~ "> 3 hrs to 12 hrs",  
                                            3 >= as.numeric(abs(time)) & as.numeric(abs(time)) >= 0 ~ "0 hrs to 3 hrs",
                                            TRUE ~ "Missing Time"),
                                 Site=case_when(d_827220437==531629870 ~ "HealthPartners",
                                                 d_827220437==548392715 ~ "Henry Ford Health System",
                                                 d_827220437==303349821 ~ "Marshfield Clinical Health System",
                                                 d_827220437==657167265 ~ "Sanford Health",
                                                 d_827220437==809703864 ~ "University of Chicago Medicine",
                                                d_827220437==125001209 ~ "Kaiser Permanente Colorado",
                                                 d_827220437==327912200 ~ "Kaiser Permanente Georgia",
                                                 d_827220437==300267574 ~ "Kaiser Permanente Hawaii",
                                                 d_827220437==452412599 ~ "Kaiser Permanente Northwest"))
avg_coll$MW <- factor(avg_coll$MW, levels= c(  "Missing Time", "0 hrs to 3 hrs", "> 3 hrs to 12 hrs", "> 12 hrs to 24 hrs", "> 24 hrs to 48 hrs", "> 48 hrs to 72 hrs", ">72hrs"))


MW_time1 <- avg_coll %>% group_by(Site, MW) %>%  summarize(n=n(), percentage=100*n/nrow(.)) %>%  select(Site,  MW, n, percentage) # %>% dplyr::ungroup() #------ why is it saying MW is not a column????
#MW_time <- MW_time1 %>%  sort_by(Site) 
  
MW_time1 %>%  gt::gt()  %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md("Table 4. Time from Last Meal to Time of Mouthwash Collection")) %>% 
  cols_label(n= md("**Number**"), MW = md(" "), percentage = md("**Percent**")) %>%  
  grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T))
  # summary_rows(
  #   columns = c(n,percentage),    
  #   fns= list(
  #     Sum= ~sum(.)
  #   ), decimals=0)

```




\FloatBarrier


```{r RemovedGraphs, warning=FALSE, echo=FALSE,  message=FALSE}



#EATDRINKTIME
EATDRINKTIME_V1=bisp %>% filter(!is.na(D_191057574) & (D_867307558== "952212668"| D_867307558=="330461666")) %>% ggplot(aes(x=D_191057574))+ ylab("Count") + 
  xlab("Time (Military Time)") +geom_bar()+  ggtitle("EATDRINKTIME(V1): Time Food or Beverage Last Consumed") +theme(axis.text.x = element_text(angle = 90))

EATDRINKTIME_V2=bisp %>% filter(!is.na(D_191057574_V2) & (D_867307558== "952212668"| D_867307558=="330461666")) %>% ggplot(aes(x=D_191057574_V2))+ ylab("Count") + 
  xlab("Time (Military Time)") +geom_bar()+  ggtitle("EATDRINKTIME(V2): Time Food or Beverage Last Consumed") +theme(axis.text.x = element_text(angle = 90))
#grid.arrange(EATDRINKTIME_V1, EATDRINKTIME_V2, nrow=2)


#SLEEPTIME
SLEEPTIME_V1=bisp %>% filter(!is.na(D_299417266)) %>% ggplot(aes(x=D_299417266))+ ylab("Count") + 
  xlab("Time (Military Time)") +geom_bar()+  ggtitle("SLEEPTIME(V1): Bedtime the Night Before Donation") +theme(axis.text.x = element_text(angle = 90))

SLEEPTIME_V2=bisp %>% filter(!is.na(D_299417266_V2)) %>% ggplot(aes(x=D_299417266_V2))+ ylab("Count") + 
  xlab("Time (Military Time)") +geom_bar()+  ggtitle("SLEEPTIME(V2): Bedtime the Night Before Donation") +theme(axis.text.x = element_text(angle = 90))
#grid.arrange(SLEEPTIME_V1, SLEEPTIME_V2, nrow=2)



BUM_sig <- BUM_tib %>%  filter(!is.na(D_299417266_V2) | !is.na(D_299417266)) %>%  #v1 and v2 were answered in this survey
  mutate(sleep = paste0(str_sub(d_556788178,1,11), 
                        ifelse(!is.na(D_299417266_V2),  str_sub(D_299417266_V2,1,5),  str_sub(D_299417266,1,5)), #choose whichever was answered
                        str_sub(d_556788178,17,24)),
         slptime= paste0(as.Date(sleep) -1, "T", str_sub(sleep,12,24)), #question is time you went to bed the night BEFORE, so have to subtract a day 
         time_sleep = difftime(as.POSIXct(ymd_hms(d_556788178)), as.POSIXct(ymd_hms(slptime)),units="hours"),
         time=as.numeric(time_sleep)) 


BUM_SLEEP = BUM_sig %>% #group_by(Site) %>% #biochk_outlier,
  dplyr::summarize('Number of Participants'=n(),
                   Min = min(time,na.rm = TRUE),
                   Q1 = quantile(time, 0.25,na.rm = TRUE),
                   Median = median(time,na.rm = TRUE),
                   Mean = mean(time,na.rm = TRUE),
                   SD=sd(time,na.rm = TRUE),
                   Q3 = quantile(time, 0.75,na.rm = TRUE),
                   Max = max(time,na.rm = TRUE))
bm_wake <- knitr::kable(BUM_SLEEP,caption='Table 5: Hours Participant Fell Asleep Before Sample Donation',digits=1, booktabs = TRUE)%>% kable_styling(latex_options = "scale_down") #%>% landscape()
add_footnote(bm_wake,"Note: Those who did not answer this question are removed from the Number of Participants in order to calculate difference in existing times.", notation = "none") #and greater than 500 minutes 




#WAKETIME
WAKETIME_V1=bisp %>% filter(!is.na(D_689861450)) %>% ggplot(aes(x=D_689861450))+ ylab("Count") + 
  xlab("Time (Military Time)") +geom_bar()+  ggtitle("WAKETIME(V1): Wake-up Time the Day of Donation") +theme(axis.text.x = element_text(angle = 90))

WAKETIME_V2=bisp %>% filter(!is.na(D_689861450_V2)) %>% ggplot(aes(x=D_689861450_V2))+ ylab("Count") + 
  xlab("Time (Military Time)") +geom_bar()+  ggtitle("WAKETIME(V2): Wake-up Time the Day of Donation") +theme(axis.text.x = element_text(angle = 90))
#grid.arrange(WAKETIME_V1, WAKETIME_V2, nrow=2)




BUM_sig <- BUM_tib %>%  filter(!is.na(D_689861450_V2) | !is.na(D_689861450)) %>%  #v1 and v2 were answered in this survey
  mutate(wake2 = paste0(str_sub(d_556788178,1,11), 
                        ifelse(!is.na(D_689861450_V2),  str_sub(D_689861450_V2,1,5),  str_sub(D_689861450,1,5)), #whichever one was answered
                        str_sub(d_556788178,17,24)),
         time_biochk2 = difftime(as.POSIXct(ymd_hms(d_556788178)), as.POSIXct(ymd_hms(wake2)),units="hours"),
         time2=as.numeric(time_biochk2)) 


BUM_WAKE = BUM_sig %>% #group_by(Site) %>% #biochk_outlier,
  dplyr::summarize('Number of Participants'=n(),
                   Min = min(time2,na.rm = TRUE),
                   Q1 = quantile(time2, 0.25,na.rm = TRUE),
                   Median = median(time2,na.rm = TRUE),
                   Mean = mean(time2,na.rm = TRUE),
                   SD=sd(time2,na.rm = TRUE),
                   Q3 = quantile(time2, 0.75,na.rm = TRUE),
                   Max = max(time2,na.rm = TRUE))
bm_wake <- knitr::kable(BUM_WAKE,caption='Table 6: Hours Awakened Before Sample Donation',digits=1, booktabs = TRUE)%>% kable_styling(latex_options = "scale_down") #%>% landscape()
add_footnote(bm_wake,"Note: Those who did not answer this question are removed from the Number of Participants in order to calculate difference in existing times.", notation = "none") #and greater than 500 minutes 



```

\newpage

# Medications
```{r Meds, warning=FALSE, echo=FALSE,  message=FALSE}

BUM_tib$D_487532606_D_619765650 <- factor(BUM_tib$D_487532606_D_619765650,levels=c(104430631, 974230748, 936042740, 731141335, 591670915, "Skipped this Question"))
BUM_tib$D_487532606_D_520755310 <- factor(BUM_tib$D_487532606_D_520755310,levels=c(104430631, 974230748, 936042740, 731141335, 591670915, "Skipped this Question"))
BUM_tib$D_487532606_D_839329467 <- factor(BUM_tib$D_487532606_D_839329467,levels=c(104430631, 974230748, 936042740, 731141335, 591670915, "Skipped this Question"))

gt_functBUM(D_487532606_D_619765650, "TYLENOL: Medication Taken, if so, Last Time Taken")

gt_functBUM(D_487532606_D_520755310, "NSAIDS: Medication Taken, if so, Last Time Taken")

gt_functBUM(D_487532606_D_839329467, "Acid Reducers: Medication Taken, if so, Last Time Taken")



```

\newpage
\pagebreak

# Reproductive Health 
```{r ReproductiveHealth, warning=FALSE, echo=FALSE,  message=FALSE}


#MENSTPRD
menstrual_funct(D_380603392, "MENSTPRD: Had Menstrual Period in the Last 12 Months")


#MENST60
one_skip_funct(D_112151599, "MENST60: Had Menstrual Period in the Last 60 Days", D_380603392, "353358909") 



#MENSTART
BUM_tibM <- BUM_tib %>%  filter(!is.na(BUM_tib$D_644459734) & BUM_tib$D_112151599=="353358909")
BUM_tibM$Mdate <- as.Date(BUM_tibM$D_644459734)

BUM_TimeM <- BUM_tibM  %>% dplyr::group_by(Mdate) %>% dplyr::summarize(n=n()) %>% dplyr::ungroup() %>%  dplyr::select(Mdate, n)

pM <- ggplot(BUM_TimeM, aes(x=Mdate, y=n)) +
       geom_line() +xlab("Date") + ylab("Participants") +  ggtitle("Plot 1: Most Recent Menstrual Period Start Date")
pM + scale_x_date(date_labels = "%b %Y")


#PREGNANT
menstrual_funct(D_518916981, "PREGNANT: Currently Pregnant")


#PREG3MON
one_skip_funct(D_234714655, "Table 13: Been Pregnant in the Last 3 Months", D_518916981, "104430631") 

#BRSTFD
menstrual_funct(D_798452445, "Table 14: Currently Breastfeeding")

#BRSTFD3MON
one_skip_funct(D_563539159, "Table 15: Breastfed in the Last 3 Months", D_798452445, "104430631") 

#CONTRACEPT
one_skip_funct(D_875535246, "Table 16: Used Hormonal Contraceptives in the Last Month", D_518916981, "104430631") 

#HORMONE
one_skip_funct(D_130311122, "Table 17: Used Prescription Hormone Therapy in the Last Month", D_518916981, "104430631") 


```

\newpage

# Mouthwash Data Collection 
```{r Mouthwash, warning=FALSE, echo=FALSE,  message=FALSE}


#ORALHLTH
BUM_tib$D_350251057 <- factor(BUM_tib$D_350251057,levels=c(670680466, 927477599, 719933364, 131550264, 138752522, 178420302, "Skipped this Question"))
gt_functBUM(D_350251057, "Table 117: Overall Health Ranking")



#MWBEFORE
gt_functBUM(D_877878167, "Table 19: Brushed Teeth Within the Hour Before Sample Donation")


#RINSEBEFORE
gt_functBUM(D_800703566, "Table 20: Rinsed Mouth Within the Hour Before Sample Donation")


#GUMBEFORE
gt_functBUM(D_294886836, "Table 21: Chewed Gum Within the Hour Before Sample Donation")


#TOBACCOBEFORE
gt_functBUM(D_642044281, "Table 22: Smoke, Vape or Chew Products Within the Hour Before Sample Donation")
```

\newpage
```{r Mouthwash_cont, warning=FALSE, echo=FALSE,  message=FALSE}

#HYGIENE
   
  #for now excluding options without toothbrush                                           
hy_prod= BUM_tib %>%  mutate(products= case_when((D_479143504_D_203919683==1 & D_479143504_D_807884576==1 & D_479143504_D_165596977==1 & D_479143504_D_578402172==1 & D_479143504_D_184513726==1 & D_479143504_D_390351864==1) ~ "All Products",
                                                 (D_479143504_D_184513726==1 & D_479143504_D_807884576==1 & D_479143504_D_165596977==1 & D_479143504_D_578402172==1 & D_479143504_D_390351864==1) ~ "All Products, Except Toothbrush",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_165596977==1 & D_479143504_D_578402172==1 & D_479143504_D_184513726==1 & D_479143504_D_390351864==1) ~ "All Products, Except Floss",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_807884576==1 & D_479143504_D_578402172==1 & D_479143504_D_184513726==1 & D_479143504_D_390351864==1) ~ "All Products, Except Water Based Flosser",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_807884576==1 & D_479143504_D_165596977==1 & D_479143504_D_184513726==1 & D_479143504_D_390351864==1) ~ "All Products, Except Tongue Cleaner",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_807884576==1 & D_479143504_D_165596977==1 & D_479143504_D_578402172==1 & D_479143504_D_390351864==1) ~ "All Products, Except Teeth Whitener",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_807884576==1 & D_479143504_D_165596977==1 & D_479143504_D_578402172==1 & D_479143504_D_184513726==1) ~ "All Products, Except Mouthwash",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_807884576==1 & D_479143504_D_165596977==1 & D_479143504_D_578402172==1) ~ "All Products, Except Teeth Whitener and Mouthwash",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_807884576==1 & D_479143504_D_165596977==1 & D_479143504_D_184513726==1) ~ "All Products, Except Tongue Cleaner and Mouthwash",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_807884576==1 & D_479143504_D_165596977==1 & D_479143504_D_390351864==1) ~ "All Products, Except Tongue Cleaner and Teeth Whitener",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_165596977==1 & D_479143504_D_578402172==1 & D_479143504_D_184513726==1) ~ "All Products, Except Floss and Mouthwash",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_165596977==1 & D_479143504_D_578402172==1 & D_479143504_D_390351864==1) ~ "All Products, Except Floss and Teeth Whitener",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_184513726==1 & D_479143504_D_578402172==1 & D_479143504_D_390351864==1) ~ "All Products, Except Floss and Water-based Flosser",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_807884576==1 & D_479143504_D_165596977==1) ~ "Toothbrush, Floss, Water-based Flosser",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_807884576==1 & D_479143504_D_578402172==1) ~ "Toothbrush, Floss, Tongue Cleaner",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_807884576==1 & D_479143504_D_184513726==1) ~ "Toothbrush, Floss, Teeth Whitener",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_807884576==1 & D_479143504_D_390351864==1) ~ "Toothbrush, Floss, Teeth Mouthwash",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_165596977==1 & D_479143504_D_578402172==1) ~ "Toothbrush, Water-based Flosser, Tongue Cleaner",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_165596977==1 & D_479143504_D_184513726==1) ~ "Toothbrush, Water-based Flosser, Teeth Whitener",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_165596977==1 & D_479143504_D_390351864==1) ~ "Toothbrush, Water-based Flosser, Teeth Mouthwash",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_578402172==1 & D_479143504_D_184513726==1) ~ "Toothbrush, Tongue Cleaner, Teeth Whitener",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_578402172==1 & D_479143504_D_390351864==1) ~ "Toothbrush, Tongue Cleaner, Mouthwash",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_184513726==1 & D_479143504_D_390351864==1) ~ "Toothbrush, Teeth Whitener, Mouthwash",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_807884576==1) ~ "Toothbrush, Floss",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_165596977==1) ~ "Toothbrush, Water-based Flosser",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_578402172==1) ~ "Toothbrush, Tongue Cleaner",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_184513726==1) ~ "Toothbrush, Teeth Whitener",
                                                 (D_479143504_D_203919683==1 & D_479143504_D_390351864==1) ~ "Toothbrush, Mouthwash",
                                                 D_479143504_D_203919683==1 ~ "Toothbrush",
                                                 D_479143504_D_807884576==1 ~ "Floss",
                                                 D_479143504_D_165596977==1 ~ "Water-based flosser or jet",
                                                 D_479143504_D_578402172==1 ~ "Tongue Cleaner",
                                                 D_479143504_D_184513726==1 ~ "Teeth Whitener",
                                                 D_479143504_D_390351864==1 ~ "Mouthwash",
                                                 TRUE   ~ "Skipped this Question"))

hy_prod$products <- factor(hy_prod$products,levels=c("All Products", "All Products, Except Toothbrush","All Products, Except Floss","All Products, Except Water Based Flosser",
                                                     "All Products, Except Tongue Cleaner", "All Products, Except Teeth Whitener", "All Products, Except Mouthwash",
                                                     "All Products, Except Teeth Whitener and Mouthwash", "All Products, Except Tongue Cleaner and Mouthwash",
                                                     "All Products, Except Tongue Cleaner and Teeth Whitener","All Products, Except Floss and Mouthwash",
                                                     "All Products, Except Floss and Teeth Whitener", "All Products, Except Floss and Water-based Flosser",
                                                     "Toothbrush, Floss, Water-based Flosser","Toothbrush, Floss, Tongue Cleaner","Toothbrush, Floss, Teeth Whitener", 
                                                     "Toothbrush, Floss, Teeth Mouthwash", "Toothbrush, Water-based Flosser, Tongue Cleaner", 
                                                     "Toothbrush, Water-based Flosser, Teeth Whitener", "Toothbrush, Water-based Flosser, Teeth Mouthwash",
                                                     "Toothbrush, Tongue Cleaner, Teeth Whitener","Toothbrush, Tongue Cleaner, Mouthwash","Toothbrush, Teeth Whitener, Mouthwash",
                                                     "Toothbrush, Floss","Toothbrush, Water-based Flosser","Toothbrush, Tongue Cleaner","Toothbrush, Teeth Whitener","Toothbrush, Mouthwash",
                                                     "Toothbrush", "Floss", "Water-based flosser or jet", "Tongue Cleaner", "Teeth Whitener", "Mouthwash", "Skipped this Question"))

dt_hygeine_summary <- hy_prod  %>% dplyr::group_by(products) %>% dplyr::summarize(n=n(), percentage=round(100*n/nrow(.), digits=2)) %>% dplyr::ungroup() %>%  dplyr::select(products, n, percentage)



dt_hygeine_summary %>%  gt::gt() %>%
  fmt_number(columns = "percentage", 
             decimals = 1) %>%
  tab_header(title = md("Table 122: Oral Health Products Used in the Last Month")) %>%
  cols_label(products = md("**Answer**"), n = md("**N**"), percentage = md("**%**")) %>%
  grand_summary_rows(columns=c(n, percentage),
                     fns = ~sum(.,na.rm = T)) %>%
  tab_options(stub.font.weight = "bold") %>%
  tab_style(style = list(cell_text(weight = "bold")),locations = cells_body(columns = products))



#BRUSH2
BUM_tib$D_498984275 <- factor(BUM_tib$D_498984275,levels=c(648960871, 693256778, 735330419, 138332277, 858624942, 850675416 , "Skipped this Question"))
one_skip_funct(D_498984275, "Table 123: Frequency Using a Toothbrush in the Last Month", D_479143504_D_203919683, "1")



#FLOSS2
BUM_tib$D_205713835 <- factor(BUM_tib$D_205713835,levels=c(648960871, 693256778, 735330419, 138332277, 858624942, 850675416 , "Skipped this Question"))
one_skip_funct(D_205713835, "Table 124: Frequency Using Floss in the Last Month", D_479143504_D_807884576, "1")


#WTRPICK2
BUM_tib$D_353467497 <- factor(BUM_tib$D_353467497,levels=c(648960871, 693256778, 735330419, 138332277, 858624942, 850675416 , "Skipped this Question"))
one_skip_funct(D_353467497, "Table 125: Frequency Using a Water Based Flosser or Pick in the Last Month", D_479143504_D_165596977, "1")



#TONGUE2
BUM_tib$D_429994023 <- factor(BUM_tib$D_429994023,levels=c(648960871, 693256778, 735330419, 138332277, 858624942, 850675416 , "Skipped this Question"))
one_skip_funct(D_429994023, "Table 126: Frequency Using a Tongue Scrubber in the Last Month", D_479143504_D_578402172, "1")



#WHITE2
BUM_tib$D_499977481 <- factor(BUM_tib$D_499977481,levels=c(648960871, 693256778, 735330419, 138332277, 858624942, 850675416 , "Skipped this Question"))
one_skip_funct(D_499977481, "Table 127: Frequency Using Teeth Whitener in the Last Month", D_479143504_D_184513726, "1")





#MWUSE
dt_MWUSE= BUM_tib %>%  filter(D_479143504_D_390351864==1)


mw_prod= dt_MWUSE %>%  mutate(products= case_when(D_406270109_D_950773275==1 ~ "Alcohol Based Mouthwash",
                                             D_406270109_D_762727133==1 ~ "Alcohol Free Mouthwash",
                                             D_406270109_D_877842367==1 ~ "Chlorhexidine Mouthwash",
                                             D_406270109_D_886771318==1 ~ "Flouride Mouthwash",
                                             D_406270109_D_404389800==1 ~ "Peroxide Mouthwash",
                                             D_406270109_D_463302301==1 ~ "Cetylpyridinium chloride Mouthwash",
                                             D_406270109_D_259744087==1 ~ "Mouthwash for Sensitive Teeth",
                                             D_406270109_D_523660949==1 ~ "Mouthwash for Dry Mouth",
                                             TRUE   ~ "Skipped this Question"))

dt_MWUSE_summary <- mw_prod  %>% dplyr::group_by(products) %>% dplyr::summarize(n=n(), percentage=100*n/nrow(.)) %>% dplyr::ungroup() %>%  dplyr::select(products, n, percentage)

dt_MWUSE_summary %>%  gt::gt() %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md("Table 29: Mouthwash Products Used in the Last Month")) %>% 
  cols_label(products = md("**Answer**"), n = md("**N**"), percentage = md("**%**")) %>% 
grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T)) %>% 
  tab_options(stub.font.weight = "bold") %>%
  tab_style(style = list(cell_text(weight = "bold")),locations = cells_body(columns = products,)) %>% opt_row_striping()



#MWALC
BUM_tib$D_349659426 <- factor(BUM_tib$D_349659426,levels=c(648960871, 693256778, 735330419, 138332277, 858624942, 850675416 , "Skipped this Question"))
one_skip_funct(D_349659426, "Table 129: Frequency Using Alcohol Based Mouthwash", D_406270109_D_950773275, "1")


#MWALCFREE
BUM_tib$D_766370065 <- factor(BUM_tib$D_766370065,levels=c(648960871, 693256778, 735330419, 138332277, 858624942, 850675416 , "Skipped this Question"))
one_skip_funct(D_766370065, "Table 130: Frequency Using Alcohol Free Mouthwash", D_406270109_D_762727133, "1")



#MWCHLOR
BUM_tib$D_520416570 <- factor(BUM_tib$D_520416570,levels=c(648960871, 693256778, 735330419, 138332277, 858624942, 850675416 , "Skipped this Question"))
one_skip_funct(D_520416570, "Table 131: Frequency Using Chlorhexidine Mouthwash", D_406270109_D_877842367, "1")


#MWFLOURIDE
BUM_tib$D_921972241 <- factor(BUM_tib$D_921972241,levels=c(648960871, 693256778, 735330419, 138332277, 858624942, 850675416 , "Skipped this Question"))
one_skip_funct(D_921972241, "Table 132: Frequency Using Flouride Mouthwash", D_406270109_D_886771318, "1")


#MWPEROX
BUM_tib$D_526973271 <- factor(BUM_tib$D_526973271,levels=c(648960871, 693256778, 735330419, 138332277, 858624942, 850675416 , "Skipped this Question"))
one_skip_funct(D_526973271, "Table 133: Frequency Using Peroxide Mouthwash", D_406270109_D_404389800, "1")


#MWCETYL
BUM_tib$D_460873842 <- factor(BUM_tib$D_460873842,levels=c(648960871, 693256778, 735330419, 138332277, 858624942, 850675416 , "Skipped this Question"))
one_skip_funct(D_460873842, "Table 134: Frequency Using Cetylpyridinium Cloride Mouthwash", D_406270109_D_463302301, "1")


#MWSENSITIVE
BUM_tib$D_430060900 <- factor(BUM_tib$D_430060900,levels=c(648960871, 693256778, 735330419, 138332277, 858624942, 850675416 , "Skipped this Question"))
one_skip_funct(D_430060900, "Table 135: Frequency Using Mouthwash for Sensitive Teeth", D_406270109_D_259744087, "1")


#MWDRY
BUM_tib$D_800752981 <- factor(BUM_tib$D_800752981,levels=c(648960871, 693256778, 735330419, 138332277, 858624942, 850675416 , "Skipped this Question"))
one_skip_funct(D_800752981,  "Table 136: Frequency Using Mouthwash for Dry Mouth", D_406270109_D_523660949, "1")








#PERMTTHLOST
  #Version1
dt_PERMTTHLOST1= BUM_tib %>%   
  filter(BUM_tib$d_822499427<as.Date("2022-11-29") & BUM_tib$d_222161762<as.Date("2022-12-1"))

#lost= dt_PERMTTHLOST1 %>%  mutate(multb2 = ifelse(D_899251483_D_812107266==1, 1, 0) + ifelse(D_899251483_D_452438775==1, 1, 0) + ifelse(D_899251483_V2_D_886864375==1, 1, 0) + ifelse(D_899251483_D_104430631==1, 1, 0))

                                                          

                                                    
lost= dt_PERMTTHLOST1 %>%  mutate(products= case_when((D_899251483_D_812107266==1 & D_899251483_D_452438775==1 & D_899251483_V2_D_886864375==1) ~ "From Accident, Decay, and Other Reasons",
                                           (D_899251483_D_812107266==1 & D_899251483_D_452438775==1) ~ "From Accident and Decay",
                                           (D_899251483_D_812107266==1 & D_899251483_V2_D_886864375==1) ~ "From Accident and Other Reasons",
                                           (D_899251483_D_452438775==1 & D_899251483_V2_D_886864375==1) ~ "From Decay and Other Reasons",
                                           D_899251483_D_812107266==1 ~ "Yes from accident or injury",
                                             D_899251483_D_452438775==1 ~ "Yes from tooth decay or disease",
                                             D_899251483_V2_D_886864375==1 ~ "Yes for some other reason",
                                             D_899251483_D_104430631==1 ~ "No",
                                             TRUE   ~ "Skipped this Question"))
lost$products <- factor(lost$products,levels=c("From Accident, Decay, and Other Reasons", "From Accident and Decay", "From Accident and Other Reasons", "From Decay and Other Reasons", "Yes from accident or injury", "Yes from tooth decay or disease", "Yes for some other reason", "No", "Skipped this Question"))

dt_PERMTTHLOST_summary <- lost  %>% dplyr::group_by(products) %>% dplyr::summarize(n=n(), percentage=100*n/nrow(.)) %>% dplyr::ungroup() %>%  dplyr::select(products, n, percentage)

df_PERMTTHLOST <- as.data.frame(dt_PERMTTHLOST_summary)

df_PERMTTHLOST %>%  gt::gt() %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md("Table 38 (V1): Lost Permanent Adult Teeth, not Including your Wisdom Teeth")) %>% 
  cols_label(products = md("**Answer**"), n = md("**N**"), percentage = md("**%**")) %>% 
grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T)) %>% 
  tab_options(stub.font.weight = "bold") %>%
  tab_style(style = list(cell_text(weight = "bold")),locations = cells_body(columns = products,)) %>% opt_row_striping()



  #Version2
dt_PERMTTHLOST2= BUM_tib %>%   
  filter(BUM_tib$d_222161762>as.Date("2022-12-1"))

#lost2= dt_PERMTTHLOST2 %>%  mutate(multb2 = ifelse(D_899251483_V2_D_812107266==1, 1, 0) + ifelse(D_899251483_V2_D_452438775==1, 1, 0) + ifelse(D_899251483_V2_D_886864375==1, 1, 0) + ifelse(D_899251483_V2_D_104430631==1, 1, 0))

                                                          

                                                    
                                           
lost2= dt_PERMTTHLOST2 %>%  mutate(products2= case_when((D_899251483_V2_D_812107266==1 & D_899251483_V2_D_452438775==1 & D_899251483_V2_D_886864375==1)~ "From Accident, Decay, and Other Reasons",
                                           (D_899251483_V2_D_812107266==1 & D_899251483_V2_D_452438775==1) ~ "From Accident and Decay",
                                           (D_899251483_V2_D_812107266==1 & D_899251483_V2_D_886864375==1) ~ "From Accident and Other Reasons",
                                           (D_899251483_V2_D_452438775==1 & D_899251483_V2_D_886864375==1) ~ "From Decay and Other Reasons",
                                           D_899251483_V2_D_812107266==1 ~ "Yes from accident or injury",
                                             D_899251483_V2_D_452438775==1 ~ "Yes from tooth decay or disease",
                                             D_899251483_V2_D_886864375==1 ~ "Yes for some other reason",
                                             D_899251483_V2_D_104430631==1  ~ "No",
                                             TRUE   ~ "Skipped this Question"))

lost2$products2 <- factor(lost2$products2,levels=c("From Accident, Decay, and Other Reasons", "From Accident and Decay", "From Accident and Other Reasons", "From Decay and Other Reasons", "Yes from accident or injury", "Yes from tooth decay or disease", "Yes for some other reason", "No", "Skipped this Question"))

dt_PERMTTHLOST_summary <- lost2  %>% dplyr::group_by(products2) %>% dplyr::summarize(n=n(), percentage=100*n/nrow(.)) %>% dplyr::ungroup() %>%  dplyr::select(products2, n, percentage)

df_PERMTTHLOST <- as.data.frame(dt_PERMTTHLOST_summary)

df_PERMTTHLOST %>%  gt::gt() %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md("Table 39 (V2): Lost Permanent Adult Teeth, not Including your Wisdom Teeth")) %>% 
  cols_label(products2 = md("**Answer**"), n = md("**N**"), percentage = md("**%**")) %>% 
grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T)) %>% 
  tab_options(stub.font.weight = "bold") %>%
  tab_style(style = list(cell_text(weight = "bold")),locations = cells_body(columns = products2,)) %>% opt_row_striping()


#TEETHLOSTAI
TEETHLOSTAI <- BUM_tib %>%  select(Connect_ID, D_724589244) %>%  filter((BUM_tib$D_899251483_V2_D_812107266==1 | BUM_tib$D_899251483_D_812107266==1) & (BUM_tib$d_822499427>as.Date("2022-12-1")))
  #TEETHLOSTAI_yn <- TEETHLOSTAI  %>% group_by(D_724589244) %>% summarize(n=n(), percentage=100*n/nrow(.)) %>% ungroup() %>% mutate(answer=dplyr::recode(D_724589244, !!!BUM_dict)) %>% replace_na(list(answer="Skipped this Question")) %>%  select(answer, n, percentage)
  TEETHLOSTAI_yn= TEETHLOSTAI %>%  mutate(answer= case_when(D_724589244==349122068 ~ "One", # | D_542661394_D_167336253==1
                                             D_724589244==194129782~ "Two to Four",
                                             D_724589244==922737557 ~ "Five to Nine",
                                             D_724589244==945387130 ~ "10+",
                                             D_724589244==383505459 ~ "More than 1 but Don't Remember",
                                             D_724589244==832322940 ~ "Don't Know",
                                             TRUE   ~ "Skipped this Question"))

  TEETHLOSTAI_yn$answer <- factor(TEETHLOSTAI_yn$answer, levels= c("One", "Two to Four", "Five to Nine", "10+", "More than 1 but Don't Remember", "Don't Know", "Skipped this Question"))
  dt_TEETHLOSTAI_yn_summary <- TEETHLOSTAI_yn  %>% dplyr::group_by(answer) %>% dplyr::summarize(n=n(), percentage=100*n/nrow(.)) %>% dplyr::ungroup() %>%  dplyr::select(answer, n, percentage)
  
  dt_TEETHLOSTAI_yn_summary %>%  gt::gt()  %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md("Table 40: Number of Teeth Lost from Accident or Injury")) %>% 
  cols_label(answer = md("**Answer**"), n = md("**N**"), percentage = md("**%**")) %>% 
grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T)) %>% 
  tab_options(
      stub.font.weight = "bold"
    ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = answer,
    )
  ) %>% opt_row_striping()


#TEETHLOSTD
TEETHLOSTD <- BUM_tib %>%  select(Connect_ID, D_957305523) %>%  filter((BUM_tib$D_899251483_V2_D_452438775==1 | BUM_tib$D_899251483_D_452438775==1) & (BUM_tib$d_822499427>as.Date("2022-12-1"))) 
  #TEETHLOSTD_yn <- TEETHLOSTD  %>% group_by(D_957305523) %>% summarize(n=n(), percentage=100*n/nrow(.)) %>% ungroup() %>% mutate(answer=dplyr::recode(D_957305523, !!!BUM_dict)) %>% replace_na(list(answer="Skipped this Question")) %>%  select(answer, n, percentage)
    TEETHLOSTD_yn= TEETHLOSTD %>%  mutate(answer= case_when(D_957305523==349122068 ~ "One", # | D_542661394_D_167336253==1
                                             D_957305523==194129782~ "Two to Four",
                                             D_957305523==922737557 ~ "Five to Nine",
                                             D_957305523==945387130 ~ "10+",
                                             D_957305523==383505459 ~ "More than 1 but Don't Remember",
                                             D_957305523==832322940 ~ "Don't Know",
                                             TRUE   ~ "Skipped this Question"))
    
  TEETHLOSTD_yn$answer <- factor(TEETHLOSTD_yn$answer, levels= c("One", "Two to Four", "Five to Nine", "10+", "More than 1 but Don't Remember", 
                                                                 "Don't Know", "Skipped this Question"))
  dt_TEETHLOSTD_yn_summary <- TEETHLOSTD_yn  %>% dplyr::group_by(answer) %>% dplyr::summarize(n=n(), percentage=100*n/nrow(.)) %>% dplyr::ungroup() %>%  dplyr::select(answer, n, percentage)
  
  dt_TEETHLOSTD_yn_summary %>%  gt::gt()  %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md("Table 41: Number of Teeth Lost from Tooth Decay or Disease")) %>% 
  cols_label(answer = md("**Answer**"), n = md("**N**"), percentage = md("**%**")) %>% 
grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T)) %>% 
  tab_options(
      stub.font.weight = "bold"
    ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = answer,
    )
  ) %>% opt_row_striping()


#TEETHLOSTOTH
TEETHLOSTOTH <- BUM_tib %>%  select(Connect_ID, D_360678252) %>%  filter((BUM_tib$D_899251483_V2_D_886864375==1| BUM_tib$D_899251483_V2_D_886864375==1) & (BUM_tib$d_822499427>as.Date("2022-12-1")))
  #TEETHLOSTOTH_yn <- TEETHLOSTOTH  %>% group_by(D_360678252) %>% summarize(n=n(), percentage=100*n/nrow(.)) %>% ungroup() %>% mutate(answer=dplyr::recode(D_360678252, !!!BUM_dict)) %>% replace_na(list(answer="Skipped this Question")) %>%  select(answer, n, percentage)
      TEETHLOSTOTH_yn= TEETHLOSTOTH %>%  mutate(answer= case_when(D_360678252==349122068 ~ "One", # | D_542661394_D_167336253==1
                                             D_360678252==194129782~ "Two to Four",
                                             D_360678252==922737557 ~ "Five to Nine",
                                             D_360678252==945387130 ~ "10+",
                                             D_360678252==383505459 ~ "More than 1 but Don't Remember",
                                             D_360678252==832322940 ~ "Don't Know",
                                             TRUE   ~ "Skipped this Question"))
      
  TEETHLOSTOTH_yn$answer <- factor(TEETHLOSTOTH_yn$answer, levels= c("One", "Two to Four", "Five to Nine", "10+", "More than 1 but Don't Remember", "Don't Know", "Skipped this Question"))
  dt_TEETHLOSTOTH_yn_summary <- TEETHLOSTOTH_yn  %>% dplyr::group_by(answer) %>% dplyr::summarize(n=n(), percentage=100*n/nrow(.)) %>% dplyr::ungroup() %>%  dplyr::select(answer, n, percentage)
  
  dt_TEETHLOSTOTH_yn_summary %>%  gt::gt()  %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md("Table 42: Number of Teeth Lost from Other Incidents")) %>% 
  cols_label(answer = md("**Answer**"), n = md("**N**"), percentage = md("**%**")) %>% 
grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T)) %>% 
  tab_options(
      stub.font.weight = "bold"
    ) %>%
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = answer,
    )
  ) %>% opt_row_striping()


#DENTURES
dnt= BUM_tib %>%  mutate(products= case_when(D_542661394_D_104430631==1 ~ "No", # | D_542661394_D_167336253==1
                                             D_542661394_D_329536041==1 ~ "Dental Bridges",
                                             D_542661394_D_365685000==1 ~ "Partial Denture",
                                             D_542661394_D_215662651==1 ~ "Full Dentures",
                                             D_542661394_D_656498939==1 ~ "Dental Implants",
                                             D_542661394_D_181769837==1 ~ "Other",
                                             D_542661394_D_178420302==1 ~ "Uknown",
                                             TRUE   ~ "Skipped this Question"))

dnt$products <- factor(dnt$products, levels= c("No", "Dental Bridges", "Partial Denture", "Full Dentures", "Dental Implants", "Other", "Uknown", "Skipped this Question"))
dt_DENTURES_summary <- dnt  %>% dplyr::group_by(products) %>% dplyr::summarize(n=n(), percentage=100*n/nrow(.)) %>% dplyr::ungroup() %>%  dplyr::select(products, n, percentage)

dt_DENTURES_summary %>%  gt::gt() %>%  
  fmt_number(columns = "percentage", decimals = 1) %>% 
  tab_header(title = md("Table 43: Lost Permanent Adult Teeth, not Including your Wisdom Teeth")) %>% 
  cols_label(products = md("**Answer**"), n = md("**N**"), percentage = md("**%**")) %>% 
grand_summary_rows(columns=c(n, percentage),fns = ~sum(.,na.rm = T)) %>% 
  tab_options(stub.font.weight = "bold") %>%
  tab_style(style = list(cell_text(weight = "bold")),locations = cells_body(columns = products,)) %>% opt_row_striping()


#DENTALCELAN
BUM_tib$D_339570897 <- factor(BUM_tib$D_339570897, levels= c(317567178, 891558680, 796081734, 752219885, 314487612, 178420302, "Skipped this Question"))
gt_functBUM(D_339570897, "Table 143: Last Professional Dental Cleaning")


#CAVITY
gt_functBUM(D_983043203, "Table 45: Had Cavities in Adult Teeth")


#GUMDISEASE
gt_functBUM(D_736028153, "Table 46: Diagnosed with Gum Disease")


#GUMTX
gt_functBUM(D_792134396, "Table 47: Treated for Gum Disease")


#ANTIBIO
gt_functBUM(D_736393021, "Table 48: Taken Antibiotics in the Last 2 Months")


#ANTIBIOTIME
BUM_tib$D_318641324 <- factor(BUM_tib$D_318641324, levels= c(666365344, 735136116, 382679079, 830677489, "Skipped this Question"))
one_skip_funct(D_318641324, "Table 148: Date Antiobiotic Last Taken", D_736393021, "353358909")



```




