# cloudbuild.yaml

steps:

 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build','-t', 'gcr.io/nih-nci-dceg-connect-prod-6d04/ccc-biospecimen-metrics:$COMMIT_SHA', '.']
   timeout: 3600s
   
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/nih-nci-dceg-connect-prod-6d04/ccc-biospecimen-metrics:$COMMIT_SHA']
   
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args: ['run','deploy','ccc-biospecimen-metrics', 
   '--image=gcr.io/nih-nci-dceg-connect-prod-6d04/ccc-biospecimen-metrics:$COMMIT_SHA', 
   '--concurrency=1', 
   '--cpu=8',
   '--memory=32Gi', 
   '--region=us-central1', 
   '--service-account=qa-qc-prod@nih-nci-dceg-connect-prod-6d04.iam.gserviceaccount.com']

tags:
  - reporting_pipeline
  - biospecimen_metrics   

options:
  logging: CLOUD_LOGGING_ONLY
  
images:
 - 'gcr.io/nih-nci-dceg-connect-prod-6d04/ccc-biospecimen-metrics:$COMMIT_SHA'
