---
title: "COVID Survey Summary Statistics"
author: "Kelsey Dowling"
date: "`r Sys.Date()`"
header-includes:  
    \usepackage[labelformat=empty]{caption}
    \usepackage{placeins} 
    \usepackage{booktabs}
    \usepackage{pdflscape}
    \usepackage{float}
    \usepackage{threeparttable}
    \usepackage{makecell}

output:
  pdf_document:
    latex_engine: xelatex
    df_print: paged
---


This report includes all COVID-19 Survey Data as well as COVID-19 related questions that have since been removed from the Research Blood, Urine, Mouthwash Survey and the Clinical Blood, Urine Survey on July 5th, 2023.

```{r libraries, include=FALSE}

library(bigrquery)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(scales)
library(gt)
library(gtsummary)
#install(tinytex)
library(tinytex)
library(tidyr)
library(knitr)
library(kableExtra)
library(lubridate)

options(tinytex.verbose = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

bq_auth()

```

```{r merge, include=FALSE}

project = "nih-nci-dceg-connect-prod-6d04"
billing= "nih-nci-dceg-connect-prod-6d04"


#either the independent covid survey was done, or the BUM survey with COVID was done (before that section was removed), or the BU survey with COVID was done (before that section was removed)
covid <- "SELECT * FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.covid19Survey_v1`  where Connect_ID is not null"
bum <- "SELECT * FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.bioSurvey_v1`  where Connect_ID is not null"
bu <- "SELECT * FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.clinicalBioSurvey_v1`    where Connect_ID is not null"

parts <- "SELECT Connect_ID, token, D_512820379, D_471593703, state_d_934298480, D_230663853,
D_335767902, D_982402227, D_919254129, D_699625233, D_564964481, D_795827569, D_544150384,
D_371067537, D_430551721, D_821247024, D_914594314,  state_d_725929722, d_822499427, d_222161762,
D_949302066 , D_517311251, D_205553981, D_117249500, d_265193023, d_331584571_d_266600170_d_343048998, 
d_331584571_d_266600170_d_840048338, d_220186468, d_253883960, d_764863765, d_784810139
FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.participants` 
where Connect_ID IS NOT NULL and (d_512820379='486306141' OR d_512820379='854703046') and 
((d_220186468='231311385' and Date(d_784810139)>='2023-07-05') or 
(d_265193023='231311385' and Date(d_222161762)<'2023-07-05') or 
(d_253883960='231311385' and Date(d_764863765)<'2023-07-05')) and d_821247024='197316935'"




covid_table <- bq_project_query(project, covid, n_max = Inf, page_size = 1000)
bum_table <- bq_project_query(project, bum, n_max = Inf, page_size = 1000)
bu_table <- bq_project_query(project, bu, n_max = Inf, page_size = 1000)
parts_table <- bq_project_query(project, parts, n_max = Inf, page_size = 1000)


covid_data <- bq_table_download(covid_table, bigint = "integer64")
bum_data <- bq_table_download(bum_table, bigint = "integer64")
bu_data <- bq_table_download(bu_table, bigint = "integer64")
parts_data <- bq_table_download(parts_table, bigint = "integer64")


parts_data$Connect_ID <- as.numeric(parts_data$Connect_ID) 
bum_data$Connect_ID <- as.numeric(bum_data$Connect_ID)
bu_data$Connect_ID <- as.numeric(bu_data$Connect_ID)
covid_data$Connect_ID <- as.numeric(covid_data$Connect_ID)


covid_only= left_join(parts_data, covid_data, by="Connect_ID")
bum_only= left_join(parts_data, bum_data, by="Connect_ID")
bu_only= left_join(parts_data, bu_data, by="Connect_ID")


#The COVID survey flag contains some BU/BUM completions, don't want to double count 
covid_pts <- covid_only %>%  filter((d_220186468=='231311385' & as.Date(d_784810139)>='2023-07-05'))
bum_pts <- bum_only %>%  filter((d_265193023=='231311385' & as.Date(d_222161762)<'2023-07-05'))
bu_pts <- bu_only %>%  filter((d_253883960=='231311385' & as.Date(d_764863765)<'2023-07-05'))

#Confirmed there were no Connect IDs in more than one dataframe

cvd <- bind_rows(covid_pts, bum_pts, bu_pts)

CVD_tib <- as_tibble(cvd)
#dim(CVD_tib)

knitr::opts_chunk$set(comment = NA)


```





```{r counts, warning=FALSE, echo=FALSE}

cat("Particiapnts with COVID Survey Completion: ", dim(cvd)[[1]])



```

```{r functions, include=FALSE}
##FUNCTIONS

## All responses of the COVID survey questions
dict <- list("104430631"="No", "353358909"="Yes", "178420302"="Do not Know", "536341288"="Female", "576796184"="Intersex or Other", "654207589"="Male",
                 "110092955"="The same day", "952212668"="The day before", "330461666"="More than a day before", "974230748"="Yes, in the past day",
                 "936042740"="Yes, in the past two days", "731141335"="Yes, in the past week", "591670915"="Yes, in the past month", "111520945"="Not at all",
                 "548628123"="A little bit", "567908725"="Somewhat", "760969884"="Quite a bit", "464631026"="Very Much", "707601969"="Yes, another",
                 "232063618"="Less than 1 month", "948148236"="Between 1 and 3 months", "692824372"="More than 3 months", "224099497"="Yes, mostly",
                 "770236544"="No, I never experienced this", "931688701"="Yes, I am experiencing this now", 
                 "586272115"="Yes, I experienced this in the past", "503154121"="Novavax" ,
                 "661871565"="Moderna", "657978450"="Pfizer", "411943417"="Johnson & Johnson", "113838601"="AstraZeneca", "503154121"="Novavax", "807835037"="Other", 
                 "670680466"="Excellent", "927477599"="Very Good", "719933364"="Good", "131550264"="Fair", "138752522"="Poor", "648960871"="Never",
                 "693256778"="Less than Once Per Week", "735330419"="1-2 Times per Week", "138332277"="3-5 Times per Week", "858624942"="Once per Day", 
                 "85067541"="2-3 Times per Day", "317567178"="In the last month", "891558680"="In the last 1-6 months", "796081734"="In the past 6-12 months",
                 "752219885"="Over a year, in the Last Two Years", "314487612"="More than 2 years", "666365344"="Within the Last 24 Hours", 
                 "735136116"="In the Past 2-7 Days", "382679079"="In the last 2-4 weeks", "830677489"="More than 4 Weeks Ago", "349122068"="One",
                 "194129782"="Two to Four", "922737557"="Five to Nine", "945387130"="10+", "383505459"="More than 1 but Don't Remember", "832322940"="Don't Know",
                 "317811347"="Don't Know", "850675416"="Two or more times per day")


simple_funct_CVD <- function(CID, Title){  
  CID_SYM <- rlang::ensym(CID)

      gt_yn <- CVD_tib %>%
    group_by(!!CID_SYM) %>%
    summarize(n = n(), percentage = 100 * n / nrow(.)) %>%
    ungroup() %>%
    mutate(answer = dplyr::recode(!!CID_SYM, !!!dict)) %>%
    replace_na(list(answer = "Skipped this Question")) %>%
    select(answer, n, percentage)
  
    gt_yn_kable <- gt_yn %>%
    mutate(
      percentage = round(percentage, 1),
      N = comma(n)
    ) %>%
    select(answer, N, percentage) %>%
    dplyr::rename(
      "Answer" = answer,
      "Pct" = percentage
    ) %>%
    bind_rows(
      tibble(
        Answer = "Total",
        N = comma(sum(gt_yn$n, na.rm = TRUE)),
        "Pct" = round(sum(gt_yn$Pct, na.rm = TRUE), 1)
      )
    )

  kable(gt_yn_kable, 
        caption = Title, align = "lrr",
        booktabs = TRUE, longtable = TRUE, escape = TRUE) %>%
    add_indent(seq(1, nrow(gt_yn_kable) - 1)) %>% 
    kable_styling(latex_options = c("scale_down"))
}




covid_once_funct <- function(CID, Title){  
  CID_SYM <- rlang::ensym(CID)
  
  gt_yn <- CVD_tib %>%
    filter((as.numeric(CVD_tib$D_860011428)>=1 | CVD_tib$D_494226443=="353358909")) %>% 
    group_by(!!CID_SYM) %>%
    summarize(n = n(), percentage = 100 * n / nrow(.)) %>%
    ungroup() %>%
    mutate(answer = dplyr::recode(!!CID_SYM, !!!dict)) %>%
    replace_na(list(answer = "Skipped this Question")) %>%
    select(answer, n, percentage)

gt_yn_kable <- gt_yn %>%
  mutate(
    percentage = round(percentage, 1),
    N = comma(n)
  ) %>%
  select(answer, N, percentage) %>%
  dplyr::rename(
    "Answer" = answer,
    "Pct" = percentage
  ) %>%
  bind_rows(
    tibble(
      Answer = "Total",
      N = comma(sum(gt_yn$n, na.rm = TRUE)),
      "Pct" = round(sum(gt_yn$Pct, na.rm = TRUE), 1)
    )
  )

  kable(gt_yn_kable, 
        caption = Title, align = "lrr",
        booktabs = TRUE, longtable = TRUE, escape = TRUE) %>%
    add_indent(seq(1, nrow(gt_yn_kable) - 1)) %>% 
    kable_styling(latex_options = c("scale_down"))
}


covid_twice_funct <- function(CID, Title){  
  CID_SYM <- rlang::ensym(CID)
  
     gt_yn <- CVD_tib %>%
        filter(as.numeric(CVD_tib$D_860011428)>=2) %>% 
    group_by(!!CID_SYM) %>%
    summarize(n = n(), percentage = 100 * n / nrow(.)) %>%
    ungroup() %>%
    mutate(answer = dplyr::recode(!!CID_SYM, !!!dict)) %>%
    replace_na(list(answer = "Skipped this Question")) %>%
    select(answer, n, percentage)
      
  gt_yn_kable <- gt_yn %>%
    mutate(
      percentage = round(percentage, 1),
      N = comma(n)
    ) %>%
    select(answer, N, percentage) %>%
    dplyr::rename(
      "Answer" = answer,
      "Pct" = percentage
    ) %>%
    bind_rows(
      tibble(
        Answer = "Total",
        N = comma(sum(gt_yn$n, na.rm = TRUE)),
        "Pct" = round(sum(gt_yn$Pct, na.rm = TRUE), 1)
      )
    )

  
  kable(gt_yn_kable, 
        caption = Title, align = "lrr",
        booktabs = TRUE, longtable = TRUE, escape = TRUE) %>%
    add_indent(seq(1, nrow(gt_yn_kable) - 1)) %>% 
    kable_styling(latex_options = c("scale_down"))
}

covid_thrice_funct <- function(CID, Title){  
  CID_SYM <- rlang::ensym(CID)
  
     gt_yn <- CVD_tib %>%
        filter(as.numeric(CVD_tib$D_860011428)>=3) %>% 
    group_by(!!CID_SYM) %>%
    summarize(n = n(), percentage = 100 * n / nrow(.)) %>%
    ungroup() %>%
    mutate(answer = dplyr::recode(!!CID_SYM, !!!dict)) %>%
    replace_na(list(answer = "Skipped this Question")) %>%
    select(answer, n, percentage)
      
  gt_yn_kable <- gt_yn %>%
    mutate(
      percentage = round(percentage, 1),
      N = comma(n)
    ) %>%
    select(answer, N, percentage) %>%
    dplyr::rename(
      "Answer" = answer,
      "Pct" = percentage
    ) %>%
    bind_rows(
      tibble(
        Answer = "Total",
        N = comma(sum(gt_yn$n, na.rm = TRUE)),
        "Pct" = round(sum(gt_yn$Pct, na.rm = TRUE), 1)
      )
    )

  
  kable(gt_yn_kable, 
        caption = Title, align = "lrr",
        booktabs = TRUE, longtable = TRUE, escape = TRUE) %>%
    add_indent(seq(1, nrow(gt_yn_kable) - 1)) %>% 
    kable_styling(latex_options = c("scale_down"))
}


#One skip logic (previous response was one particular response)
one_skip_funct <- function(CID, Title, Previous_CID, Previous_Answer){  
  CID_SYM <- rlang::ensym(CID)
  CID_SYM_P <- rlang::ensym(Previous_CID)
  
     gt_yn <- CVD_tib %>%
        filter(!!CID_SYM_P==Previous_Answer) %>% 
    group_by(!!CID_SYM) %>%
    summarize(n = n(), percentage = 100 * n / nrow(.)) %>%
    ungroup() %>%
    mutate(answer = dplyr::recode(!!CID_SYM, !!!dict)) %>%
    replace_na(list(answer = "Skipped this Question")) %>%
    select(answer, n, percentage)
      
  gt_yn_kable <- gt_yn %>%
    mutate(
      percentage = round(percentage, 1),
      N = comma(n)
    ) %>%
    select(answer, N, percentage) %>%
    dplyr::rename(
      "Answer" = answer,
      "Pct" = percentage
    ) %>%
    bind_rows(
      tibble(
        Answer = "Total",
        N = comma(sum(gt_yn$n, na.rm = TRUE)),
        "Pct" = round(sum(gt_yn$Pct, na.rm = TRUE), 1)
      )
    )

  
  kable(gt_yn_kable, 
        caption = Title, align = "lrr",
        booktabs = TRUE, longtable = TRUE, escape = TRUE) %>%
    add_indent(seq(1, nrow(gt_yn_kable) - 1)) %>% 
    kable_styling(latex_options = c("scale_down"))
}


#Two skip logic (previous response was one of two particular responses)
two_skip_funct <- function(CID, Title, Previous_CID, Previous_Answer, Previous_CID2, Previous_Answer2){  
  CID_SYM <- rlang::ensym(CID)
  CID_SYM_P <- rlang::ensym(Previous_CID)
  CID_SYM_P2 <- rlang::ensym(Previous_CID2)
    
      gt_yn <- CVD_tib %>%
        filter(!!CID_SYM_P==Previous_Answer | !!CID_SYM_P2==Previous_Answer2) %>% 
    group_by(!!CID_SYM) %>%
    summarize(n = n(), percentage = 100 * n / nrow(.)) %>%
    ungroup() %>%
    mutate(answer = dplyr::recode(!!CID_SYM, !!!dict)) %>%
    replace_na(list(answer = "Skipped this Question")) %>%
    select(answer, n, percentage)
      
  gt_yn_kable <- gt_yn %>%
    mutate(
      percentage = round(percentage, 1),
      N = comma(n)
    ) %>%
    select(answer, N, percentage) %>%
    dplyr::rename(
      "Answer" = answer,
      "Pct" = percentage
    ) %>%
    bind_rows(
      tibble(
        Answer = "Total",
        N = comma(sum(gt_yn$n, na.rm = TRUE)),
        "Pct" = round(sum(gt_yn$Pct, na.rm = TRUE), 1)
      )
    )

  
  kable(gt_yn_kable, 
        caption = Title, align = "lrr",
        booktabs = TRUE, longtable = TRUE, escape = TRUE) %>%
    add_indent(seq(1, nrow(gt_yn_kable) - 1)) %>% 
    kable_styling(latex_options = c("scale_down"))

      
}


create_kable_table <- function(df, group_by_vriable, Title){  
  CID_SYM <- rlang::ensym(group_by_vriable)
  
  gt_yn <- df %>%
    group_by(!!CID_SYM) %>%
    summarize(n = n(), percentage = 100 * n / nrow(.)) %>%
    ungroup() %>%
    mutate(answer = dplyr::recode(!!CID_SYM, !!!dict)) %>%
    replace_na(list(answer = "Skipped this Question")) %>%
    select(answer, n, percentage)
  
  gt_yn_kable <- gt_yn %>%
    mutate(
      percentage = round(percentage, 1),
      N = comma(n)
    ) %>%
    select(answer, N, percentage) %>%
    dplyr::rename(
      "Answer" = answer,
      "Pct" = percentage
    ) %>%
    bind_rows(
      tibble(
        Answer = "Total",
        N = comma(sum(gt_yn$n, na.rm = TRUE)),
        "Pct" = round(sum(gt_yn$Pct, na.rm = TRUE), 1)
      )
    )

  
  kable(gt_yn_kable, 
        caption = Title, align = "lrr",
        booktabs = TRUE, longtable = TRUE, escape = TRUE) %>%
    add_indent(seq(1, nrow(gt_yn_kable) - 1)) %>% 
    kable_styling(latex_options = c("scale_down"))
}




create_kable_table_w_footnote <- function(df, group_by_vriable, Title){  
  CID_SYM <- rlang::ensym(group_by_vriable)
  
  gt_yn <- df %>%
    group_by(!!CID_SYM) %>%
    summarize(n = n(), percentage = 100 * n / nrow(.)) %>%
    ungroup() %>%
    mutate(answer = dplyr::recode(!!CID_SYM, !!!dict)) %>%
    replace_na(list(answer = "Skipped this Question")) %>%
    select(answer, n, percentage)
  
  gt_yn_kable <- gt_yn %>%
    mutate(
      percentage = round(percentage, 1),
      N = comma(n)
    ) %>%
    select(answer, N, percentage) %>%
    dplyr::rename(
      "Answer" = answer,
      "Pct" = percentage
    ) %>%
    bind_rows(
      tibble(
        Answer = "Total",
        N = comma(sum(gt_yn$n, na.rm = TRUE)),
        "Pct" = round(sum(gt_yn$Pct, na.rm = TRUE), 1)
      )
    )

  
  kable(gt_yn_kable, 
        caption = Title, align = "lrr",
        booktabs = TRUE, longtable = TRUE, escape = TRUE) %>%
    add_indent(seq(1, nrow(gt_yn_kable) - 1)) %>% 
    kable_styling(latex_options = c("scale_down")) %>% 
    footnote(general="Participants may select multiple responses or skip the question.", general_title = "")
}



#Histogram Function --- can't get them to work
hist_funct <- function(CID,Title, Xlab, Ylab) {
  CID_SYM <- rlang::ensym(CID)
  CVD_tib %>% dplyr::mutate(!!CID_SYM:=as.numeric(!!CID_SYM)) %>%
    filter(!is.na(!!CID_SYM)) %>% ggplot(aes(x=!!CID_SYM))+
     xlab(Xlab) + ylab(Ylab) + geom_histogram()+  ggtitle(Title)+
    geom_histogram(color="black")+ scale_y_continuous(breaks=pretty_breaks()) +
    geom_vline(aes(xintercept=mean(!!CID_SYM, na.rm=T)), colour="#2973A5" , linetype="solid")
  
}


date_hist_funct <- function(CID,Title, Xlab, Ylab){
  CID_SYM <- rlang::ensym(CID)
  covid_sect<- CVD_tib %>% dplyr::mutate(contracted_date2 = case_when(!is.na(!!CID_SYM) ~ paste0(!!CID_SYM, "-01"),
                                                          TRUE ~ NA))
  covid_sect$contracted_date2 <- as.Date(covid_sect$contracted_date2)

  covid_sect %>% 
    mutate(Date = ymd(contracted_date2)) %>% 
    ggplot(aes(contracted_date2)) +
    xlab(Xlab) + ylab(Ylab) + geom_histogram()+  ggtitle(Title)+
    geom_histogram(color="black")+ scale_y_continuous(breaks=pretty_breaks()) +
    geom_vline(aes(xintercept=mean(count, na.rm=T)), colour="#2973A5" , linetype="solid")
}




refactor_variables <- function(dataframe, variable_pattern, levels) {
  selected_variables <- grep(variable_pattern, names(dataframe), value = TRUE)
  for (variable_name in selected_variables) {
    dataframe[[variable_name]] <- factor(dataframe[[variable_name]], levels = levels)
  }
  return(dataframe)
}

# Define variable pattern and levels once you get to the table
# EX:
# variable_pattern <- "^D_114280729_"
# levels <- c(232063618, 948148236,  692824372, "Skipped this Question")
# 
# # Apply the function
# CVD_tib <- refactor_variables(CVD_tib, variable_pattern, levels)






```



\newpage

```{r COVID, warning=FALSE, echo=FALSE,  message=FALSE, fig.pos='H', results='asis'}


#COV1
CVD_tib$D_494226443 <- factor(CVD_tib$D_494226443,levels=c(104430631, 353358909, 178420302,"Skipped this Question"))
simple_funct_CVD(D_494226443, "Ever Have COVID-19")


#COV2
hist_funct(D_860011428, "Times Having COVID-19", "Times", "Frequency")
```


```{r First_time, warning=FALSE, echo=FALSE,  message=FALSE, fig.pos='H', results='asis'}
## First Time Having COVID 
had_covid= CVD_tib %>%  filter(as.numeric(D_860011428)>=1 | D_494226443=="353358909")



#COV3

# Need to incorporate the old month- year variables from BU/BUM
CVD_tib$year_month1 <- ifelse(!is.na(CVD_tib$D_980800222_V2_1_1), CVD_tib$D_980800222_V2_1_1,
                              ifelse(!is.na(CVD_tib$D_980800222_1_1_D_173502329_1) & !is.na(CVD_tib$D_980800222_1_1_D_366972678_1), 
                                     paste0(CVD_tib$D_980800222_1_1_D_366972678_1, "-", CVD_tib$D_980800222_1_1_D_173502329_1),
                                     ifelse(!is.na(CVD_tib$D_980800222_1_1_D_173502329_1_1) & !is.na(CVD_tib$D_980800222_1_1_D_366972678_1_1), 
                                     paste0(CVD_tib$D_980800222_1_1_D_366972678_1_1, "-", CVD_tib$D_980800222_1_1_D_173502329_1_1), NA)))


CVD_tib$year_month1 <- ym(CVD_tib$year_month1)


cat("\\FloatBarrier")
date_hist_funct(year_month1, "First Occurance of COVID-19", "Date", "Cases")


#COV4
CVD_tib$D_366980310_1_1 <- factor(CVD_tib$D_366980310_1_1,levels=c(104430631, 353358909, 178420302,"Skipped this Question"))
covid_once_funct(D_366980310_1_1, "Test Positive the First Time Having COVID-19")

  

#COV5
dt_select2 <- CVD_tib  %>%  filter((as.numeric(D_860011428)>=1| D_494226443=="353358909") & D_366980310_1_1!="353358909") %>%  select(Connect_ID, D_498462481_1_1) 
  
create_kable_table(dt_select2, D_498462481_1_1, "HealthCare Provider Confirm Diagnosis the First Time Having COVID-19")



#COV6
covid_once_funct(D_694503437_1_1, "Had Any Symptoms the First Time Having COVID-19")

#COV7
CVD_tib$D_451163824_1_1 <- factor(CVD_tib$D_451163824_1_1,levels=c(111520945, 548628123, 567908725, 760969884, 464631026,"Skipped this Question"))
one_skip_funct(D_451163824_1_1, "Worst Symptoms Interfere with Daily Activities the First Time Having COVID-19", D_694503437_1_1, "353358909")


#COV8
COVID_tib=as_tibble(had_covid)
COVID_tib8= COVID_tib  %>% filter(D_694503437_1_1=="353358909")



symptom_map <- c(
  D_705336878_1_1_D_705336878_1_1_D_406943303 = "Fever",
  D_705336878_1_1_D_705336878_1_1_D_760243464 = "Body Chills",
  D_705336878_1_1_D_705336878_1_1_D_423283665 = "Body or Muscle Aches",
  D_705336878_1_1_D_705336878_1_1_D_160627865 = "Weakness or Fatigue",
  D_705336878_1_1_D_705336878_1_1_D_960642359 = "Confusion",
  D_705336878_1_1_D_705336878_1_1_D_579409935 = "Trouble Sleeping",
  D_705336878_1_1_D_705336878_1_1_D_653630699 = "New Loss of Taste or Smell",
  D_705336878_1_1_D_705336878_1_1_D_367747257 = "Nasal Congestion",
  D_705336878_1_1_D_705336878_1_1_D_162167690 = "Sore Throat",
  D_705336878_1_1_D_705336878_1_1_D_756774083 = "Cough",
  D_705336878_1_1_D_705336878_1_1_D_679368947 = "Shortness of Breath",
  D_705336878_1_1_D_705336878_1_1_D_896163801 = "Chest Tightness",
  D_705336878_1_1_D_705336878_1_1_D_178318661 = "Stomach Pain",
  D_705336878_1_1_D_705336878_1_1_D_684149600 = "Dirrhea",
  D_705336878_1_1_D_705336878_1_1_D_524258008 = "Nausea",
  D_705336878_1_1_D_705336878_1_1_D_810340693 = "Vomiting",
  D_705336878_1_1_D_705336878_1_1_D_657566099 = "Rashes or Other Skin Changes",
  D_705336878_1_1_D_705336878_1_1_D_283776061 = "Conjunctivitis",
  D_705336878_1_1_D_705336878_1_1_D_807835037 = "Other"
)

# Need counts of all combinations
symptom_combos <- COVID_tib8 %>%
  select(Connect_ID, all_of(names(symptom_map))) %>%
  pivot_longer(
    cols = -Connect_ID,
    names_to = "symptom_code",
    values_to = "selected"
  ) %>%
  filter(selected == 1) %>%
  mutate(symptom = symptom_map[symptom_code]) %>%
  group_by(Connect_ID) %>%
  summarise(
    symptom_combo = paste(sort(symptom), collapse = "; "),
    .groups = "drop"
  ) %>%
  count(symptom_combo, name = "N") %>%
  arrange(desc(N))

# Too many counts of just 1, limiting the counts to 25 and up 
symptom_combos_filtered <- symptom_combos %>%
  filter(N >= 25)

# Want percentage in the N column as well, with the denominator of COVID-tib8
final_symptoms <- symptom_combos_filtered %>%
  mutate( `N (%)` = paste0(formatC(N, format = "d", big.mark = ","),  " (", 
      formatC(100 * N / nrow(COVID_tib8), format = "f", digits = 1), "%)")) %>%
  select(-N)  # don't need the old N column


kable(final_symptoms, 
    caption = "Had Any Sypmtoms the First Time Having COVID-19",
    col.names = c("Symptom(s)", "N"),
    row.names = FALSE, align = c("l", "r"),   booktabs = TRUE) %>%
    kable_styling(latex_options = c("hold_position", "scale_down"),  full_width = FALSE, font_size = 8) %>%  
  footnote(general="Due to the vast number of combinations, counts under 25 are supressed in this table.", general_title = "") %>% landscape()





#COV9
CVD_tib$D_928530823_1_1 <- factor(CVD_tib$D_928530823_1_1,levels=c(104430631, 353358909, 178420302,"Skipped this Question"))
one_skip_funct(D_928530823_1_1, "Experience Septic Shock the First Time Having COVID-19", D_694503437_1_1, "353358909")


#COV10
CVD_tib$D_108733102_1_1 <- factor(CVD_tib$D_928530823_1_1,levels=c(104430631, 353358909, 178420302,"Skipped this Question"))
one_skip_funct(D_108733102_1_1, "Diagnosed with Pneumonia the First Time Having COVID-19", D_694503437_1_1, "353358909")


#COV11
CVD_tib$D_389465772_1_1 <- factor(CVD_tib$D_928530823_1_1,levels=c(104430631, 353358909, 178420302,"Skipped this Question"))
one_skip_funct(D_389465772_1_1, "Diagnosed with Bood Clots the First Time Having COVID-19", D_694503437_1_1, "353358909")


#COV12
CVD_tib$D_775313030_1_1 <- factor(CVD_tib$D_928530823_1_1,levels=c(104430631, 353358909, 178420302,"Skipped this Question"))
one_skip_funct(D_775313030_1_1, "Overnight Hospital Stay the First Time Having COVID-19", D_694503437_1_1, "353358909")


#COV13
cat("\\FloatBarrier")
hist_funct(D_744230001_1_1, "Nights in the Hospital the First Time Having COVID-19", "Nights", "Count")

#COV14A
one_skip_funct(D_782396371_1_1, "Given Oxygen in the Hospital the First Time Having COVID-19", D_775313030_1_1, "353358909")

#COV14B
hist_funct(D_930944000_1_1, "Days Treated with Oxygen in the Hospital the First Time Having COVID-19", "Days", "Count")

#COV15A
one_skip_funct(D_984121390_1_1, "Given Breathing Tube or Ventilator in the Hospital the First Time Having COVID-19", D_775313030_1_1, "353358909")

#COV15B
cat("\\FloatBarrier")
hist_funct(D_930944000_1_1, "Days Treated with Breathing Tube or Ventilator the First Time Having COVID-19", "Days", "Count")

#COV16A
one_skip_funct(D_179406442_1_1, "ICU monitoring in the Hospital the First Time Having COVID-19", D_775313030_1_1, "353358909")

#COV16B
cat("\\FloatBarrier")
hist_funct(D_803339020_1_1, "Days Treated with ICU monitoring the First Time Having COVID-19", "Days", "Count")

#COV17A
one_skip_funct(D_893966847_1_1, "Receive Dialysis Treatment in the Hospital the First Time Having COVID-19", D_775313030_1_1, "353358909")

#COV17B
cat("\\FloatBarrier")
hist_funct(D_169509213_1_1, "Days Treated with Dialysis the First Time Having COVID-19", "Days", "Count")

```

```{r second_time, warning=FALSE, echo=FALSE,  message=FALSE, fig.pos='H', results='asis'}
## Second Time Having COVID
had_covid2= CVD_tib %>%  filter(as.numeric(D_860011428)>=2)

#COV3_2
CVD_tib$year_month2 <- ifelse(!is.na(CVD_tib$D_980800222_V2_2_2), CVD_tib$D_980800222_V2_2_2,
                              ifelse(!is.na(CVD_tib$D_980800222_2_2_D_173502329_2) & !is.na(CVD_tib$D_980800222_2_2_D_366972678_2), 
                                     paste0(CVD_tib$D_980800222_2_2_D_366972678_2, "-", CVD_tib$D_980800222_2_2_D_173502329_2),
                                     ifelse(!is.na(CVD_tib$D_980800222_2_2_D_173502329_2_2) & !is.na(CVD_tib$D_980800222_2_2_D_366972678_2_2), 
                                     paste0(CVD_tib$D_980800222_2_2_D_366972678_2_2, "-", CVD_tib$D_980800222_2_2_D_173502329_2_2), NA)))


CVD_tib$year_month2 <- ym(CVD_tib$year_month2)

cat("\\FloatBarrier")
date_hist_funct(year_month2, "Second Occurance of COVID-19", "Date", "Cases")



#COV4_2--CVD_tib$D_860011428)>=2
covid_twice_funct(D_366980310_2_2, "Test Positive the Second Time Having COVID-19")

  

#COV5
#covid_twice_funct(D_498462481_two, "COV5_2: HealthCare Provider Confirm Diagnosis the Second Time Having COVID-19")
dt_select2 <- CVD_tib  %>%  
    filter((as.numeric(D_860011428)>=2| D_494226443=="353358909") & D_366980310_2_2!="353358909") %>%  select(Connect_ID, D_498462481_2_2) 
create_kable_table(dt_select2, D_498462481_2_2, "HealthCare Provider Confirm Diagnosis the Second Time Having COVID-19")





#COV6
covid_twice_funct(D_694503437_2_2, "Had Any Symptoms the Second Time Having COVID-19")

#COV7
CVD_tib$D_451163824_2_2 <- factor(CVD_tib$D_451163824_2_2,levels=c(111520945, 548628123, 567908725, 760969884, 464631026,"Skipped this Question"))
one_skip_funct(D_451163824_2_2, "Worst Symptoms Interfere with Daily Activities the Second Time Having COVID-19", D_694503437_2_2, "353358909")





#COV8
COVID_tib=as_tibble(had_covid)
COVID_tib8= COVID_tib  %>%  filter(D_694503437_2_2=="353358909") 

symptom_map <- c(
  D_705336878_2_2_D_705336878_2_2_D_406943303 = "Fever",
  D_705336878_2_2_D_705336878_2_2_D_760243464 = "Body Chills",
  D_705336878_2_2_D_705336878_2_2_D_423283665 = "Body or Muscle Aches",
  D_705336878_2_2_D_705336878_2_2_D_160627865 = "Weakness or Fatigue",
  D_705336878_2_2_D_705336878_2_2_D_960642359 = "Confusion",
  D_705336878_2_2_D_705336878_2_2_D_579409935 = "Trouble Sleeping",
  D_705336878_2_2_D_705336878_2_2_D_653630699 = "New Loss of Taste or Smell",
  D_705336878_2_2_D_705336878_2_2_D_367747257 = "Nasal Congestion",
  D_705336878_2_2_D_705336878_2_2_D_162167690 = "Sore Throat",
  D_705336878_2_2_D_705336878_2_2_D_756774083 = "Cough",
  D_705336878_2_2_D_705336878_2_2_D_679368947 = "Shortness of Breath",
  D_705336878_2_2_D_705336878_2_2_D_896163801 = "Chest Tightness",
  D_705336878_2_2_D_705336878_2_2_D_178318661 = "Stomach Pain",
  D_705336878_2_2_D_705336878_2_2_D_684149600 = "Dirrhea",
  D_705336878_2_2_D_705336878_2_2_D_524258008 = "Nausea",
  D_705336878_2_2_D_705336878_2_2_D_810340693 = "Vomiting",
  D_705336878_2_2_D_705336878_2_2_D_657566099 = "Rashes or Other Skin Changes",
  D_705336878_2_2_D_705336878_2_2_D_283776061 = "Conjunctivitis",
  D_705336878_2_2_D_705336878_2_2_D_807835037 = "Other"
)

# Need counts of all combinations
symptom_combos <- COVID_tib8 %>%
  select(Connect_ID, all_of(names(symptom_map))) %>%
  pivot_longer(
    cols = -Connect_ID,
    names_to = "symptom_code",
    values_to = "selected"
  ) %>%
  filter(selected == 1) %>%
  mutate(symptom = symptom_map[symptom_code]) %>%
  group_by(Connect_ID) %>%
  summarise(
    symptom_combo = paste(sort(symptom), collapse = "; "),
    .groups = "drop"
  ) %>%
  count(symptom_combo, name = "N") %>%
  arrange(desc(N))

# Too many counts of just 1, limiting the counts to 25 and up 
symptom_combos_filtered <- symptom_combos %>%
  filter(N >= 25)

# Want percentage in the N column as well, with the denominator of COVID-tib8
final_symptoms <- symptom_combos_filtered %>%
  mutate( `N (%)` = paste0(formatC(N, format = "d", big.mark = ","),  " (", 
      formatC(100 * N / nrow(COVID_tib8), format = "f", digits = 1), "%)")) %>%
  select(-N)  # don't need the old N column


kable(final_symptoms, 
    caption = "Had Any Sypmtoms the Second Time Having COVID-19",
    col.names = c("Symptom(s)", "N"),
    row.names = FALSE, align = c("l", "r"),   booktabs = TRUE) %>%
    kable_styling(latex_options = c("hold_position", "scale_down"), full_width = FALSE, font_size = 8) %>%  
  footnote(general="Due to the vast number of combinations, counts under 25 are supressed in this table.", general_title = "") %>% landscape()



#COV9
one_skip_funct(D_928530823_2_2, "Experience Septic Shock the Second Time Having COVID-19", D_694503437_2_2, "353358909")

#COV10
one_skip_funct(D_108733102_2_2, "Diagnosed with Pneumonia the Second Time Having COVID-19", D_694503437_2_2, "353358909")

#COV11
one_skip_funct(D_389465772_2_2, "Diagnosed with Bood Clots the Second Time Having COVID-19", D_694503437_2_2, "353358909")

#COV12
one_skip_funct(D_775313030_2_2, "Overnight Hospital Stay the Second Time Having COVID-19", D_694503437_2_2, "353358909")

#COV13
cat("\\FloatBarrier")
hist_funct(D_744230001_2_2, "Nights in the Hospital the Second Time Having COVID-19", "Nights", "Count")

#COV14A
one_skip_funct(D_782396371_2_2, "Given Oxygen in the Hospital the Second Time Having COVID-19", D_775313030_2_2, "353358909")

#COV14B
cat("\\FloatBarrier")
hist_funct(D_930944000_2_2, "Days Treated with Oxygen in the Hospital the Second Time Having COVID-19", "Days", "Count")

#COV15A
one_skip_funct(D_984121390_2_2, "Given Breathing Tube or Ventilator in the Hospital the Second Time Having COVID-19", D_775313030_2_2, "353358909")

#COV15B
cat("\\FloatBarrier")
hist_funct(D_930944000_2_2, "Days Treated with Breathing Tube or Ventilator the Second Time Having COVID-19", "Days", "Count")

#COV16A
one_skip_funct(D_179406442_2_2, "ICU monitoring in the Hospital the Second Time Having COVID-19", D_775313030_2_2, "353358909")

#COV16B
cat("\\FloatBarrier")
hist_funct(D_803339020_2_2, "Days Treated with ICU monitoring the Second Time Having COVID-19", "Days", "Count")

#COV17A
one_skip_funct(D_893966847_2_2, "Receive Dialysis Treatment in the Hospital the Second Time Having COVID-19", D_775313030_2_2, "353358909")

#COV17B-- no one answered yet 
cat("\\FloatBarrier")
hist_funct(D_169509213_2_2, "Days Treated with Dialysis the Second Time Having COVID-19", "Days", "Count")
```


```{r grids, warning=FALSE, echo=FALSE,  message=FALSE}

##Third Time Having COVID--- not doing just yet 


#GRID COV19A
dt_COV19A= COVID_tib %>% filter(D_694503437_1_1=="353358909" | D_694503437_2_2=="353358909" | D_694503437_3_3=="353358909")

which_symptA1 <-dt_COV19A %>%  
  mutate(symptom= case_when(D_847578001_D_488415137==244354126 ~ "Never Experienced",
                            D_847578001_D_488415137==724612102 ~ "Currently Experiencing",
                            D_847578001_D_488415137==178780048 ~ "Previously Experienced",
                            TRUE   ~ "Skipped this question"),
         symptom = factor(symptom,levels=c("Never Experienced", "Previously Experienced",  "Currently Experiencing", "Skipped this question")))

create_kable_table(which_symptA1, symptom, "Experienced Lost of Taste or Smell Since COVID-19 Diagnosis")


######
which_symptA2= dt_COV19A %>%  mutate(symptom= case_when(D_847578001_D_167695804==244354126 ~ "Never Experienced",
                                                      D_847578001_D_167695804==724612102 ~ "Currently Experiencing",
                                                      D_847578001_D_167695804==178780048 ~ "Previously Experienced",
                                             TRUE   ~ "Skipped this question"),
         symptom = factor(symptom,levels=c("Never Experienced", "Previously Experienced",  "Currently Experiencing", "Skipped this question")))

create_kable_table(which_symptA2, symptom, "Experienced Appetite Changes Since COVID-19 Diagnosis")


######
which_symptA3= dt_COV19A %>%  mutate(symptom= case_when(D_847578001_D_730334054==244354126 ~ "Never Experienced",
                                                      D_847578001_D_730334054==724612102 ~ "Currently Experiencing",
                                                      D_847578001_D_730334054==178780048 ~ "Previously Experienced",
                                             TRUE   ~ "Skipped this question"),
         symptom = factor(symptom,levels=c("Never Experienced", "Previously Experienced",  "Currently Experiencing", "Skipped this question")))

create_kable_table(which_symptA3, symptom, "Experienced Feeling More Tired than Usual Since COVID-19 Diagnosis")


######
which_symptA4= dt_COV19A %>%  mutate(symptom= case_when(D_847578001_D_215996690==244354126 ~ "Never Experienced",
                                                      D_847578001_D_215996690==724612102 ~ "Currently Experiencing",
                                                      D_847578001_D_215996690==178780048 ~ "Previously Experienced",
                                             TRUE   ~ "Skipped this question"),
         symptom = factor(symptom,levels=c("Never Experienced", "Previously Experienced",  "Currently Experiencing", "Skipped this question")))

create_kable_table(which_symptA4, symptom, "Experienced Trouble Remembering Things Since COVID-19 Diagnosis")



######
which_symptA5= dt_COV19A %>%  mutate(symptom= case_when(D_847578001_D_462737492==244354126 ~ "Never Experienced",
                                                      D_847578001_D_462737492==724612102 ~ "Currently Experiencing",
                                                      D_847578001_D_462737492==178780048 ~ "Previously Experienced",
                                             TRUE   ~ "Skipped this question"),
         symptom = factor(symptom,levels=c("Never Experienced", "Previously Experienced",  "Currently Experiencing", "Skipped this question")))

create_kable_table(which_symptA5, symptom, "Experienced Trouble Paying Attention Since COVID-19 Diagnosis")



######
which_symptA6= dt_COV19A %>%  mutate(symptom= case_when(D_847578001_D_469675296==244354126 ~ "Never Experienced",
                                                      D_847578001_D_469675296==724612102 ~ "Currently Experiencing",
                                                      D_847578001_D_469675296==178780048 ~ "Previously Experienced",
                                             TRUE   ~ "Skipped this question"),
         symptom = factor(symptom,levels=c("Never Experienced", "Previously Experienced",  "Currently Experiencing", "Skipped this question")))

create_kable_table(which_symptA6, symptom, "Experienced Trouble Thinking or Making Decisions Since COVID-19 Diagnosis")





#GRID COVID19B
dt_COV19B= COVID_tib %>% filter(D_694503437_1_1=="353358909" | D_694503437_2_2=="353358909" | D_694503437_3_3=="353358909") 



which_symptB1= dt_COV19B %>%  mutate(symptom= case_when(D_136730307_D_962475128==244354126 ~ "Never Experienced",
                                                      D_136730307_D_962475128==724612102 ~ "Currently Experiencing",
                                                      D_136730307_D_962475128==178780048 ~ "Previously Experienced",
                                             TRUE   ~ "Skipped this question"),
         symptom = factor(symptom,levels=c("Never Experienced", "Previously Experienced",  "Currently Experiencing", "Skipped this question")))

create_kable_table(which_symptB1, symptom, "Experienced Shortness of Breath Since COVID-19 Diagnosis")


########
which_symptB2= dt_COV19B %>%  mutate(symptom= case_when(D_136730307_D_989576239==244354126 ~ "Never Experienced",
                                                      D_136730307_D_989576239==724612102 ~ "Currently Experiencing",
                                                      D_136730307_D_989576239==178780048 ~ "Previously Experienced",
                                             TRUE   ~ "Skipped this question"),
         symptom = factor(symptom,levels=c("Never Experienced", "Previously Experienced",  "Currently Experiencing", "Skipped this question")))

create_kable_table(which_symptB2, symptom, "Experienced Inability to Exercise at Normal Level Since COVID-19 Diagnosis")



########
which_symptB3= dt_COV19B %>%  mutate(symptom= case_when(D_136730307_D_338613869==244354126 ~ "Never Experienced",
                                                      D_136730307_D_338613869==724612102 ~ "Currently Experiencing",
                                                      D_136730307_D_338613869==178780048 ~ "Previously Experienced",
                                             TRUE   ~ "Skipped this question"),
         symptom = factor(symptom,levels=c("Never Experienced", "Previously Experienced",  "Currently Experiencing", "Skipped this question")))

create_kable_table(which_symptB3, symptom, "Experienced Inability to Return to School or Work Since COVID-19 Diagnosis")



########
which_symptB4= dt_COV19B %>%  mutate(symptom= case_when(D_136730307_D_126794793==244354126 ~ "Never Experienced",
                                                      D_136730307_D_126794793==724612102 ~ "Currently Experiencing",
                                                      D_136730307_D_126794793==178780048 ~ "Previously Experienced",
                                             TRUE   ~ "Skipped this question"),
         symptom = factor(symptom,levels=c("Never Experienced", "Previously Experienced",  "Currently Experiencing", "Skipped this question")))

create_kable_table(which_symptB4, symptom, "Experienced Inability to Return to Usual Activities Since COVID-19 Diagnosis")




########
which_symptB5= dt_COV19B %>%  mutate(symptom= case_when(D_136730307_D_218793117==244354126 ~ "Never Felt",
                                                      D_136730307_D_218793117==724612102 ~ "Currently Feeling",
                                                      D_136730307_D_218793117==178780048 ~ "Previously Felt",
                                             TRUE   ~ "Skipped this question"),
         symptom = factor(symptom,levels=c("Never Felt", "Previously Felt",  "Currently Feeling", "Skipped this question")))

create_kable_table(which_symptB5, symptom, "Experienced Feeling Weak, Tired, or Sick after Physical Activity Since COVID-19 Diagnosis")










#GRID COVID19C
dt_COV19C= COVID_tib %>% filter(D_694503437_1_1=="353358909" | D_694503437_2_2=="353358909" | D_694503437_3_3=="353358909")


which_sympt1= dt_COV19C %>%  mutate(symptom= case_when(D_751358419_D_524096053==244354126 ~ "Never Felt",
                                                   D_751358419_D_524096053==724612102 ~ "Currently Feeling",
                                                   D_751358419_D_524096053==178780048 ~ "Previously Felt",
                                                      TRUE   ~ "Skipped this question"),
         symptom = factor(symptom,levels=c("Never Felt", "Previously Felt",  "Currently Feeling", "Skipped this question")))

create_kable_table(which_sympt1, symptom, "Experienced Feeling Lightheaded or Dizzy Since COVID-19 Diagnosis")



######

which_sympt2= dt_COV19C %>%  mutate(symptom= case_when(D_751358419_D_814101706==244354126 ~ "Never Experienced",
                                                   D_751358419_D_814101706==724612102 ~ "Currently Experiencing",
                                                   D_751358419_D_814101706==178780048 ~ "Previously Experienced", 
                                                      TRUE   ~ "Skipped this question"),
         symptom = factor(symptom,levels=c("Never Experienced", "Previously Experienced",  "Currently Experiencing", "Skipped this question")))

create_kable_table(which_sympt2, symptom, "Experienced Periods of Racing Heart Rate Since COVID-19 Diagnosis")




######

which_sympt3= dt_COV19C %>%  mutate(symptom= case_when(D_751358419_D_635026188==244354126 ~ "Never Experienced",
                                                       D_751358419_D_635026188==724612102 ~ "Currently Experiencing",
                                                       D_751358419_D_635026188==178780048 ~ "Previously Experienced", 
                                                       TRUE   ~ "Skipped this question"),
         symptom = factor(symptom,levels=c("Never Experienced", "Previously Experienced",  "Currently Experiencing", "Skipped this question")))

create_kable_table(which_sympt3, symptom, "Experienced Trouble Sleeping Since COVID-19 Diagnosis")



######

which_sympt4= dt_COV19C %>%  mutate(symptom= case_when(D_751358419_D_238135048==244354126 ~ "Never Experienced",
                                                       D_751358419_D_238135048==724612102 ~ "Currently Experiencing",
                                                       D_751358419_D_238135048==178780048 ~ "Previously Experienced", 
                                                       TRUE   ~ "Skipped this question"),
         symptom = factor(symptom,levels=c("Never Experienced", "Previously Experienced",  "Currently Experiencing", "Skipped this question")))

create_kable_table(which_sympt4, symptom, "Experienced Changes to Mood or Emotion Since COVID-19 Diagnosis")



######

which_sympt5= dt_COV19C %>%  mutate(symptom= case_when(D_751358419_D_632714520==244354126 ~ "Never Experienced",
                                                       D_751358419_D_632714520==724612102 ~ "Currently Experiencing",
                                                       D_751358419_D_632714520==178780048 ~ "Previously Experienced", 
                                                       TRUE   ~ "Skipped this question"),
         symptom = factor(symptom,levels=c("Never Experienced", "Previously Experienced",  "Currently Experiencing", "Skipped this question")))

create_kable_table(which_sympt5, symptom, "Experienced Muscle Aches Since COVID-19 Diagnosis")







#COV19C6A
dt_select2 <- CVD_tib  %>%  filter(D_694503437_1_1=="353358909" | D_694503437_2_2=="353358909" | D_694503437_3_3=="353358909")

create_kable_table(dt_select2, D_110872086_D_110872086, "Experienced Any Other Symptoms Since COVID-19 Diagnosis")



#COV19C6B
one_skip_funct(D_591826144, "Still Experiencing the Other Symptoms Since COVID-19 Diagnosis", D_110872086_D_110872086, "707601969")

```


```{r experiences, warning=FALSE, echo=FALSE,  message=FALSE}

#GRID 
#COV20A1

#levels <- c(232063618, 948148236,  692824372, "Skipped this Question")

# Apply the function
#CVD_tib <- refactor_variables(CVD_tib, variable_pattern, levels)


two_skip_funct(D_114280729_D_374567479, "Length of Time Lost of Taste or Smell Experienced", D_847578001_D_488415137, "724612102", D_847578001_D_488415137, "178780048")


#COV20A2
two_skip_funct(D_114280729_D_966214244, "Length of Time Feeling More Tired Experienced", D_847578001_D_730334054, "724612102", D_847578001_D_730334054, "178780048")

#COV20A3
two_skip_funct(D_114280729_D_109223043, "Length of Time Having Trouble Remembering Things", D_847578001_D_215996690, "724612102", D_847578001_D_215996690, "178780048")

#COV20A4
two_skip_funct(D_114280729_D_368669706, "Length of Time Having Trouble Paying Attention", D_847578001_D_462737492, "724612102", D_847578001_D_462737492, "178780048")

#COV20A5
two_skip_funct(D_114280729_D_605818246, "Length of Time Having Trouble Thinking or Making Decisions", D_847578001_D_469675296, "724612102", D_847578001_D_469675296, "178780048")

#COV20A6
two_skip_funct(D_114280729_D_790860504, "Length of Time Appetite Changes Experienced", D_847578001_D_167695804, "724612102", D_847578001_D_167695804, "178780048")

#COV20A7
two_skip_funct(D_114280729_D_336856410, "Length of Time Feeling of Lightheadedness or Dizziness Experienced", D_751358419_D_524096053, "724612102", D_751358419_D_524096053, "178780048")

#COV20A8
two_skip_funct(D_114280729_D_518602598, "Length of Time Periods of Racing Heart Rate Experienced", D_751358419_D_814101706, "724612102", D_751358419_D_814101706, "178780048")

#COV20A9
two_skip_funct(D_114280729_D_770190369, "Length of Time Shortness of Breath Experienced", D_136730307_D_962475128, "724612102", D_136730307_D_962475128, "178780048")

#COV20A10
two_skip_funct(D_114280729_D_994153376, "Length of Time Inability to Exercise at Usual Level Experienced", D_136730307_D_989576239, "724612102", D_136730307_D_989576239, "178780048")

#COV20A11
two_skip_funct(D_114280729_D_481587023, "Length of Time Inability to Return to Work or School Experienced", D_136730307_D_338613869, "724612102", D_136730307_D_338613869, "178780048")

#COV20A12
two_skip_funct(D_114280729_D_590361055, "Length of Time Inability to Return to Work or School Experienced", D_136730307_D_126794793, "724612102", D_136730307_D_126794793, "178780048")

#COV20A13
two_skip_funct(D_114280729_D_108389123, "Length of Time Feeling Weak, Tired, or Sick after Physical Exercise Experienced", D_136730307_D_218793117, "724612102", D_136730307_D_218793117, "178780048")

#COV20A14
two_skip_funct(D_114280729_D_747085418, "Length of Time Trouble Sleeping Experienced", D_751358419_D_635026188, "724612102", D_751358419_D_635026188, "178780048")

#COV20A15
two_skip_funct(D_114280729_D_702905707, "Length of Time Changes in Mood and Emotions Experienced", D_751358419_D_238135048, "724612102", D_751358419_D_238135048, "178780048")

#COV20A16
two_skip_funct(D_114280729_D_986119909, "Length of Time Muscle Aches Experienced", D_751358419_D_632714520, "724612102", D_751358419_D_632714520, "178780048")





#COV20A17
one_skip_funct(D_934384452, "Length of Time Other Symptom Experienced", D_110872086_D_110872086, "707601969")

```


```{r recovery, warning=FALSE, echo=FALSE,  message=FALSE, fig.pos='H', results='asis'}

#COV21
one_skip_funct(D_273371161, "Feel Like You Have Fully Recovered from COVID-19", D_110872086_D_110872086, "707601969")

#COV22

COV22_Months=hist_funct(D_959877599_D_700620868, "Time to Fully Recover from COVID-19", "Months", "Count")
COV22_Days=hist_funct(D_959877599_D_908044428, "Time to Fully Recover from COVID-19", "Days", "Count")
grid.arrange(COV22_Months, COV22_Days, nrow=2)

#GRID  COV23A1

variable_pattern <- "^D_114280729_"
levels <- c(232063618, 948148236,  692824372, "Skipped this Question")

# Apply the function
#CVD_tib <- refactor_variables(CVD_tib, variable_pattern, levels)




#COV23A1
which_COV23A1= CVD_tib  %>%  filter(D_494226443!="353358909" | D_498462481_1_1=="104430631"| D_694503437_1_1=="104430631") %>%  
                     mutate(answer= case_when(D_813989715_D_874168085==770236544 ~ "No, I never experienced this",
                                              D_813989715_D_874168085==931688701 ~ "Yes, I am experiencing this now",
                                              D_813989715_D_874168085==586272115 ~ "Yes, I experienced this in the past",
                                              TRUE   ~ "Skipped this Question"),
                            answer = factor(answer, levels= c("No, I never experienced this", "Yes, I am experiencing this now", 
                                                              "Yes, I experienced this in the past", "Skipped this Question")))
   
create_kable_table(which_COV23A1, answer, "Experienced Lost of Taste or Smell Since 2020")
 
 

#COV23A2
     
which_COV23A2= CVD_tib  %>%  filter(D_494226443!="353358909" | D_498462481_1_1=="104430631"| D_694503437_1_1=="104430631") %>%  
                     mutate(answer= case_when(D_813989715_D_283112988==770236544 ~ "No, I never experienced this",
                                              D_813989715_D_283112988==931688701 ~ "Yes, I am experiencing this now",
                                              D_813989715_D_283112988==586272115 ~ "Yes, I experienced this in the past",
                                              TRUE   ~ "Skipped this Question"),
                            answer = factor(answer, levels= c("No, I never experienced this", "Yes, I am experiencing this now", 
                                                              "Yes, I experienced this in the past", "Skipped this Question")))
 
create_kable_table(which_COV23A2, answer, "Experienced Appetite Changes Since 2020")



#COV23A3

which_COV23A3= CVD_tib  %>%  filter(D_494226443!="353358909" | D_498462481_1_1=="104430631"| D_694503437_1_1=="104430631") %>%  
                     mutate(answer= case_when(D_813989715_D_580629349==770236544 ~ "No, I never experienced this",
                                              D_813989715_D_580629349==931688701 ~ "Yes, I am experiencing this now",
                                              D_813989715_D_580629349==586272115 ~ "Yes, I experienced this in the past",
                                              TRUE   ~ "Skipped this Question"),
                            answer = factor(answer, levels= c("No, I never experienced this", "Yes, I am experiencing this now", 
                                                              "Yes, I experienced this in the past", "Skipped this Question")))

create_kable_table(which_COV23A3, answer, "Feeling More Tired than Usual Since 2020") 
 


#COV23A4
   
which_COV23A4= CVD_tib  %>%  filter(D_494226443!="353358909" | D_498462481_1_1=="104430631"| D_694503437_1_1=="104430631") %>%  
                     mutate(answer= case_when(D_813989715_D_151327643==770236544 ~ "No, I never experienced this",
                                              D_813989715_D_151327643==931688701 ~ "Yes, I am experiencing this now",
                                              D_813989715_D_151327643==586272115 ~ "Yes, I experienced this in the past",
                                              TRUE   ~ "Skipped this Question"),
                            answer = factor(answer, levels= c("No, I never experienced this", "Yes, I am experiencing this now", 
                                                              "Yes, I experienced this in the past", "Skipped this Question")))
 
create_kable_table(which_COV23A4, answer, "Having Trouble Remebering Things Since 2020")  


#COV23A5
   
which_COV23A5= CVD_tib  %>%  filter(D_494226443!="353358909" | D_498462481_1_1=="104430631"| D_694503437_1_1=="104430631") %>%  
                     mutate(answer= case_when(D_813989715_D_440872808==770236544 ~ "No, I never experienced this",
                                              D_813989715_D_440872808==931688701 ~ "Yes, I am experiencing this now",
                                              D_813989715_D_440872808==586272115 ~ "Yes, I experienced this in the past",
                                              TRUE   ~ "Skipped this Question"),
                            answer = factor(answer, levels= c("No, I never experienced this", "Yes, I am experiencing this now",
                                                              "Yes, I experienced this in the past", "Skipped this Question")))
 
 create_kable_table(which_COV23A5, answer, "Having Trouble Paying Attention Since 2020")


#COV23A6
   
which_COV23A6= CVD_tib  %>%  filter(D_494226443!="353358909" | D_498462481_1_1=="104430631"| D_694503437_1_1=="104430631") %>%  
                     mutate(answer= case_when(D_813989715_D_874223830==770236544 ~ "No, I never experienced this",
                                              D_813989715_D_874223830==931688701 ~ "Yes, I am experiencing this now",
                                              D_813989715_D_874223830==586272115 ~ "Yes, I experienced this in the past",
                                              TRUE   ~ "Skipped this Question"),
                            answer = factor(answer, levels= c("No, I never experienced this", "Yes, I am experiencing this now", 
                                                              "Yes, I experienced this in the past", "Skipped this Question")))
 
  create_kable_table(which_COV23A6, answer, "Having Trouble Thinking or Making Decisions Since 2020")




#GRID  COV23B1
#COV23B1
   
which_COV23B1= CVD_tib  %>%  filter(D_494226443!="353358909" | D_498462481_1_1=="104430631"| D_694503437_1_1=="104430631") %>%  
                     mutate(answer= case_when(D_857165713_D_847529903==770236544 ~ "No, I never experienced this",
                                              D_857165713_D_847529903==931688701 ~ "Yes, I am experiencing this now",
                                              D_857165713_D_847529903==586272115 ~ "Yes, I experienced this in the past",
                                              TRUE   ~ "Skipped this Question"),
                            answer = factor(answer, levels= c("No, I never experienced this", "Yes, I am experiencing this now", 
                                                              "Yes, I experienced this in the past", "Skipped this Question")))
 
   create_kable_table(which_COV23B1, answer, "Felt Dizziness or Shortness of Breath Since 2020")


#COV23B2
   
which_COV23B2= CVD_tib  %>%  filter(D_494226443!="353358909" | D_498462481_1_1=="104430631"| D_694503437_1_1=="104430631") %>%  
                     mutate(answer= case_when(D_857165713_D_219358831==770236544 ~ "No, I never experienced this",
                                              D_857165713_D_219358831==931688701 ~ "Yes, I am experiencing this now",
                                              D_857165713_D_219358831==586272115 ~ "Yes, I experienced this in the past",
                                              TRUE   ~ "Skipped this Question"),
                            answer = factor(answer, levels= c("No, I never experienced this", "Yes, I am experiencing this now", 
                                                              "Yes, I experienced this in the past", "Skipped this Question")))
 
create_kable_table(which_COV23B2, answer, "Experienced Periods of Raching of Heart Rate Since 2020")
 

#COV23B3
   
which_COV23B3= CVD_tib  %>%  filter(D_494226443!="353358909" | D_498462481_1_1=="104430631"| D_694503437_1_1=="104430631") %>%  
                     mutate(answer= case_when(D_857165713_D_636367178==770236544 ~ "No, I never experienced this",
                                              D_857165713_D_636367178==931688701 ~ "Yes, I am experiencing this now",
                                              D_857165713_D_636367178==586272115 ~ "Yes, I experienced this in the past",
                                              TRUE   ~ "Skipped this Question"),
                            answer = factor(answer, levels= c("No, I never experienced this", "Yes, I am experiencing this now", 
                                                              "Yes, I experienced this in the past", "Skipped this Question")))
 
create_kable_table(which_COV23B3, answer, "Experienced Shortness of Breath Since 2020") 


#COV23B4
   
which_COV23B4= CVD_tib  %>%  filter(D_494226443!="353358909" | D_498462481_1_1=="104430631"| D_694503437_1_1=="104430631") %>%  
                     mutate(answer= case_when(D_857165713_D_243443780==770236544 ~ "No, I never experienced this",
                                              D_857165713_D_243443780==931688701 ~ "Yes, I am experiencing this now",
                                              D_857165713_D_243443780==586272115 ~ "Yes, I experienced this in the past",
                                              TRUE   ~ "Skipped this Question"),
                            answer = factor(answer, levels= c("No, I never experienced this", "Yes, I am experiencing this now", 
                                                              "Yes, I experienced this in the past", "Skipped this Question")))
 
 create_kable_table(which_COV23B4, answer, "Experienced Feeling Weak, Tired, or Sick after Physical Activity Since 2020")


#COV23B5
   
which_COV23B5= CVD_tib  %>%  filter(D_494226443!="353358909" | D_498462481_1_1=="104430631"| D_694503437_1_1=="104430631") %>%  
                     mutate(answer= case_when(D_857165713_D_357462273==770236544 ~ "No, I never experienced this",
                                              D_857165713_D_357462273==931688701 ~ "Yes, I am experiencing this now",
                                              D_857165713_D_357462273==586272115 ~ "Yes, I experienced this in the past",
                                              TRUE   ~ "Skipped this Question"),
                            answer = factor(answer, levels= c("No, I never experienced this", "Yes, I am experiencing this now", 
                                                              "Yes, I experienced this in the past", "Skipped this Question")))
 
 create_kable_table(which_COV23B5, answer, "Having Trouble Sleeping Since 2020") 


#COV23B6
   
which_COV23B6= CVD_tib  %>%  filter(D_494226443!="353358909" | D_498462481_1_1=="104430631"| D_694503437_1_1=="104430631") %>%  
                     mutate(answer= case_when(D_857165713_D_638380747==770236544 ~ "No, I never experienced this",
                                              D_857165713_D_638380747==931688701 ~ "Yes, I am experiencing this now",
                                              D_857165713_D_638380747==586272115 ~ "Yes, I experienced this in the past",
                                              TRUE   ~ "Skipped this Question"),
                            answer = factor(answer, levels= c("No, I never experienced this", "Yes, I am experiencing this now", 
                                                              "Yes, I experienced this in the past", "Skipped this Question")))
 
 create_kable_table(which_COV23B6, answer, "Experienced Changes in Mood or Emotion Since 2020") 


#COV23B7
   
which_COV23B7= CVD_tib  %>%  filter(D_494226443!="353358909" | D_498462481_1_1=="104430631"| D_694503437_1_1=="104430631") %>%  
                     mutate(answer= case_when(D_857165713_D_187399900==770236544 ~ "No, I never experienced this",
                                              D_857165713_D_187399900==931688701 ~ "Yes, I am experiencing this now",
                                              D_857165713_D_187399900==586272115 ~ "Yes, I experienced this in the past",
                                              TRUE   ~ "Skipped this Question"),
                            answer = factor(answer, levels= c("No, I never experienced this", "Yes, I am experiencing this now", 
                                                              "Yes, I experienced this in the past", "Skipped this Question")))
 
  create_kable_table(which_COV23B7, answer, "Experienced Muscle Aches Since 2020") 





#COV23B8A
simple_funct_CVD(D_424718457_D_424718457, "Experienced any Other Symptom Since 2020")

#CVD_tib %>%  select(D_424718457_D_157417942) %>% filter(!is.na(D_424718457_D_157417942)) %>% gt() %>% cols_label(D_424718457_D_157417942= md("**Table 126: Experienced What Other Symptom Since 2020**"))


#COV238B
one_skip_funct(D_368715875, "Table 126: Still Experiencing Said Other Symptom", D_424718457_D_424718457, "707601969")

   variable_pattern <- "^D_749956170_"
levels <- c(232063618, 948148236,  692824372, "Skipped this Question")

# Apply the function
CVD_tib <- refactor_variables(CVD_tib, variable_pattern, levels)

#GRID
#COV24A1
two_skip_funct(D_749956170_D_527872064 , "Length of Time Experiencing Loss of Taste or Smell", D_813989715_D_874168085,"931688701",D_813989715_D_874168085,"586272115")


#COV24A2
two_skip_funct(D_749956170_D_691752394 , "Length of Time Experiencing Appetite Changes", D_813989715_D_283112988,"931688701",D_813989715_D_283112988,"586272115")


#COV24A3
two_skip_funct(D_749956170_D_143206081 , "Length of Time Feeling More Tired Than Usual", D_813989715_D_580629349,"931688701",D_813989715_D_580629349,"586272115")


#COV24A4
two_skip_funct(D_749956170_D_431203595 , "Length of Time Having Trouble Remembering Things", D_813989715_D_151327643,"931688701",D_813989715_D_151327643,"586272115")



#COV24A5
two_skip_funct(D_749956170_D_516899143 , "Length of Time Having Trouble Paying Attention", D_813989715_D_440872808,"931688701",D_813989715_D_440872808,"586272115")



#COV24A6
two_skip_funct(D_749956170_D_223008071 , "Length of Time Having Trouble Thinking or Making Decision", D_813989715_D_874223830,"931688701",D_813989715_D_874223830,"586272115")



#COV24A7
two_skip_funct(D_749956170_D_599862694 , "Length of Time Experiencing Feeling Lightheaded and Dizzy", D_857165713_D_847529903,"931688701",D_857165713_D_847529903,"586272115")



#COV24A8
two_skip_funct(D_749956170_D_860444009 , "Length of Time Experiencing Periods of Racing Heart Rate", D_857165713_D_219358831,"931688701",D_857165713_D_219358831,"586272115")



#COV24A9
two_skip_funct(D_749956170_D_246857412 , "Length of Time Experiencing Shortness of Breath", D_857165713_D_636367178,"931688701",D_857165713_D_636367178,"586272115")


#COV24A10
two_skip_funct(D_749956170_D_144819886 , "Length of Time Experiencing Feeling Weak, Tired or Sick after Physical Activity", D_857165713_D_243443780,"931688701",D_857165713_D_243443780,"586272115")


#COV24A11
two_skip_funct(D_749956170_D_304155106 , "Length of Time Having Trouble Sleeping", D_857165713_D_357462273,"931688701",D_857165713_D_357462273,"586272115")



#COV24A12
two_skip_funct(D_749956170_D_830581863 , "Length of Time Experiencing Changes in your Mood or Emotions", D_857165713_D_638380747,"931688701",D_857165713_D_638380747,"586272115")



#COV24A13
two_skip_funct(D_749956170_D_463689026 , "Length of Time Experiencing Muscle Aches", D_857165713_D_187399900,"931688701",D_857165713_D_187399900,"586272115")



```


```{r vaccine, warning=FALSE, echo=FALSE,  message=FALSE}
#COV25    
#Include both versions from earlier surveys
#CVD_tib <- CVD_tib %>% mutate(D_890156588_V2 = ifelse(!is.na(D_890156588_V2), D_890156588_V2, D_890156588))

   COV25 <- CVD_tib  %>%  filter(d_822499427>as.Date("2022-12-1")) %>% 
  select(Connect_ID, D_890156588_V2) 
   
create_kable_table(COV25, D_890156588_V2, "Received COVID-19 Vaccination test 1") 

   

#COV26
#incorporate older versions
CVD_tib <- CVD_tib  %>%  mutate(D_877074400_V2 = ifelse(!is.na(D_877074400_V2), as.numeric(D_877074400_V2), as.numeric(D_877074400)))
cat("\\FloatBarrier")
hist_funct(D_877074400_V2, "Number of COVID-19 Vaccinations", "Vaccinations", "Count")
```


```{r vaccine_plots, warning=FALSE, echo=FALSE,  message=FALSE, fig.pos='H', results='asis'}
#COV27 (up to 10 vaccines)

CVD_tib$D_715581797_1_1 <- ifelse(!is.na(CVD_tib$D_715581797_1_1), CVD_tib$D_715581797_1_1, 
                                  ifelse(!is.na(CVD_tib$D_715581797_V2_1_1), CVD_tib$D_715581797_V2_1_1, CVD_tib$D_71558179_V2_1_1))
CVD_tib$D_715581797_2_2 <- ifelse(!is.na(CVD_tib$D_715581797_2_2), CVD_tib$D_715581797_2_2, 
                                  ifelse(!is.na(CVD_tib$D_715581797_V2_2_2), CVD_tib$D_715581797_V2_2_2, CVD_tib$D_71558179_V2_2_2))
CVD_tib$D_715581797_3_3 <- ifelse(!is.na(CVD_tib$D_715581797_3_3), CVD_tib$D_715581797_3_3, 
                                  ifelse(!is.na(CVD_tib$D_715581797_V2_3_3), CVD_tib$D_715581797_V2_3_3, CVD_tib$D_71558179_V2_3_3))
CVD_tib$D_715581797_4_4 <- ifelse(!is.na(CVD_tib$D_715581797_4_4), CVD_tib$D_715581797_4_4, 
                                  ifelse(!is.na(CVD_tib$D_715581797_V2_4_4), CVD_tib$D_715581797_V2_4_4, CVD_tib$D_71558179_V2_4_4))
CVD_tib$D_715581797_5_5 <- ifelse(!is.na(CVD_tib$D_715581797_5_5), CVD_tib$D_715581797_5_5, 
                                  ifelse(!is.na(CVD_tib$D_715581797_V2_5_5), CVD_tib$D_715581797_V2_5_5, CVD_tib$D_71558179_V2_5_5))
CVD_tib$D_715581797_6_6 <- ifelse(!is.na(CVD_tib$D_715581797_6_6), CVD_tib$D_715581797_6_6, 
                                  ifelse(!is.na(CVD_tib$D_715581797_V2_6_6), CVD_tib$D_715581797_V2_6_6, CVD_tib$D_71558179_V2_6_6))
CVD_tib$D_715581797_7_7 <- ifelse(!is.na(CVD_tib$D_715581797_7_7), CVD_tib$D_715581797_7_7, 
                                  ifelse(!is.na(CVD_tib$D_715581797_V2_7_7), CVD_tib$D_715581797_V2_7_7, CVD_tib$D_71558179_V2_7_7))
CVD_tib$D_715581797_8_8 <- ifelse(!is.na(CVD_tib$D_715581797_8_8), CVD_tib$D_715581797_8_8, 
                                  ifelse(!is.na(CVD_tib$D_715581797_V2_8_8), CVD_tib$D_715581797_V2_8_8, CVD_tib$D_71558179_V2_8_8))
CVD_tib$D_715581797_9_9 <- ifelse(!is.na(CVD_tib$D_715581797_9_9), CVD_tib$D_715581797_9_9, 
                                  ifelse(!is.na(CVD_tib$D_715581797_V2_9_9), CVD_tib$D_715581797_V2_9_9, CVD_tib$D_71558179_V2_9_9))

cat("\\FloatBarrier")
date_hist_funct(D_715581797_1_1, "Date of First COVID-19 vaccine", "Date", "Cases")
cat("\\FloatBarrier")
date_hist_funct(D_715581797_2_2, "Date of Second COVID-19 vaccine", "Date", "Cases")
cat("\\FloatBarrier")
date_hist_funct(D_715581797_3_3, "Date of Third COVID-19 vaccine", "Date", "Cases")

# cat("\\clearpage")
# cat("\\FloatBarrier")
# date_hist_funct(D_715581797_4_4, "Date of Fourth COVID-19 vaccine", "Date", "Cases")
# cat("\\FloatBarrier")
# date_hist_funct(D_715581797_5_5, "Date of Fifth COVID-19 vaccine", "Date", "Cases")
# cat("\\FloatBarrier")
# date_hist_funct(D_715581797_6_6, "Date of Sixth COVID-19 vaccine", "Date", "Cases")
# 
# cat("\\clearpage")
# cat("\\FloatBarrier")
# date_hist_funct(D_715581797_7_7, "Date of Seventh COVID-19 vaccine", "Date", "Cases")
# cat("\\FloatBarrier")
# date_hist_funct(D_715581797_8_8, "Date of Eighth COVID-19 vaccine", "Date", "Cases")
# cat("\\FloatBarrier")
# date_hist_funct(D_715581797_9_9, "Date of Ninth COVID-19 vaccine", "Date", "Cases")
```


```{r vaccine2, warning=FALSE, echo=FALSE,  message=FALSE, fig.pos='H', results='asis'}
#COV28
CVD_tib <- CVD_tib %>% mutate(vaccinated = ifelse(!is.na(D_890156588_V2), D_890156588_V2, D_890156588),
                              vacc_num = ifelse(!is.na(D_877074400_V2), as.numeric(D_877074400_V2), as.numeric(D_877074400)))

COV28_1 <- CVD_tib  %>%  filter(vaccinated=="353358909" & (vacc_num>=1)) 

create_kable_table(COV28_1, D_220055064_1_1_D_220055064_1_1, "Brand of First COVID-19 Vaccine") 




COV28_2 <- CVD_tib  %>%  filter(vaccinated=="353358909" & (vacc_num>=2)) 

create_kable_table(COV28_2, D_220055064_2_2_D_220055064_2_2, "Brand of Second COVID-19 Vaccine") 
   
   

COV28_3 <- CVD_tib  %>%  filter(vaccinated=="353358909" & (vacc_num>=3)) 

create_kable_table(COV28_3, D_220055064_3_3_D_220055064_3_3, "Brand of Third COVID-19 Vaccine")
   
   

COV28_4 <- CVD_tib  %>%  filter(vaccinated=="353358909" & (vacc_num>=4))

create_kable_table(COV28_4, D_220055064_4_4_D_220055064_4_4, "Brand of Fourth COVID-19 Vaccine")
   
   

COV28_5 <- CVD_tib  %>%  filter(vaccinated=="353358909" & (vacc_num>=5))

create_kable_table(COV28_5, D_220055064_5_5_D_220055064_5_5, "Brand of Fifth COVID-19 Vaccine")
   

```