---
title: "Biospecimen Weekly Metrics RMD"
author: "Kelsey Sanchez"
date: "Data Extracted and Report Ran: `r Sys.Date()`"
header-includes:  
    \usepackage[labelformat=empty]{caption}
    \usepackage{placeins}
    \usepackage{booktabs}
    \usepackage{pdflscape}


output:
  pdf_document:
      latex_engine: xelatex
      extra_dependencies: ["float"]
      toc: true
      keep_tex: yes
      fig_width: 7
      fig_height: 5
      fig_caption: true
      df_print: paged 
---
  
  
```{r setup,eval=TRUE,include=FALSE,echo=FALSE, warning=FALSE}

#    latex_engine: xelatex -- this was in the set up previously, but caused issues when running locally so it was removed 

#old.packages()
#update.packages()  


library(bigrquery)
library(data.table) ###to write or read and data management 
library(dplyr) ###data management
# library(boxr) ###read or write data from/to box
library(tidyverse) ###for data management
library(reshape)  ###to work on transition from long to wide or wide to long data
library(listr) ###to work on a list of vector, files or..
library(sqldf) ##sql
library(lubridate) ###date time
library(ggplot2) ###plots
#library(ggpubr) ###for the publications of plots
#library(RColorBrewer) ###visions color http://www.sthda.com/english/wiki/colors-in-r
library(gridExtra)
library(stringr) ###to work on patterns, charaters
#library(plyr)
library(tinytex) #for pdf
#library(rmarkdown) ###for the output tables into other files: pdf, rtf, etc.
library(janitor) #to get the summary sum
library(finalfit) #https://cran.r-project.org/web/packages/finalfit/vignettes/export.html t
library(expss) ###to add labels
library(epiDisplay) ##recommended applied here crosstable, tab1
library(summarytools) ##recommended
library(gmodels) ##recommended
library(magrittr)
library(arsenal)
library(gtsummary)
library(kableExtra)
library(gt)
library(gtsummary)
library(crosstable)
#library(cowplot)
#library(webshot2)
library(glue) 
library(readr)
library(rio)
library(DBI)
#options(knitr.table.format = "latex")
currentDate <- Sys.Date()
currentDate <- as.Date(currentDate)

bq_auth()

### Set Box folders for output CSV files #######################################
use_test_box_folder <- TRUE # Local user sets this (Jake or Kelsey)

# Over-ride if using plumber api on GCP (USER DOESN'T TOUCH THIS!)
# Check if the environment variable exists and is not empty
if (!is.null(Sys.getenv("USE_TEST_BOX_FOLDER")) &&
    Sys.getenv("USE_TEST_BOX_FOLDER") != "") {
  use_test_box_folder <- as.logical(Sys.getenv("USE_TEST_BOX_FOLDER"))
}

if (use_test_box_folder) {
  boxfolder <- 222593912729 # test box folder
} else {
  boxfolder <- 221280601453 # destination of CSV files (not pdf)
}


##### Making sure personal C drives aren't referenced if this code is being used by others


#Change to FALSE if referencing this code
write_to_local_drive = F #F

#local_drive="C:/Users/dowlingk2/Documents/Module-Missingness-and-Metrics/data/"    


### This function below is put before any write.csv functions, and "filename" is updated. It determines wheteher the file will be created locally or not.
#filename=
local_drive= ifelse(write_to_local_drive, "C:/Users/dowlingk2/Documents/Module-Missingness-and-Metrics/data/", "")

```

```{r BQ_DBI, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}

project <- "nih-nci-dceg-connect-prod-6d04"
dataset <- "FlatConnect"


# Establish a connection to BigQuery
con <- dbConnect(
  bigrquery::bigquery(),
  project = project,
  dataset = dataset,
  billing = project  # Use project for billing
)

# Verify the connection by listing available tables
dbListTables(con)

participants <- tbl(con, "participants_JP", page_size = 5000)
biospecimen <- tbl(con, "biospecimen_JP")

```


```{r Overall, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}

#If we need too many variables mutated and selected, I might need to make another massive 'general_merge' like dataframe and can reference this to write it
# general_merge_premutations <- participants %>%
#   filter(d_821247024 == '197316935' & (d_512820379=="486306141" | d_512820379=="854703046" | d_831041022 == '353358909')) %>% #Match Ops report
#      left_join(biospecimen, by = c("Connect_ID", "token", "d_827220437")) %>%
#      mutate(Connect_ID = as.character(Connect_ID), 
#             token = as.character(token), 
#             d_827220437 = as.character(d_827220437))

general_merge_premutations <- participants %>%
     left_join(biospecimen, by = c("Connect_ID", "token", "d_827220437")) %>%
    filter(d_821247024 == '197316935' & (d_512820379=="486306141" | d_512820379=="854703046") & d_831041022 == '104430631') %>% #Match Ops report
     mutate(Connect_ID = as.character(Connect_ID), 
            token = as.character(token), 
            d_827220437 = as.character(d_827220437))


#Mutating as many of the variables in the report ahead of time as possible before collecting the data locally; less memory saved that way
general_merge1 <- general_merge_premutations %>%  
  mutate(
    Recruitment_type = case_when(d_512820379 == '180583933'  ~ "Not active",
                                 d_512820379 == '486306141'  ~ "Active",
                                 d_512820379 == '854703046'  ~ "Passive"),
    Verification_status = case_when(d_821247024 == '875007964'  ~ "Not yet verified",
                                    d_821247024 == '197316935'  ~ "Verified",
                                    d_821247024 == '219863910'  ~ "Cannot be verified",
                                    d_821247024 == '922622075'  ~ "Duplicate",
                                    d_821247024 == '160161595'  ~ "Outreach timed out"),
    Site = case_when(d_827220437 == '472940358'  ~ "Baylor Scott and White",
                     d_827220437 == '531629870'  ~ "HealthPartners",
                     d_827220437 == '548392715'  ~ "Henry Ford Health",
                     d_827220437 == '303349821'  ~ "Marshfield Clinic Health System",
                     d_827220437 == '657167265'  ~ "Sanford Health",
                     d_827220437 == '809703864'  ~ "University of Chicago Medicine",
                     d_827220437 == '125001209'  ~ "Kaiser Permanente Colorado",
                     d_827220437 == '327912200'  ~ "Kaiser Permanente Georgia",
                     d_827220437 == '300267574'  ~ "Kaiser Permanente Hawaii",
                     d_827220437 == '452412599'  ~ "Kaiser Permanente Northwest"),
    Setting = case_when(d_650516960== '534621077'  ~ "Research Collections",
                        d_650516960== '664882224'  ~ "Clinical Collections",
                        d_650516960=="103209024" ~ "Home Collection",
                        TRUE  ~ "No Collections"),
    BiospeCollection = ifelse((d_878865966 == '353358909'| d_167958071 == '353358909' | d_684635302 == '353358909'), 
                              "Any biospecimen Collections","No biospecimen collections"),
    biocol.appoint = case_when(BiospeCollection == "Any biospecimen Collections" & d_410912345== '353358909' ~ "Baseline Collection",
                                    TRUE ~ "No Baseline Collection"),
    BL_blood = case_when(d_878865966 == '353358909'  ~ "Any blood collected",
                                                d_878865966 == '104430631'  ~ "No blood collected"),
    BL_mouthwash = case_when(d_684635302 == '353358909'  ~ "Any mouthwash collected",
                                             d_684635302 == '104430631'  ~ "No mouthwash collected"),
    BL_urine = case_when(d_167958071 == '353358909'  ~ "Any urine collected",
                                         d_167958071 == '104430631'  ~ "No urine collected"),
    Blood_order_placed = case_when(d_173836415_d_266600170_d_530173840 == '104430631'  ~ "No",
                                   d_173836415_d_266600170_d_530173840 == '353358909'  ~ "Yes"),
    Blood_setting = case_when(d_173836415_d_266600170_d_592099155 == '534621077'  ~ "Research",
                              d_173836415_d_266600170_d_592099155 == '664882224'  ~ "Clinical",
                              d_173836415_d_266600170_d_592099155 == '103209024'  ~ "Home"),
    Urine_setting = case_when(d_173836415_d_266600170_d_718172863 == '534621077'  ~ "Research",
                              d_173836415_d_266600170_d_718172863 == '664882224'  ~ "Clinical",
                              d_173836415_d_266600170_d_718172863 == '103209024'  ~ "Home"),
    MW_setting = case_when(d_173836415_d_266600170_d_915179629 == '534621077'  ~ "Research",
                           d_173836415_d_266600170_d_915179629 == '664882224'  ~ "Clinical",
                           d_173836415_d_266600170_d_915179629 == '103209024'  ~ "Home"),
    BUM_completion_status = case_when(d_265193023 == '231311385'  ~ "Submitted",
                                      d_265193023 == '615768760'  ~ "Started",
                                      d_265193023 == '972455046'  ~ "Not Started"),
    BU_completion_status = case_when(d_253883960 == '231311385'  ~ "Submitted",
                                     d_253883960 == '615768760'  ~ "Started",
                                     d_253883960 == '972455046'  ~ "Not Started"),
    Rsc_Site_location = case_when(d_951355211 == '777644826'  ~ "UC-DCAM",
                              d_951355211 == '145191545'  ~ "Ingalls Harvey",
                              d_951355211 == '489380324'  ~ "River East",
                              d_951355211 == '120264574'  ~ "South Loop",
                              d_951355211 == '834825425'  ~ "HP Research Clinic",
                              d_951355211 == '574368418'  ~ "HP Park Nicollet",
                              d_951355211 == '736183094'  ~ "HFH K-13 Research Clinic",
                              d_951355211 == '886364332'  ~ "HFH Cancer Pavilion Research Clinic",
                              d_951355211 == '706927479'  ~ "HFH Livonia Research Clinic",
                              d_951355211 == '322059622'  ~ "HFH Pop-Up",
                              d_951355211 == '692275326'  ~ "Marshfield",
                              d_951355211 == '813701399'  ~ "Weston",
                              d_951355211 == '698283667'  ~ "Lake Hallie",
                              d_951355211 == '691714762'  ~ "Rice Lake",
                              d_951355211 == '487512085'  ~ "Wisconsin Rapids",
                              d_951355211 == '983848564'  ~ "Colby Abbotsford",
                              d_951355211 == '261931804'  ~ "Minocqua",
                              d_951355211 == '665277300'  ~ "Merrill",
                              d_951355211 == '589224449'  ~ "Sioux Falls Imagenetics",
                              d_951355211 == '467088902'  ~ "Fargo South University",
                              d_951355211 == '567969985'  ~ "MF Pop-Up",
                              d_951355211 == '319518299'  ~ "UCM Pop-Up",
                              d_951355211 == '940329442'  ~ "Orland Park",
                              d_951355211 == '723351427'  ~ "BCC- HWC",
                              d_951355211 == '807443231'  ~ "FW All Saints",
                              d_951355211 == '475614532'  ~ "BCC- Plano",
                              d_951355211 == '809370237'  ~ "BCC- Worth St",
                              d_951355211 == '856158129'  ~ "BCC- Irving",
                              d_951355211 == '436956777'  ~ "NTX Biorepository",
                              d_951355211 == '288564244'  ~ "BCC- Fort Worth",
                              is.na(d_951355211) & Site=='University of Chicago Medicine' ~ "Missing UC location",
                              is.na(d_951355211) & Site=='HealthPartners' ~ "Missing HP location",
                              is.na(d_951355211) & Site=='Marshfield Clinic Health System' ~ "Missing MF location",
                              is.na(d_951355211) & Site=='Sanford Health' ~ "Missing SF location",
                              is.na(d_951355211) & Site=='Henry Ford Health' ~ "Missing HFH location",
                              is.na(d_951355211) & Site=='Baylor Scott and White' ~ "Missing BSWH location"),
    Clin_Site_location=case_when(Site=="HealthPartners" & (d_173836415_d_266600170_d_185243482 == '2' | d_173836415_d_266600170_d_452847912 == '2')  ~ "Elk River",
                                 Site=="HealthPartners" & (d_173836415_d_266600170_d_185243482 == '3' | d_173836415_d_266600170_d_452847912 == '3')  ~ "Chanhassen",
                                 d_173836415_d_266600170_d_185243482 == '1050010095' |
                                   d_173836415_d_266600170_d_452847912 == '1050010095'  ~ "Wyandotte",
                                 d_173836415_d_266600170_d_185243482 == '1060010063' |
                                   d_173836415_d_266600170_d_185243482 == '1060170018' |
                                   d_173836415_d_266600170_d_452847912 == '1060010063' |
                                   d_173836415_d_266600170_d_452847912 == '1060170018'  ~ "Macomb",
                                 d_173836415_d_266600170_d_185243482 == '1040010047' |
                                   d_173836415_d_266600170_d_185243482 == '1040010046' |
                                   d_173836415_d_266600170_d_185243482 == '1011220006' |
                                   d_173836415_d_266600170_d_452847912 == '1040010047' |
                                   d_173836415_d_266600170_d_452847912 == '1040010046' |
                                   d_173836415_d_266600170_d_452847912 == '1011220006'  ~ "West Bloomfield",
                                 d_173836415_d_266600170_d_185243482 == '1011410008' |
                                   d_173836415_d_266600170_d_452847912 == '1011410008'  ~ "Royal Oak",
                                 d_173836415_d_266600170_d_185243482 == '1010180040' |
                                   d_173836415_d_266600170_d_452847912 == '1010180040'  ~ "Fairlane (Dearborn)",
                                 d_173836415_d_266600170_d_185243482 == '1010120026' |
                                   d_173836415_d_266600170_d_452847912 == '1010120026'  ~ "Columbus",
                                 d_173836415_d_266600170_d_185243482 == '1011660013 ' |
                                   d_173836415_d_266600170_d_452847912 == '1011660013'  ~ "Plymouth",
                                 d_173836415_d_266600170_d_185243482 == '1010360011' |
                                   d_173836415_d_266600170_d_452847912 == '1010360011'  ~ "Troy",
                                 d_173836415_d_266600170_d_185243482 == '1010350019' | 
                                   d_173836415_d_266600170_d_452847912 == '1010350019' ~ "Taylor",
                                 d_173836415_d_266600170_d_185243482 == '1010240013' |
                                   d_173836415_d_266600170_d_452847912 == '1010240013'  ~ "Livonia",
                                 d_173836415_d_266600170_d_185243482 == '1010320019' |
                                   d_173836415_d_266600170_d_452847912 == '1010320019'  ~ "Sterling Heights",
                                 d_173836415_d_266600170_d_185243482 == '1010010193' |
                                   d_173836415_d_266600170_d_185243482 == '1010010114' |
                                   d_173836415_d_266600170_d_452847912 == '1010010193' |
                                   d_173836415_d_266600170_d_452847912 == '1010010114'  ~ "K1 HFH Main",
                                 d_173836415_d_266600170_d_185243482 == '1010200009' |
                                   d_173836415_d_266600170_d_452847912 == '1010200009'  ~ "Ford Road",
                                 d_173836415_d_266600170_d_185243482 == '1010270015' |
                                   d_173836415_d_266600170_d_452847912 == '1010270015'  ~ "NCO",
                                 d_173836415_d_266600170_d_185243482 == '1050020026' | 
                                   d_173836415_d_266600170_d_452847912 == '1050020026'  ~ "Brownstown",
                                 Site=="Henry Ford Health" & is.na(d_173836415_d_266600170_d_185243482) & is.na(d_173836415_d_266600170_d_452847912)  ~ "Missing Location ID",
                                 Site=="University of Chicago Medicine" & (d_173836415_d_266600170_d_185243482=='1' | d_173836415_d_266600170_d_452847912=='1')  ~ "South Loop",
                                 Site=="University of Chicago Medicine" & (d_173836415_d_266600170_d_185243482=='2' | d_173836415_d_266600170_d_452847912=='2')  ~ "Orland Park",
                                 Site=="University of Chicago Medicine" & (d_173836415_d_266600170_d_185243482=='3' | d_173836415_d_266600170_d_452847912=='3')  ~ "Kenwood",
                                 Site=="University of Chicago Medicine" & (d_173836415_d_266600170_d_185243482=='4' | d_173836415_d_266600170_d_452847912=='4')  ~ "River East",
                                 Site=="University of Chicago Medicine" & (d_173836415_d_266600170_d_185243482=='5' | 
                                                                             d_173836415_d_266600170_d_452847912=='5')  ~ "Dearborn Station"),
    Data_System = case_when((d_173836415_d_266600170_d_534041351=='353358909' & is.na(d_173836415_d_266600170_d_693370086)) |
                              (d_173836415_d_266600170_d_210921343=='353358909' & is.na(d_173836415_d_266600170_d_786930107))~ "Biospecimen Dashboard Only",
                            (is.na(d_173836415_d_266600170_d_534041351) & d_173836415_d_266600170_d_693370086=='353358909') |
                              (is.na(d_173836415_d_266600170_d_210921343) & d_173836415_d_266600170_d_786930107=='353358909')~ "Site Data Only",
                            (d_173836415_d_266600170_d_534041351=='353358909' & d_173836415_d_266600170_d_693370086=='353358909') |
                              (d_173836415_d_266600170_d_210921343=='353358909' & d_173836415_d_266600170_d_786930107=='353358909')  ~ "Site Data & Biospecimen Dashboard"),
    research_sv = case_when(d_265193023 == '231311385'  ~ "Submitted",
                            d_265193023 == '615768760'  ~ "Started",
                            d_265193023 == '972455046'  ~ "Not Started"),
    clinic_sv = case_when(d_253883960 == '231311385'  ~ "Submitted",
                          d_253883960 == '615768760'  ~ "Started",
                          d_253883960 == '972455046'  ~ "Not Started")) %>% 
  select(Recruitment_type, Verification_status, Site, Setting, BiospeCollection, BL_blood, BL_mouthwash, BL_urine, 
         Blood_order_placed, Blood_setting, Urine_setting, MW_setting,  BUM_completion_status, BU_completion_status,
         Rsc_Site_location, Clin_Site_location,  Data_System, research_sv, clinic_sv, #biocol.appoint,
         d_173836415_d_266600170_d_139245758,d_173836415_d_266600170_d_982213346,d_173836415_d_266600170_d_740582332,
         d_173836415_d_266600170_d_541311218, d_173836415_d_266600170_d_224596428, d_410912345, Connect_ID, 
         d_556788178, d_173836415_d_266600170_d_185243482, d_173836415_d_266600170_d_452847912) %>%  
  as_tibble()

 








#Dataframe above was too big, had to break it into mutliple, smaller chunks
##Data on all 16 tube types: id, deviaion, and collection
general_merge2 <- general_merge_premutations %>% 
  filter(d_821247024 == '197316935') %>% 
  select(d_143615646_d_678857215, d_223999569_d_678857215, d_232343615_d_678857215, d_299553921_d_678857215, 
         d_376960806_d_678857215, d_454453939_d_678857215, d_505347689_d_678857215, d_589588440_d_678857215, d_652357376_d_678857215, 
         d_677469051_d_678857215, d_683613884_d_678857215, d_703954371_d_678857215, d_787237543_d_678857215, d_838567176_d_678857215, 
         d_958646668_d_678857215, d_973670172_d_678857215, d_143615646_d_593843561, d_223999569_d_593843561, d_232343615_d_593843561, 
         d_299553921_d_593843561, d_376960806_d_593843561, d_454453939_d_593843561, d_505347689_d_593843561, d_589588440_d_593843561, 
         d_652357376_d_593843561, d_677469051_d_593843561, d_683613884_d_593843561, d_703954371_d_593843561, d_787237543_d_593843561, 
         d_838567176_d_593843561, d_958646668_d_593843561, d_973670172_d_593843561) %>% 
  as_tibble()



general_merge3 <- general_merge_premutations %>% 
  filter(d_821247024 == '197316935') %>% 
  select(d_143615646_d_762124027, d_223999569_d_762124027, 
         d_232343615_d_762124027, d_299553921_d_762124027, d_376960806_d_762124027, d_454453939_d_762124027, d_505347689_d_762124027, 
         d_589588440_d_762124027, d_652357376_d_762124027, d_677469051_d_762124027, d_683613884_d_762124027, d_703954371_d_762124027, 
         d_787237543_d_762124027, d_838567176_d_762124027, d_958646668_d_762124027, d_973670172_d_762124027, d_820476880) %>% 
  as_tibble()


general_merge4 <- general_merge_premutations %>% 
  filter(d_821247024 == '197316935') %>% 
  select(d_143615646_d_825582494, d_223999569_d_825582494, d_232343615_d_825582494, d_299553921_d_825582494, 
         d_376960806_d_825582494, d_454453939_d_825582494, d_505347689_d_825582494, d_589588440_d_825582494, 
         d_652357376_d_825582494, d_677469051_d_825582494, d_683613884_d_825582494, d_703954371_d_825582494, 
         d_787237543_d_825582494, d_838567176_d_825582494, d_958646668_d_825582494, d_973670172_d_825582494,
         d_222161762, d_331584571_d_266600170_d_840048338, d_764863765, d_534669573) %>% 
  as_tibble()


general_merge_all <- cbind(general_merge1, general_merge2, general_merge3, general_merge4)



### First date of a verified participant. This will be used to set week time frames for counts. Each week must start on Monday and end with the following Sunday to be consistent with all reports
veristart.date = as.Date("2021-07-27")

```


```{r Removing_Duplicates, include=FALSE}

# Ops no longer wants duplicate collections in this report
## REMOVING DUPLICATES: Method- take the first collection and drop the second collection
##### NOTE: Home MW collections are separate collections BUT they are not finalized, so they will not be removed from the dataframe


# Step 1: Find the duplicate rows
## 295- one person has three rows; 147 individuals
actual_dups <- general_merge_all %>%
  filter(!is.na(d_556788178)) %>%
  group_by(Connect_ID) %>%
  filter(n() > 1)

# Step2: Of the duplicate rows, keep the one with the first collection time stamp
#Keeping 147- each person keeps their lower collection time
rows_to_keep <- actual_dups %>%
  group_by(Connect_ID) %>%
  filter(d_556788178 == min(d_556788178, na.rm = TRUE)) %>%
  ungroup()


# Take all duplicate rows out of the original dataframe
#Take the 295 from the original 52650 rows, totaling ==52,355
non_duplicate_rows <- general_merge_all %>%
    anti_join(actual_dups, by = c("Connect_ID", "d_556788178"))  # Ensure all columns are included

# Combine new overall dataframe with those duplicate rows we filtered with the earlier timstamp
#52,355+147=52502
no_dups <- bind_rows(rows_to_keep, non_duplicate_rows)


```

```{r Duplicates, include=FALSE}

# ## All the duplicate rows- this is pulled from the Biospecimen QC code
# dup <- "WITH T AS (
#   SELECT Connect_ID 
#   FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.biospecimen_JP`
#   WHERE d_820476880 LIKE 'CXA%' 
#   AND d_820476880 NOT LIKE 'CHA%'
#   GROUP BY Connect_ID
#   HAVING COUNT(Connect_ID) > 1
# ) 
# SELECT Connect_ID 
# FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.biospecimen_JP`
# WHERE Connect_ID IN (SELECT Connect_ID FROM T) and d_820476880 NOT LIKE 'CHA%'"
# 
# dup_table <- bq_project_query(project, dup)
# dup_data <- bq_table_download(dup_table, bigint = "integer64", n_max = Inf, page_size = 1000)
# 
# 
# #All duplicate rows- 374
# dim(dup_data)
# 
# #For each participant with a duplicate row(s), select the row with the earlier collection
# rows_to_keep <- general_merge_all %>%
#   filter(Connect_ID %in% dup_data$Connect_ID) %>% 
#   group_by(Connect_ID) %>%
#   filter(d_556788178 == min(d_556788178, na.rm = TRUE)) %>%
#   ungroup()
# 
# #Remove all the duplicate rows from the dataframe
# non_duplicate_rows <- general_merge_all %>%
#     anti_join(actual_dups, by = c("Connect_ID", "d_556788178"))
# 
# #Add back that one row we kept for each duplicate participant collection
# no_dups <- bind_rows(rows_to_keep, non_duplicate_rows)

```


```{r Functions, include=FALSE}


pct_tb <- function(x,y){
  table1 <- CrossTable(x,y, prop.t=FALSE, prop.r=FALSE, prop.c=TRUE,chisq=FALSE)
  pct <- as.data.frame(cbind(table1$prop.row,table1$t))
  if(ncol(pct)==2){
    total <- as.numeric(sum(pct[,2]))
    pct[nrow(pct)+1,c(1:2)] <- c(1,total)
    rownames(pct)[nrow(pct)] <- "Total"
    colnames(pct)[1] <- paste0("pct_",colnames(pct)[1])
    colnames(pct)[2] <- paste0("n_",colnames(pct)[2])
    
  }
  else  if(ncol(pct)>2 ){
    total <- as.numeric(sum(pct[,3] + pct[,4]))
    pct[nrow(pct)+1,c(1:4)] <- c(sum(pct[,3])/total,sum(pct[,4])/total,sum(pct[,3]),sum(pct[,4]))
    rownames(pct)[nrow(pct)] <- "Total"
    colnames(pct)[c(1:2)] <- paste0("pct_",colnames(pct[c(1:2)]))
    colnames(pct)[c(3:4)] <- paste0("n_",colnames(pct)[c(3:4)])
    
    pct[,5] <- paste0(format(pct[,3],big.mark=","), " (",round(100*pct[,1],1), " %)")
    pct[,6] <- paste0(format(pct[,4],big.mark=","), " (",round(100*pct[,2],1), " %)") 
    colnames(pct)[5] <- paste0("n_",colnames(pct)[1])
    colnames(pct)[6] <- paste0("n_",colnames(pct)[2])
  }
  return(pct)
}




n_pct_table <- function(x,y){
  #x<-clinicnotes.notcol$Site
  #y<-clinicnotes.notcol$notcol.notes
  ctable<- CrossTable(x,y)
  count <- as.data.frame.matrix(ctable$t)
  perc <- as.data.frame.matrix(ctable$prop.col)
  n<- as.numeric(length(levels(x)))
  m <- as.numeric(length(levels(y)))
  tb_combo <- array(pct_n(ctable$t,ctable$prop.col),dim=c(n,m)) 
  tb_combo <- as.data.frame(tb_combo)
  colnames(tb_combo) <- colnames(count)
  
  total <- sum(count)
  count$Total <- apply(count,1,sum)
  tb_combo$Total <- paste0(count$Total, "( ", round(100*(count$Total)/total,1), " %)")
  
  tb_combo$Site <- rownames(count)
  tb_combo[(n+1),c(1:(m+1))] <- as.character(apply(count,2,sum))
  tb_combo$Site[is.na(tb_combo$Site)] <- replace_na("Total")  
  return(tb_combo)
}



pct_n <- function(x,y){ paste0(x,"( ", round(100*y,2), " %)")}


# tbl_cross() tables are repeated throughout the code. The variables for row and column must be put in quotes when calling the function
create_tbl_cross <- function(data, row_var, colm_var, row_or_col_pct, row_name, column_name){
cross__table <- data %>%  
  tbl_cross(
    row = !!sym(row_var),
    col = !!sym(colm_var),
    digits=c(0,1),
    percent = row_or_col_pct,
    label=list(!!sym(row_var) ~ row_name,
               !!sym(colm_var) ~ column_name),
    missing="ifany",
    margin_text="Total") 

#Ops doesn't like the grouped by variables on a different line the column labels
cross_table_df <- as.data.frame(cross__table)[-1, ]
  
}



# Converting the finalized collection time to the previous Monday. All graphs are looking at the collection week counts as Monday-Sunday


adjust_to_monday <- function(dt) {
  if (is.na(dt)) {
    return(NA)  
  }
  
  # Get the day of the week (1 = Sunday, 2 = Monday, ..., 7 = Saturday)
  dow <- wday(dt)
  
  # If the day is not Monday (2), subtract the number of days to the previous Monday
  if (dow != 2) {
    dt <- dt - days((dow - 2) %% 7)
  }
  return(dt)
}

# Ensure d_556788178 is in Date format
no_dups$d_556788178 <- as.Date(no_dups$d_556788178)

no_dups$Monday_collections <- sapply(no_dups$d_556788178, adjust_to_monday)

# Convert to Date to ensure proper format
no_dups$Monday_collections <- as.Date(no_dups$Monday_collections)








## Not a function, but a shortcut for repeating code in plots

figure_themes <-  theme(panel.background = element_blank(),
        axis.line = element_line(size=0.2),
        axis.text.x=element_text(angle=60, hjust=1), axis.title.x = element_text( size = 14, face = "bold") ,
        axis.title.y = element_text(size = 14, face = "bold",color="black"),
        plot.title = element_text(hjust = 0.5,size = 12, face = "bold")) + 
  theme(plot.caption = element_text(hjust=0))


```




```{r Table1.1, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}

## This is the ONLY table that looks by participant count. The rest look at collection counts, and many participants have multiple collections ("duplicate collections")


bio.appoint <- no_dups %>% arrange(Connect_ID, d_410912345, Rsc_Site_location) %>%
  group_by(Connect_ID) %>%
  summarise(
    d_410912345 = mean(d_410912345, na.rm = TRUE), #to remove the multiple collections by Connect_ID
    Rsc_Site_location = first(Rsc_Site_location)
  ) 
 
biocol.tb <- base::merge(no_dups, bio.appoint,by.x=c("Connect_ID", "d_410912345"),by.y=c("Connect_ID", "d_410912345"),all.x=TRUE )
 
table1 <- biocol.tb %>% 
  group_by(Connect_ID) %>% 
  mutate(biocol.appoint = case_when(BiospeCollection == "Any biospecimen Collections" & d_410912345== 353358909 ~ "Baseline Collection",
                                    TRUE ~ "No Baseline Collection")) 

table1.1 <- create_tbl_cross(table1, "Site", "biocol.appoint", "row", "Site", " ")

biospe.t1 <- knitr::kable(table1.1,
                          col.names=c("Site", "Baseline Collection","No Baseline Collection", "Total Verified Participants"),
                          caption='Table 1.1: Baseline Biospecimen Collection Status Among Verified Participants',
                          row.names=FALSE,align=c("l","c","c","c"), booktabs = TRUE) %>%
  add_indent(seq(1, 10)) %>%
  kable_styling(latex_options = "scale_down") 

table_1.1 <- no_dups %>% 
  mutate(biocol.appoint = case_when(BiospeCollection == "Any biospecimen Collections" & d_410912345== 353358909 ~ "Baseline Collection",
                                    TRUE ~ "No Baseline Collection")) %>%
  group_by(Site, biocol.appoint) %>%  tally()


```


```{r Table1.2, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}




table_1.2 <- no_dups %>% filter(Setting=="Research Collections") %>%
  filter(BiospeCollection == "Any biospecimen Collections" & d_410912345== '353358909') %>%
  group_by(Rsc_Site_location) %>%  tally() %>%
  mutate(Site_Group = case_when(
    Rsc_Site_location %in% c("UC-DCAM", "Ingalls Harvey", "River East", "South Loop", "UCM Pop-Up", "Orland Park", "Missing UC location") ~ "University of Chicago Medicine",
    Rsc_Site_location %in% c("HP Research Clinic",  "HP Park Nicollet", "Missing HP location") ~ "HealthPartners",
    Rsc_Site_location %in% c("Lake Hallie", "Marshfield", "MF Pop-Up", "Minocqua", "Weston", "Wisconsin Rapids", "Rice Lake", "Colby Abbotsford", "Merrill") ~ "Marshfield Clinic Health System",
    Rsc_Site_location %in% c("Sioux Falls Imagenetics", "Fargo South University", "Missing SF location") ~ "Sanford Health",
    Rsc_Site_location %in% c("HFH K-13 Research Clinic", "HFH Livonia Research Clinic", "HFH Cancer Pavilion Research Clinic", "HFH Pop-Up", "Missing HFH location") ~ "Henry Ford Health",
    Rsc_Site_location %in% c("BCC- HWC","FW All Saints","BCC- Plano","BCC- Worth St","BCC- Irving","NTX Biorepository","BCC- Fort Worth", "Missing BSWH location") ~ "Baylor Scott and White",
    TRUE ~ "Other"
  ))


#Get total overall collections
total_collections <- table_1.2 %>%
  group_by(Site_Group) %>%
  summarize(Total_Collections = sum(`n`, na.rm = TRUE))

#Get collection by Site
table_1.2 <- table_1.2 %>%
  left_join(total_collections, by = "Site_Group")


table_1.2 <- table_1.2 %>%
  mutate(Percentage = round((`n` / Total_Collections * 100), digits=1))

#Create total row
total_rows <- table_1.2 %>%
  group_by(Site_Group) %>%
  summarize(`Rsc_Site_location` = "Total",
            `n` = sum(`n`),
            Percentage = 100) %>%
  ungroup()

table_1.2 <- bind_rows(table_1.2, total_rows)

#Need an N% column, not individual N and %
table_1.2$`Total Research Collections` <- paste0(table_1.2$`n`, " (", table_1.2$Percentage,"%)")


#Group location by site, and indent the location names
table_1.2 <- table_1.2 %>%
  mutate(`Collection Location` = paste0("\u00A0\u00A0\u00A0",`Rsc_Site_location`)) %>%  
  select(-c(`n`, `Total_Collections`, 'Percentage', 'Rsc_Site_location'))


table_1.2_gt <- table_1.2[, c(1,3,2)] %>%

  gt::gt(groupname_col = "Site_Group")





table_1.2_gt <- table_1.2_gt %>%  summary_rows(
  groups = TRUE,
  columns = vars("Total Research Collections"),
  fns = (Sum = ~sum(.)),
) %>% tab_header("Table 1.2: Baseline Research Biospecimen Collections by Collection Location")
  

```



```{r Table1.3, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}


table_1.3 <- no_dups %>% filter(Setting=="Clinical Collections") %>%
  filter(BiospeCollection == "Any biospecimen Collections" & d_410912345== '353358909') %>%
  group_by(Clin_Site_location) %>%  tally() %>%
  mutate(Site_Group = case_when(
    `Clin_Site_location` %in% c("Macomb", "West Bloomfield", "Wyandotte","Fairlane (Dearborn)", "Plymouth", "Royal Oak", "Troy", "K1 HFH Main","Sterling Heights","Columbus", 
                                 "Livonia","Taylor", "Ford Road", "NCO","Brownstown", "Missing Location ID") ~ "Henry Ford Health", 
    `Clin_Site_location` %in% c("Elk River", "Chanhassen") ~ "HealthPartners", #"NSC", 
    `Clin_Site_location` %in% c("South Loop","Orland Park","Kenwood","River East","Dearborn Station") ~ "University of Chicago Medicine",
    TRUE ~ "Other"
  ))


#Get total overall collections
total_collections <- table_1.3 %>%
  group_by(Site_Group) %>%
  summarize(Total_Collections = sum(`n`, na.rm = TRUE))

#Get collection by Site
table_1.3 <- table_1.3 %>%
  left_join(total_collections, by = "Site_Group")


table_1.3 <- table_1.3 %>%
  mutate(Percentage = round((`n` / Total_Collections * 100), digits=1))

#Create total row
total_rows <- table_1.3 %>%
  group_by(Site_Group) %>%
  summarize(`Clin_Site_location` = "Total",
            `n` = sum(`n`),
            Percentage = 100) %>%
  ungroup()

table_1.3 <- bind_rows(table_1.3, total_rows)

#Need an N% column, not individual N and %
table_1.3$`Total Research Collections` <- paste0(table_1.3$`n`, " (", table_1.3$Percentage,"%)")


#Group location by site, and indent the location names
table_1.3 <- table_1.3 %>%
  mutate(`Collection Location` = paste0("\u00A0\u00A0\u00A0",`Clin_Site_location`)) %>%  
  select(-c(`n`, `Total_Collections`, 'Percentage', 'Clin_Site_location'))


table_1.3_gt <- table_1.3[, c(1,3,2)] %>%

  gt::gt(groupname_col = "Site_Group")





table_1.3_gt <- table_1.3_gt %>%  summary_rows(
  groups = TRUE,
  columns = vars("Total Research Collections"),
  fns = (Sum = ~sum(.)),
) %>% tab_header("Table 1.3: Baseline Clinical Biospecimen Collections by Clinic Location")
  

```




```{r Sanford_Table_1.4, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}

table1_4_locations <- no_dups %>% filter(Setting=="Clinical Collections") %>%
  filter(BiospeCollection == "Any biospecimen Collections" & d_410912345== '353358909' & Site=="Sanford Health")

footnote_count <- nrow(table1_4_locations)

add_Site_location <- function(table1_4_locations, csv_file_path) {
  site_data <- read_csv(csv_file_path)
  
  if (!("ID" %in% colnames(site_data)) | !("Site_location" %in% colnames(site_data))) {
    stop("The CSV file must contain 'ID' and 'Site_location' columns.")
  }
  
  case_when_string <- ""
  
  for (i in 1:nrow(site_data)) {
    id <- site_data[i, "ID"]
    location <- site_data[i, "Site_location"]
    
    case_when_string <- paste0(
      case_when_string,
      "d_173836415_d_266600170_d_185243482 == ", id, " | d_173836415_d_266600170_d_452847912 == ", id, " ~ '", location, "',\n"
    )
  }
  
  case_when_string <- substr(case_when_string, 1, nchar(case_when_string) - 2)
  
  case_when_statement <- paste0("case_when(\n", case_when_string, "\n)")
  
  table1_4_locations <- table1_4_locations %>%
    mutate(Site_location = eval(parse(text = case_when_statement)))
  
  return(table1_4_locations)
}


table1_4_locations <- add_Site_location(table1_4_locations, "Sanford_Clincal_Locations.csv")
table1_4_locations <- table1_4_locations %>% filter(!is.na(Site_location))


table1_4_locations_all <- table1_4_locations 

table1_4_locations_7days <- table1_4_locations %>% filter(d_556788178 >= currentDate - 7)
table1_4_locations_30days <- table1_4_locations %>% filter(d_556788178 >= currentDate - 30)


count_all <- table1_4_locations_all %>%
  count(Site_location) %>%
  mutate(Count_Total = n) %>%
  select(-n)

total_all <- sum(count_all$Count_Total)
count_all <- count_all %>%
  mutate(Percent_Total = paste0(round((Count_Total / total_all) * 100, 1), "%"))


count_7days <- table1_4_locations_7days %>%
  count(Site_location) %>%
  mutate(Count_7days = n) %>%
  select(-n)

total_7days <- sum(count_7days$Count_7days)
count_7days <- count_7days %>%
  mutate(Percent_7days = paste0(round((Count_7days / total_7days) * 100, 1), "%"))


count_30days <- table1_4_locations_30days %>%
  count(Site_location) %>%
  mutate(Count_30days = n) %>%
  select(-n)

total_30days <- sum(count_30days$Count_30days)
count_30days <- count_30days %>%
  mutate(Percent_30days = paste0(round((Count_30days / total_30days) * 100, 1), "%"))


final_col_num_1.5 <- full_join(count_all, count_7days, by = "Site_location") %>% full_join(count_30days, by = "Site_location") %>%
  replace_na(list(Count_Total = 0, Percent_Total = "0%", Count_7days = 0, Percent_7days = "0%", Count_30days = 0, Percent_30days = "0%"))


total_row <- data.frame(
  Site_location = "Total",
  Count_Total = total_all,
  Percent_Total = "100%",
  Count_7days = total_7days,
  Percent_7days = "100%",
  Count_30days = total_30days,
  Percent_30days = "100%"
)

final_col_num_1.5 <- bind_rows(final_col_num_1.5, total_row)


final_col_num_1.5$C7 <- paste0(final_col_num_1.5$Count_7days, " (", final_col_num_1.5$Percent_7days, ")")
final_col_num_1.5$C30 <- paste0(final_col_num_1.5$Count_30days, " (", final_col_num_1.5$Percent_30days, ")")


SF_clin_count <- final_col_num_1.5[, c(1,8,9)]

```



```{r Table1.5, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}


finalized <- no_dups %>% filter(d_410912345== 353358909) 
table1.5 <- create_tbl_cross(finalized, 'Site', "BL_blood", "row", 'Site', " ")

biospe.bld <- knitr::kable(table1.5, #removing the award line over the columns
                           col.names=c("Site", "Any Blood Collected","No Blood Collected", "Total Collections"),
                           caption='Table 1.5: Baseline Blood Collection Status Among Biospecimen Collections',
                           row.names=FALSE,align=c("l","c","c","c"), 
                           booktabs = TRUE)  %>% add_indent(seq(1,  10)) %>%  
  kable_styling(latex_options = "HOLD_position")   



```


```{r Coll_Sett_AllSites, eval=TRUE,echo=FALSE,warning=FALSE,include=FALSE,results='hold'}

## the counts aren't quite right, for example there's counts of clinical mw which isn't possible
# coll_set_spec <- no_dups %>% 
#   mutate(
#     blood_specs = ifelse(BL_blood == "Any blood collected", 1, 0),
#     urine_specs = ifelse(BL_urine == "Any urine collected", 1, 0),
#     mouthwash_specs = ifelse(BL_mouthwash == "Any mouthwash collected", 1, 0)
#   ) %>%
#   group_by(Setting) %>%
#   summarise(
#     Blood = sum(blood_specs, na.rm = TRUE),
#     Urine = sum(urine_specs, na.rm = TRUE),
#     Mouthwash = sum(mouthwash_specs, na.rm = TRUE)
#   )


 

## Issue: for whatever reason some people have a null BL_BioSpm_BloodSetting_v1r0/Urine/MW value, so the extra '| d_650516960==' is added
#but 650516960 won't apply correctly to mouthwash all the time
coll_set_spec <- no_dups %>% 
  mutate(
    Blood_Clinical = ifelse(BL_blood == "Any blood collected" & (Blood_setting=="Clinical" | Setting=="Clinical Collections"), 1, 0),
    Blood_Research = ifelse(BL_blood == "Any blood collected" & (Blood_setting=="Research" | Setting=="Research Collections"), 1, 0),
    Blood_Home = ifelse(BL_blood == "Any blood collected" & (Blood_setting=="Home"| Setting=="Home Collection"), 1, 0),
    Urine_Clinical = ifelse(BL_urine == "Any urine collected" & (Urine_setting=="Clinical" | Setting=="Clinical Collections"), 1, 0),
    Urine_Research = ifelse(BL_urine == "Any urine collected" & (Urine_setting=="Research" | Setting=="Research Collections"), 1, 0),
    Urine_Home = ifelse(BL_urine == "Any urine collected" & (Urine_setting=="Home"| Setting=="Home Collection"), 1, 0),
    Mouthwash_Clinical = ifelse(BL_mouthwash == "Any mouthwash collected" & MW_setting=="Clinical", 1, 0),
    Mouthwash_Research = ifelse(BL_mouthwash == "Any mouthwash collected" & MW_setting=="Research", 1, 0),
    Mouthwash_Home = ifelse(BL_mouthwash == "Any mouthwash collected" & MW_setting=="Home", 1, 0)
  )


long_format <- coll_set_spec %>%
  select(starts_with("Blood"), starts_with("Urine"), starts_with("Mouthwash")) %>% 
  mutate(across(everything(), as.numeric)) %>% 
  pivot_longer(
    cols = everything(),
    names_to = c("Specimen_Type", "Location"),
    names_sep = "_",
    values_to = "Count"
  )


long_format <- long_format %>% filter(Count == 1)


cross_tab <- long_format %>%
  group_by(Location, Specimen_Type) %>%
  summarise(Count = n()) %>%
  pivot_wider(names_from = Specimen_Type, values_from = Count, values_fill = list(Count = 0))


total_row <- data.frame(
  Location = "Total",
  Blood = sum(cross_tab$Blood),
  Urine = sum(cross_tab$Urine),
  Mouthwash = sum(cross_tab$Mouthwash)
)

allsites_crosstab <- bind_rows(cross_tab, total_row)



# Perentages
allsites_crosstab <- allsites_crosstab %>%
  mutate(across(starts_with("Blood"), ~ paste0(.x, " (", round(.x / allsites_crosstab$Blood[4], digits = 3) * 100, "%)")),
         across(starts_with("Urine"), ~ paste0(.x, " (", round(.x / allsites_crosstab$Urine[4], digits = 3) * 100, "%)")),
         across(starts_with("Mouthwash"), ~ paste0(.x, " (", round(.x / allsites_crosstab$Mouthwash[4], digits = 3) * 100, "%)")))

# Format the total row separately
#allsites_crosstab[nrow(allsites_crosstab), -1] <- lapply(allsites_crosstab[nrow(allsites_crosstab), -1], function(x) paste0(x)) #, " (100%)"
allsites_crosstab[nrow(allsites_crosstab), 2:4] <- lapply(allsites_crosstab[nrow(allsites_crosstab), 2:4], function(x) gsub("\\(100%\\).*", "(100%)", x))


tab5=knitr::kable(allsites_crosstab, 
                  col.names=c("Collection Setting","Any Blood Collected", "Urine Collected", "Mouthwash Collected"), 
                  caption='Table 1.6: Baseline Collection Setting Among Biospecimen Collections by Specimen Type', 
                  row.names=FALSE, align=c("l","c","c","c"), format.args = list(big.mark = ","), booktabs = TRUE)   
add_footnote(tab5, "Note: Blood and urine specimens are not collected in the Home setting, and mouthwash specimens are not collected in the Clinical setting.", 
             notation = "none")


```


```{r Coll_Sett_Hyrbids, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}

##need to check this. Wasn't merged correctly in the merge conlflict on Github
table2_hybrid <- no_dups %>%  filter(Site=="Henry Ford Health" | Site=="HealthPartners" | Site=="Sanford Health" | Site=="University of Chicago Medicine")

sites <- unique(table2_hybrid$Site)
site_results <- list()

for (site in sites) {
  site_data <- filter(table2_hybrid, Site == site)
  
  coll_set_spec <- site_data  %>%
    mutate(
    Blood_Clinical = ifelse(BL_blood == "Any blood collected" & (Blood_setting=="Clinical" | Setting=="Clinical Collections"), 1, 0),
    Blood_Research = ifelse(BL_blood == "Any blood collected" & (Blood_setting=="Research" | Setting=="Research Collections"), 1, 0),
    Blood_Home = ifelse(BL_blood == "Any blood collected" & (Blood_setting=="Home"| Setting=="Home Collection"), 1, 0),
    Urine_Clinical = ifelse(BL_urine == "Any urine collected" & (Urine_setting=="Clinical" | Setting=="Clinical Collections"), 1, 0),
    Urine_Research = ifelse(BL_urine == "Any urine collected" & (Urine_setting=="Research" | Setting=="Research Collections"), 1, 0),
    Urine_Home = ifelse(BL_urine == "Any urine collected" & (Urine_setting=="Home"| Setting=="Home Collection"), 1, 0),
    Mouthwash_Clinical = ifelse(BL_mouthwash == "Any mouthwash collected" & MW_setting=="Clinical", 1, 0),
    Mouthwash_Research = ifelse(BL_mouthwash == "Any mouthwash collected" & MW_setting=="Research", 1, 0),
    Mouthwash_Home = ifelse(BL_mouthwash == "Any mouthwash collected" & MW_setting=="Home", 1, 0)
    )
  
  
  long_format <- coll_set_spec %>%
  select(starts_with("Blood"), starts_with("Urine"), starts_with("Mouthwash")) %>% 
  mutate(across(everything(), as.numeric)) %>% 
  pivot_longer(
    cols = everything(),
    names_to = c("Specimen_Type", "Location"),
    names_sep = "_",
    values_to = "Count"
  )


long_format <- long_format %>% filter(Count == 1)


  # derived_cols <- coll_set_spec %>%
  #   select(starts_with("Blood"), starts_with("Urine"), starts_with("Mouthwash"))
  # 
  # long_format <- derived_cols %>%
  #   pivot_longer(
  #     cols = everything(),
  #     names_to = c("Specimen_Type", "Location"),
  #     names_sep = "_",
  #     values_to = "Count"
  #   ) %>%
  #   filter(Count == 1)
  
  cross_tab_HYB <- long_format %>%
    group_by(Location, Specimen_Type) %>%
    summarise(Count = n(), .groups = 'drop') %>%  # <--- Added .groups = 'drop'
    pivot_wider(
      names_from = Specimen_Type,
      values_from = Count,
      values_fill = list(Count = 0)
    )
  
  # Add Home back with zero counts if it doesn't exist
  if (!"Home" %in% cross_tab_HYB$Location) {
    # <--- Added this block
    cross_tab_HYB <- cross_tab_HYB %>%
      add_row(
        Location = "Home",
        Blood = 0,
        Urine = 0,
        Mouthwash = 0
      )  
  }
  
  total_row <- data.frame(
    Location = "Total",
    Blood = sum(cross_tab_HYB$Blood),
    Urine = sum(cross_tab_HYB$Urine),
    Mouthwash = sum(cross_tab_HYB$Mouthwash)
  )
  
  hybrid_crosstab <- bind_rows(cross_tab_HYB, total_row)
  
  # Perentages
  hybrid_crosstab <- hybrid_crosstab %>%
    mutate(across(starts_with("Blood"), ~ paste0(.x, " (", round(.x / hybrid_crosstab$Blood[4], digits = 3) * 100, "%)")),
           across(starts_with("Urine"), ~ paste0(.x, " (", round(.x / hybrid_crosstab$Urine[4], digits = 3) * 100, "%)")),
           across(starts_with("Mouthwash"), ~ paste0(.x, " (", round(.x / hybrid_crosstab$Mouthwash[4], digits = 3) * 100, "%)")))
  
  # Format the total row separately
  #hybrid_crosstab[nrow(hybrid_crosstab), -1] <- lapply(hybrid_crosstab[nrow(hybrid_crosstab), -1], function(x) paste0(x)) #, " (100%)"
  hybrid_crosstab[nrow(hybrid_crosstab), 2:4] <- lapply(hybrid_crosstab[nrow(hybrid_crosstab), 2:4], function(x) gsub("\\(100%\\).*", "(100%)", x))
  
  
  # Store the result for the current site
  site_results[[site]] <- hybrid_crosstab
}


tab5_1=knitr::kable(site_results["Henry Ford Health"], 
                    col.names=c("Collection Setting","Any Blood Collected", "Urine Collected", "Mouthwash Collected"), 
                    caption='Table 1.7: Baseline Collection Setting Among Biospecimen Collections by Specimen Type, Henry Ford Health', 
                    row.names=FALSE, align=c("l","c","c","c"), format.args = list(big.mark = ","), booktabs = TRUE)   
add_footnote(tab5_1, "Note: Blood and urine specimens are not collected in the Home setting, and mouthwash specimens are not collected in the Clinical setting.", 
             notation = "none")


tab5_2=knitr::kable(site_results["HealthPartners"], 
                    col.names=c("Collection Setting","Any Blood Collected", "Urine Collected", "Mouthwash Collected"), 
                    caption='Table 1.8: Baseline Collection Setting Among Biospecimen Collections by Specimen Type, HealthPartners', 
                    row.names=FALSE, align=c("l","c","c","c"), format.args = list(big.mark = ","), booktabs = TRUE)   
add_footnote(tab5_2, "Note: Blood and urine specimens are not collected in the Home setting, and mouthwash specimens are not collected in the Clinical setting.", 
             notation = "none")


tab5_3=knitr::kable(site_results["Sanford Health"], 
                    col.names=c("Collection Setting","Any Blood Collected", "Urine Collected", "Mouthwash Collected"), 
                    caption='Table 1.9: Baseline Collection Setting Among Biospecimen Collections by Specimen Type, Sanford Health', 
                    row.names=FALSE, align=c("l","c","c","c"), format.args = list(big.mark = ","), booktabs = TRUE)
add_footnote(tab5_3, "Note: Blood and urine specimens are not collected in the Home setting, and mouthwash specimens are not collected in the Clinical setting.", 
             notation = "none")


tab5_4=knitr::kable(site_results["University of Chicago Medicine"], 
                    col.names=c("Collection Setting","Any Blood Collected", "Urine Collected", "Mouthwash Collected"), 
                    caption='Table 1.10: Baseline Collection Setting Among Biospecimen Collections by Specimen Type, University of Chicago Medicine', 
                    row.names=FALSE, align=c("l","c","c","c"), format.args = list(big.mark = ","), booktabs = TRUE)
add_footnote(tab5_4, "Note: Blood and urine specimens are not collected in the Home setting, and mouthwash specimens are not collected in the Clinical setting.", 
             notation = "none")


```


```{r Data_Sytems, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}


data_systems_table <- no_dups %>%  filter(!is.na(Data_System))

table1.11_blood <- create_tbl_cross(data_systems_table, "Data_System", "BL_blood", "column", "Data System", " ")
table1.11_urine <- create_tbl_cross(data_systems_table, "Data_System", "BL_urine", "column", "Data System", " ")



table1.11 <- cbind(table1.11_blood[, c(1,2)], table1.11_urine[, c(1,2)])

#repeated columns removed, and 'unknown' row removed
table1.11 <- table1.11[, c(1,2,4)]


systems = knitr::kable(table1.11, 
                       col.names = c("Data System", "Blood Collected", "Urine Collected"),
                           caption='Table 1.11: Baseline- Data System Status Among Clinical Biospecimen Collections by Specimen Type', 
                           row.names=FALSE,align=c("l","c","c"), booktabs = TRUE) %>%  kable_styling(latex_options = "HOLD_position") 
add_footnote(systems, "Note: Site data may be available up to 48 hours later than Biospecimen Dashboard data. 'Site Data Only' is assumed to be '0 (0%)' when not listed.", 
             notation = "none")

```





```{r Collections by Site and Setting, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}
rsch_coll <- no_dups %>%  filter(Setting=="Research Collections") %>% 
  mutate('Specimens Collected'= case_when((BL_blood=="Any blood collected" & BL_urine=="Any urine collected" & BL_mouthwash=="Any mouthwash collected") ~ 'Blood, Urine, Mouthwash (All)',
                                          (BL_blood=="Any blood collected" & BL_urine=="Any urine collected" & BL_mouthwash!="Any mouthwash collected") ~ 'Blood & Urine Only',
                                          (BL_blood=="Any blood collected" & BL_urine!="Any urine collected" & BL_mouthwash=="Any mouthwash collected") ~ 'Blood & Mouthwash Only',
                                          (BL_blood!="Any blood collected" & BL_urine=="Any urine collected" & BL_mouthwash=="Any mouthwash collected") ~ 'Urine & Mouthwash Only',
                                          (BL_blood=="Any blood collected" & BL_urine!="Any urine collected" & BL_mouthwash!="Any mouthwash collected") ~ 'Blood Only',
                                          (BL_blood!="Any blood collected" & BL_urine=="Any urine collected" & BL_mouthwash!="Any mouthwash collected") ~ 'Urine Only',
                                          (BL_blood!="Any blood collected" & BL_urine!="Any urine collected" & BL_mouthwash=="Any mouthwash collected") ~ 'Mouthwash Only',
                                          (BL_blood!="Any blood collected" & BL_urine!="Any urine collected" & BL_mouthwash!="Any mouthwash collected") ~ 'No Specimens Collected'))
rsch_coll$'Specimens Collected' <- factor(rsch_coll$'Specimens Collected',levels=c('Blood, Urine, Mouthwash (All)', 'Blood & Urine Only','Blood & Mouthwash Only','Urine & Mouthwash Only','Blood Only','Urine Only','Mouthwash Only','No Specimens Collected'))


clin_coll <- no_dups %>%  filter(Setting=="Clinical Collections") %>% 
  mutate('Specimens Collected'= case_when(BL_blood=="Any blood collected" & BL_urine=="Any urine collected" ~ 'Blood & Urine (All)',
                                          BL_blood=="Any blood collected" & BL_urine!="Any urine collected" ~ 'Blood Only',
                                          BL_blood!="Any blood collected" & BL_urine=="Any urine collected" ~ 'Urine Only',
                                          BL_blood!="Any blood collected" & BL_urine!="Any urine collected" ~ 'No Specimens Collected',
                                          TRUE ~ "Unknown")) %>%  filter('Specimens Collected' != "Unknown")
clin_coll$`Specimens Collected` <- factor(clin_coll$`Specimens Collected`, levels = c('Blood & Urine (All)', 'Blood Only', 'Urine Only', 'No Specimens Collected'))


coll_completenessR_totals <- create_tbl_cross(rsch_coll, 'Specimens Collected', "Site", "column", 'Specimens Collected', " ")
coll_completenessC_totals <- create_tbl_cross(clin_coll, 'Specimens Collected', "Site", "column", 'Specimens Collected', " ")

colnames(coll_completenessR_totals)[1] <- "Specimens Collected"
colnames(coll_completenessC_totals)[1] <- "Specimens Collected"

knitr::kable(coll_completenessR_totals , 
             caption='Table 2.1: Baseline Research Biospecimen Collection Completeness by Specimen Type', 
             row.names=FALSE,align=c("l","c","c","c","c","c","c"), booktabs = TRUE)  %>% 
  kable_styling(latex_options = "scale_down")




knitr::kable(coll_completenessC_totals , 
             caption='Table 2.2: Baseline Clinical Biospecimen Collection Completeness by Specimen Type', 
             row.names=FALSE,align=c("l","c","c","c","c","c","c","c","c","c"), booktabs = TRUE)  %>% 
  kable_styling(latex_options = "scale_down")

```




```{r Blood_Completeness_All, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}



### This chunk is a problem!!



# #Naming the blood tubes
# #no_dups$blood_tubes_types=0
# for (i in 1:length(no_dups$Connect_ID)){
#    sst1 = ifelse(no_dups$d_299553921[[1]]==353358909, 1, 0)
#    d_703954371,"d_454453939","d_838567176","d_652357376","d_376960806","d_232343615","d_589588440","d_677469051", "d_683613884","d_958646668", "d_505347689")
#    #blood_tubes= blood_tubes + sum(AI+As+Bl+Hs+Me+Hw+Wh+Ot, na.rm=T)
# 
# }
  

blood_tubes <- c("d_299553921","d_703954371","d_454453939","d_838567176","d_652357376","d_376960806","d_232343615","d_589588440","d_677469051", "d_683613884","d_958646668", "d_505347689")  

no_dups$deviations <-0 #Blood Collections
no_dups$blood_collections <- 0 #Deviations  
for(i in 1:length(blood_tubes)){
  
  blood_collections <- ifelse(no_dups[,paste(blood_tubes[i],"d_593843561",sep="_")] == 104430631 | is.na(no_dups[,paste(blood_tubes[i],"d_593843561",sep="_")]),0,1)  
  
  deviations <- ifelse(no_dups[,paste(blood_tubes[i],"d_678857215",sep="_")]==104430631 | is.na(no_dups[,paste(blood_tubes[i],"d_678857215",sep="_")]),0,1) 
  
  no_dups$deviations <- no_dups$deviations+deviations
  no_dups$blood_collections <- blood_collections + no_dups$blood_collections ###to check collection
}  


#Research has max of 5 tubes, clinical has a max of 11 tubes
no_dups <- no_dups %>% 
  mutate(bloodcomplete = ifelse((Setting=="Research Collections" & blood_collections == 5) | (Setting=="Clinical Collections" & blood_collections == 11), "Blood.Completion" ,
                                ifelse( (Setting=="Research Collections" & (blood_collections<5 & blood_collections>0)) | (Setting=="Clinical Collections" & (blood_collections <  11 & blood_collections > 0)),"Blood.Incompleted",
                                        "NoBlood")))

#Research had some adjustments with the ACD tube
tube_research <- tube_col %>% filter(Setting=="Research Collections") %>%
  mutate(bld.complt = ifelse(ifelse(collection.tm < as.Date("2024-03-01") | Site=="HealthPartners", bldcol_max==5, bldcol_max==4),"BloodCompletion",
                             ifelse(bldcol_max==0, "NoBlood","BloodIncomplet")))




```








```{r BUM_Survey, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}

#nothing to do with collections, duplicate collections don't matter
research <- no_dups %>%  filter(Setting=="Research Collections")

bum_survey <- create_tbl_cross(research, "research_sv", "Site", "column", " ", " ")

knitr::kable(bum_survey,  
             caption='Table 3.1: Baseline Biospecimen Survey Status Among Research Collections', 
             row.names=FALSE,align=c("l","c","c","c","c","c","c"), booktabs = TRUE)  %>% 
  kable_styling(latex_options = "scale_down") 

```



```{r BUM_UC, echo=FALSE, eval=TRUE, warning=FALSE}


fig3_sub <- research %>%  filter(Site=="University of Chicago Medicine" & !is.na(research_sv)) %>% 
  #mutate(Site = droplevels(Site)) %>% 
  arrange(Monday_collections,research_sv) %>% 
  group_by(Monday_collections,research_sv) %>% tally()


figsub3 <- fig3_sub %>%
  group_by(Monday_collections) %>%
  mutate(per_week_parts = sum(n)) %>%
  filter(research_sv == "Submitted") %>%
  mutate(weekly_sub = n) %>%
  ungroup() %>%
  mutate(cum_sub = cumsum(weekly_sub),
         cumtotal = cumsum(per_week_parts))


Fig3.1 <- ggplot(figsub3, aes(x=as.Date(Monday_collections), y=100*(cum_sub/cumtotal))) + 
  geom_line(na.rm=T) + geom_point(width = 0.2) +
  scale_y_continuous(name="Percent %",limits=c(0,100),expand=c(0,0)) + #, limits=c(0,30), breaks=seq(0,30,5)) +
  scale_x_date(name="Date",date_labels = "%y-%m-%d", date_breaks = "2 weeks", limits=c( as.Date("2022-06-20"),as.Date(currentDate)-1),expand=c(0,0))  +
  scale_fill_brewer(palette="Dark2") +
  ggtitle(label="Figure 3.1: Baseline- Cumulative Percent of Biospecimen Surveys \n Submitted, University of Chicago Medicine") +
  figure_themes




Fig3.2 <- ggplot(figsub3, aes(x=as.Date(Monday_collections), y=100*(weekly_sub/per_week_parts))) + 
  geom_line(na.rm=T) + geom_point(width = 0.2) +
  scale_y_continuous(name="Percent %",limits=c(0,100),expand=c(0,0)) + 
  scale_x_date(name="Date",date_labels = "%y-%m-%d", date_breaks = "2 weeks", limits=c( as.Date("2022-06-20"),as.Date(currentDate)-1),expand=c(0,0))  +
  ggtitle(label="Figure 3.2: Baseline- Weekly Percent of Biospecimen Surveys Submitted, \n University of Chicago Medicine") +
  figure_themes

```


```{r BU_Survey, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}

clinical <- no_dups %>%  filter(Setting=="Clinical Collections")

bu_survey <- create_tbl_cross(clinical, "clinic_sv", "Site", "column", " ", " ")

knitr::kable(bu_survey,  
             caption='Table 3.2: Baseline Biospecimen Survey Status Among Clinical Collections', 
             row.names=FALSE,align=c("l","c","c","c","c","c","c"), booktabs = TRUE)  %>% 
  kable_styling(latex_options = "scale_down") 

```



```{r, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}

rsch_srvy_time <- participants %>% 
  filter(d_265193023=='231311385' & d_821247024 == '197316935') %>%  
  select(d_222161762, d_331584571_d_266600170_d_840048338, d_822499427) %>%  as_tibble() %>% 
  mutate(rsch_comptime = difftime(as.POSIXct(ymd_hms(d_222161762)),as.POSIXct(ymd_hms(d_331584571_d_266600170_d_840048338)),units="hours"),
         rsch_check_vst = case_when(as.numeric(rsch_comptime) >72 ~"> 72hrs",
                                  72 >= as.numeric(rsch_comptime) & as.numeric(rsch_comptime) > 48 ~ "> 48 hrs to 72 hrs",
                                  48 >= as.numeric(rsch_comptime) & as.numeric(rsch_comptime) > 24 ~ "> 24 hrs to 48 hrs",
                                  24 >= as.numeric(rsch_comptime) & as.numeric(rsch_comptime) > 12 ~ "> 12 hrs to 24 hrs",
                                  12 >= as.numeric(rsch_comptime) & as.numeric(rsch_comptime) > 3 ~ "> 3 hrs to 12 hrs",    
                                  3 >= as.numeric(rsch_comptime) & as.numeric(rsch_comptime) >= 0 ~ "0 hrs to 3 hrs", 
                                  TRUE ~ "Missing Time"),
         rsch_check_vst = factor(rsch_check_vst, levels=c("Missing Time", "0 hrs to 3 hrs", "> 3 hrs to 12 hrs",
                                                          "> 12 hrs to 24 hrs", "> 24 hrs to 48 hrs", "> 48 hrs to 72 hrs", 
                                                          "> 72hrs")))


svry_before_covid <- rsch_srvy_time %>% filter(d_222161762<as.Date("2023-07-05"))
svry_after_covid <- rsch_srvy_time %>% filter(d_222161762>as.Date("2023-07-05"))


svry_bf_covid <- create_tbl_cross(svry_before_covid, 'rsch_check_vst', "Site", "column", ' ', " ")
svry_aft_covid <- create_tbl_cross(svry_after_covid, 'rsch_check_vst', "Site", "column", ' ', " ")



tbl19a <-knitr::kable(svry_bf_covid, 
                      caption='Table 3.3: Baseline Biospecimen Survey Completion Time from Research Collection Visit Check In \n (Pre-COVID- 19 Questions Removal)',
                      row.names=FALSE,align=c("l","c","c","c","c","c","c"), booktabs = TRUE)  %>% 
    kable_styling(latex_options = "scale_down")
add_footnote(tbl19a,"Note: The COVID-19 survey questions were separated from the Biospecimen Survey on July 5, 2023.", notation = "none") 




tbl19b <- knitr::kable(svry_aft_covid, 
                       caption='Table 3.4: Baseline Biospecimen Survey Completion Time from Research Collection Visit Check In \n (Post- COVID-19 Questions Removal)',
                       row.names=FALSE,align=c("l","c","c","c","c","c","c"), booktabs = TRUE)  %>% 
    kable_styling(latex_options = "scale_down")
add_footnote(tbl19b,"Note: The COVID-19 survey questions were separated from the Biospecimen Survey on July 5, 2023.", notation = "none")




##################

svry_before_covid 
svry_after_covid

```



```{r, eval=TRUE,echo=FALSE,include=FALSE,results='hold'}


##References collection time, so can't have duplicate (blood and urine collections)
clin_srvy_time <- no_dups %>%  
  filter(Setting=="Clinical Collections" & BU_completion_status=="Submitted" & !is.na(d_764863765) & !is.na(d_534669573))
  mutate(ctime = as.numeric(difftime(as.POSIXct(ymd_hms(d_764863765)),as.POSIXct(ymd_hms(d_534669573)),units="hours")))

  
#we should only have to use 740582332 here, but it is not derived correctly every time
clin_srvy_coll <- clin_srvy_time %>% 
  mutate(clin_comptime = difftime(as.POSIXct(ymd_hms(d_764863765)),as.POSIXct(ymd_hms(d_534669573)),units="hours"),
         d_173836415_d_266600170_d_139245758_clc = as.POSIXct(ymd_hms(d_173836415_d_266600170_d_139245758)), ##urine
         d_173836415_d_266600170_d_982213346_clc = as.POSIXct(ymd_hms(d_173836415_d_266600170_d_982213346)), ##blood collected
         d_173836415_d_266600170_d_740582332_clc = as.POSIXct(ymd_hms(d_173836415_d_266600170_d_740582332)), ##Autogenerated date/time stamp for Any specimen collected at RRL
         clc.coltm  = do.call(pmin, c(select(.,ends_with('clc')),na.rm=TRUE)),
         clin_srvy_startstop = case_when(as.numeric(clin_comptime) >72 ~"> 72hrs",
                                  72 >= as.numeric(clin_comptime) & as.numeric(clin_comptime) > 48 ~ "> 48 hrs to 72 hrs",
                                  48 >= as.numeric(clin_comptime) & as.numeric(clin_comptime) > 24 ~ "> 24 hrs to 48 hrs",
                                  24 >= as.numeric(clin_comptime) & as.numeric(clin_comptime) > 12 ~ "> 12 hrs to 24 hrs",
                                  12 >= as.numeric(clin_comptime) & as.numeric(clin_comptime) > 3 ~ "> 3 hrs to 12 hrs",    
                                  3 >= as.numeric(clin_comptime) & as.numeric(clin_comptime) >= 0 ~ "0 hrs to 3 hrs", 
                                  TRUE ~ "Missing Time"),
         clin_srvy_startstop = factor(clin_srvy_startstop, levels=c("Missing Time", "0 hrs to 3 hrs", "> 3 hrs to 12 hrs",
                                                          "> 12 hrs to 24 hrs", "> 24 hrs to 48 hrs", "> 48 hrs to 72 hrs", 
                                                          "> 72hrs")))


svry_before_covid <- clin_srvy_time %>% filter(d_764863765<as.Date("2023-07-05"))
svry_after_covid <- clin_srvy_time %>% filter(d_764863765>as.Date("2023-07-05"))


svry_bf_covid <- create_tbl_cross(svry_before_covid, 'clin_srvy_startstop', "Site", "column", ' ', " ")
svry_aft_covid <- create_tbl_cross(svry_after_covid, 'clin_srvy_startstop', "Site", "column", ' ', " ")



tbl19a <-knitr::kable(svry_bf_covid, 
                      caption='Table 3.5: Baseline Clinical Biospecimen Survey Complete Time from Collection Time',
                      row.names=FALSE,align=c("l","c","c","c","c","c","c"), booktabs = TRUE)  %>% 
    kable_styling(latex_options = "scale_down")




###################
clin_srvy_time <- no_dups %>% 
  filter(BU_completion_status=="Submitted") %>% 
  mutate(clin_comptime = difftime(as.POSIXct(ymd_hms(d_764863765)),as.POSIXct(ymd_hms(d_534669573)),units="hours"),
         clin_srvy_startstop = case_when(as.numeric(clin_comptime) >72 ~"> 72hrs",
                                  72 >= as.numeric(clin_comptime) & as.numeric(clin_comptime) > 48 ~ "> 48 hrs to 72 hrs",
                                  48 >= as.numeric(clin_comptime) & as.numeric(clin_comptime) > 24 ~ "> 24 hrs to 48 hrs",
                                  24 >= as.numeric(clin_comptime) & as.numeric(clin_comptime) > 12 ~ "> 12 hrs to 24 hrs",
                                  12 >= as.numeric(clin_comptime) & as.numeric(clin_comptime) > 3 ~ "> 3 hrs to 12 hrs",    
                                  3 >= as.numeric(clin_comptime) & as.numeric(clin_comptime) >= 0 ~ "0 hrs to 3 hrs", 
                                  TRUE ~ "Missing Time"),
         clin_srvy_startstop = factor(clin_srvy_startstop, levels=c("Missing Time", "0 hrs to 3 hrs", "> 3 hrs to 12 hrs",
                                                          "> 12 hrs to 24 hrs", "> 24 hrs to 48 hrs", "> 48 hrs to 72 hrs", 
                                                          "> 72hrs")))


svry_before_covid <- clin_srvy_time %>% filter(d_764863765<as.Date("2023-07-05"))
svry_after_covid <- clin_srvy_time %>% filter(d_764863765>as.Date("2023-07-05"))


svry_bf_covid <- create_tbl_cross(svry_before_covid, 'clin_srvy_startstop', "Site", "column", ' ', " ")
svry_aft_covid <- create_tbl_cross(svry_after_covid, 'clin_srvy_startstop', "Site", "column", ' ', " ")



tbl19a <-knitr::kable(svry_bf_covid, 
                      caption='Table 3.6: Baseline Biospecimen Survey Completion Length (in Minutes) \n Among Submitted Research Surveys (Pre-COVID-19 Questions Removal)',
                      row.names=FALSE,align=c("l","c","c","c","c","c","c"), booktabs = TRUE)  %>% 
    kable_styling(latex_options = "scale_down")
add_footnote(tbl19a,"Note: The COVID-19 survey questions were separated from the Biospecimen Survey on July 5, 2023. Research biospecimen surveys with a negative completion time have been excluded.", notation = "none") 




tbl19b <- knitr::kable(svry_aft_covid, 
                       caption='Table 3.7: Baseline Biospecimen Survey Completion Length (in Minutes) \n Among Submitted Research Surveys (Post-COVID-19 Questions Removal)',
                       row.names=FALSE,align=c("l","c","c","c","c","c","c"), booktabs = TRUE)  %>% 
    kable_styling(latex_options = "scale_down")
add_footnote(tbl19b,"Note: The COVID-19 survey questions were separated from the Biospecimen Survey on July 5, 2023.", notation = "none")


```